#ifndef RECOIL_FEATURES_CONFIG_AIMBOT_CONFIG_H
#define RECOIL_FEATURES_CONFIG_AIMBOT_CONFIG_H

#include "core/types.h"

#define SCAN_MAX 256
#define RCL_AIM 1
#define RCL_AIM_INTERVAL 12
#define RCL_AIM_RANGE 3000.0f
#define RCL_AIM_PRED_MAX 3
#define RCL_AIM_PRED_COEF 0.8f
#define RCL_AIM_PROJ_SPEED 3255.0f

#endif
