#ifndef TITANOX_SCAN_SCAN_H
#define TITANOX_SCAN_SCAN_H

#include "core/types.h"

extern uintptr_t t_mgr;
extern int t_mgr_logs;
extern int t_test_state;
extern int t_test_after_x;
extern int t_test_after_y;
extern int t_moved;
extern int t_moved2;
extern int t_kept;
extern int t_tested;
extern int t_ok;
extern uint64_t t_writes;
extern uint64_t t_tick_2;
extern int t_attempt;
extern int t_prev_state;
extern int t_other_logs;
extern int t_other_detail;
extern uintptr_t t_own_ptr_2;
extern int t_own_index_2;
extern int t_own_team_2;
extern int t_own_base;
extern int t_own_logs_2;
extern int t_audited;
extern int t_inject_logs;
extern const char *t_own_from_2;
extern uint64_t t_tick;
extern uint64_t t_write_last;
extern int t_write_phase;
extern int t_write_count;
extern int t_write_base_ok;
extern int t_write_base_x;
extern int t_write_base_y;
extern int t_trace_logs;
extern int t_trace_n;
extern uintptr_t t_trace_obj[TNX_OBJECT_MAX];
extern int t_trace_x[TNX_OBJECT_MAX];
extern int t_trace_y[TNX_OBJECT_MAX];
extern int t_hop_chosen;
extern int t_hop_sticky;
extern int t_coord_off;
extern int t_modesig_hits;
extern int t_modesig_notfound;
extern int t_floor_logged;
extern int t_fallback_logged;
extern int t_census_logs;
extern int t_elem_dumps;
extern int t_hop2_census;
extern int t_type3_floats;
extern uintptr_t t_census_container;
extern int32_t t_census_count;
extern uintptr_t t_census_array;
extern uintptr_t t_census_first;
extern uint64_t t_census_ms;
extern int t_slot_dumped;
extern int t_gate_calls;
extern uintptr_t t_own_ptr_4;
extern int t_own_index_3;
extern int t_own_src;
extern uintptr_t t_own_off;
extern uintptr_t t_scan_container;
extern int t_scan_logs;
extern int t_own_logged;
extern int32_t t_wrote_x;
extern int32_t t_wrote_y;
extern int32_t t_own_pos_x;
extern int32_t t_own_pos_y;
extern uint64_t t_wrote_tick;
extern int t_wrote_valid;
extern int t_check_done;
extern uint64_t t_test_writes;
extern int t_class_dumps;
extern const char *t_own_from_4;
extern int t_players_dumps;
extern int t_hop_dumps;
extern int t_modehit_dump;
extern uint64_t t_prev_upd;
extern uint64_t t_prev_rend;
extern uint64_t t_pred_took;
extern uint64_t t_pred_miss;
extern int t_pred_logs;
extern uintptr_t t_hop_scene;
extern int t_gid_logs;
extern int t_coord_logs;
extern int t_dump_done;
extern int t_score_logs;
extern int t_last_choice;
extern int t_hop_logs;
extern int t_start_logged;
extern uintptr_t t_setpred_2;
extern int t_setpred_state;
extern int t_probe_done_2;
extern uintptr_t t_probe_object;
extern uint64_t t_probe_last_ms;
extern int t_coord_ok;
extern int t_coord_usable;
extern int t_coord_distinct;
extern int t_team_off;
extern int t_map_w;
extern int t_map_h;
extern int t_map_ok;
extern uint64_t t_ticks_2;
extern uint64_t t_threat_ticks;
extern uint64_t t_writes_3;
extern uint64_t t_last_write_ms;
extern int t_giveup_logs;
extern uint64_t t_probe_tick;
extern tnx_obj_t t_dodge_probe_list[TNX_OBJECT_MAX];
extern int t_gidless;
extern int t_gidless_logs;
extern int t_gidoff_logs;
extern int t_stage;
extern int t_stuck;
extern int32_t t_last_x;
extern int32_t t_last_y;
extern int t_logs_3;
extern int t_dead;
extern int t_revive_logs;
extern int t_own_team_3;
extern int t_proj_own;
extern int t_proj_other;
extern int t_own_team_seen;
extern int t_filter_logs;
extern int t_drop_along;
extern int t_drop_reach;
extern int t_live_threats;
extern int t_team_other_seen;
extern int t_stick_cleared;
extern uintptr_t t_proj_addr;
extern uint8_t t_proj_bytes[TNX_DIFF_BYTES];
extern int t_proj_have;
extern int t_proj_dumps;
extern uint64_t t_proj_diff_logs;
extern uint64_t t_proj_firsts;
extern int t_latch_logs;
extern int t_mode_seen7;
extern int t_mode_max;
extern int t_gate_seen;
extern uintptr_t t_own_obj;
extern uintptr_t t_elem;
extern int32_t t_elem_x0;
extern int32_t t_elem_y0;
extern int32_t t_own_before_x;
extern int32_t t_own_before_y;
extern int t_setter_called;
extern int t_elem_called;
extern int t_rb_logs;
extern uintptr_t t_own_elem;
extern uint64_t t_own_stamp;
extern int t_own_logs_6;
extern uintptr_t t_own_ptr_3;
extern int32_t t_own_gid;
extern int t_own_logs_4;
extern int t_own_logs_5;
extern tnx_proj_t t_projs[TNX_PROJ_MAX];
extern int t_side_hits;
extern int t_side_projs;
extern int t_signal_logs;
extern int t_map_dumps;
extern float t_walk_step;
extern int32_t t_prev_x_3;
extern int32_t t_prev_y_3;
extern int t_prev_ok;
extern uint64_t t_measured;
extern const char *const t_names[TNX_BASES];
extern int t_owner_logs;
extern uint64_t t_dropped_2;

void tnx_alert_menu(NSString *info);
int tnx_modesig_hit(uintptr_t at);
void tnx_modesig_tick(void);
void tnx_players_dump(uintptr_t players, uintptr_t array, int32_t count, int32_t capacity);
void tnx_battle_alert(uintptr_t scene, uintptr_t scenePrev);
int tnx_element_type(uintptr_t vt, uintptr_t *wordOut);
void tnx_container_census(uintptr_t array, int32_t count, uintptr_t container);
int tnx_container_header(uintptr_t object, uintptr_t *arrayOut, int32_t *countOut, int32_t *capOut, char *why, size_t whyLen);
void tnx_hop_dump(uintptr_t client, uintptr_t inner);
int32_t tnx_gid_at(uintptr_t element, uintptr_t off);
int32_t tnx_gid(uintptr_t element, int32_t *offOut);
void tnx_own_dump(uintptr_t element);
int tnx_container_score(uintptr_t container);
int tnx_own_verdict(uintptr_t element, char *why, size_t whyLen);
NSString *tnx_status_text(void);
int tnx_scan_ready(int battle);
void tnx_resolve_addresses(void);
int tnx_mode_score(uintptr_t mode);
BOOL tnx_is_mode_vtable(uintptr_t value, uintptr_t *rvaOut);
void tnx_locate_battle_mode(void);
int tnx_trail_beats_slot(int live, int nonEmpty, int32_t count, int slot);
int tnx_trail_ranked(int *out, int max);
int tnx_verify_setprediction(void);
void tnx_read_map(uintptr_t mode);
void tnx_gidless_scan(uintptr_t manager);
uintptr_t tnx_list_gid_off(uintptr_t array, int32_t count);
void tnx_proj_track(uintptr_t elem, uintptr_t classRva, int32_t gid, int32_t team);
void tnx_team_dump(const tnx_obj_t *objects, int usable);
void tnx_class_dump(const tnx_obj_t *objects, int usable);
int tnx_slot_probe(void);
int tnx_mode_real(uintptr_t mode, uintptr_t *vtOut, uintptr_t *chainOut, uintptr_t *innerOut);
void tnx_own_probe(void);
int tnx_inject_own(tnx_obj_t *objects, int usable, int capacity);
int tnx_own_latch(const tnx_obj_t *objects, int usable, int *indexOut, const char **fromOut);
int tnx_take_own(const tnx_obj_t *objects, int usable, int *indexOut, const char **fromOut);
void tnx_pos_trace(const tnx_obj_t *objects, int usable);
void tnx_write_test(const tnx_obj_t *objects, int usable, int ownIndex);
void tnx_audit_all(void);
int tnx_read_flag(void);
int tnx_vt_ok(uintptr_t obj, uintptr_t *vtOut);
int tnx_cand_ok(uintptr_t cand, const char **why, uintptr_t *vtOut);
uintptr_t tnx_hop(uintptr_t base, int *whyOut);
uintptr_t tnx_own_obj(void);
void tnx_setter(int32_t vx, int32_t vy);
void tnx_elem_write(uintptr_t element, int32_t vx, int32_t vy);
int tnx_mode(void);
int tnx_inner(void);
int tnx_gate(void);
uintptr_t tnx_client(void);
int tnx_own_by_min_gid(uintptr_t array, int32_t count, uintptr_t *elemOut, int32_t *gidOut);
int tnx_own_from_list(const tnx_obj_t *objects, int usable, int *indexOut, const char **fromOut);
void tnx_statics(void);
void tnx_readback(int plus);
void tnx_state_note(int state);
int tnx_own_scan(void);
int tnx_resolve_own_2(const tnx_obj_t *objects, int usable, int *indexOut, const char **fromOut);
void tnx_gate_report(int slotHit);
int tnx_proj_scan(uintptr_t manager, int32_t count);
extern int t_ctrl_pick;

uintptr_t tnx_controller(void);
void tnx_watch(int32_t ownX, int32_t ownY);
void tnx_death_signals(uintptr_t ownElem, int32_t ownX, int32_t ownY);
void tnx_alive(int32_t ownX, int32_t ownY);
void tnx_map_dump(uintptr_t bounds);
void tnx_census(void);
int tnx_own(int32_t *xOut, int32_t *yOut);
float tnx_step(void);
void tnx_measure(void);
int tnx_proj_mine(const tnx_proj_t *p);
uint64_t tnx_upd_delta(void);
uint64_t tnx_rend_delta(void);
void tnx_state(void);
uint64_t tnx_word_2(uintptr_t address);
const char *tnx_header_reason(uintptr_t manager, int32_t *countOut, int32_t *capOut);
uintptr_t tnx_coord_x_off(void);
uintptr_t tnx_coord_y_off(void);

extern int32_t t_gid_hi;
extern int32_t t_gid_lo;
extern const uintptr_t t_mode_vtables[36];
extern int t_proj_skipped;
extern int t_tnx_verbose;
extern tnx_trail_t t_trail[TNX_TRAIL_MAX];
int tnx_ctrl_bounds_2(uintptr_t base, int32_t *wOut, int32_t *hOut);
void tnx_paircal(void);
void tnx_probe_3(uintptr_t manager, uintptr_t mode, int verbose);

#endif
