#ifndef TITANOX_SCAN_SCAN_H
#define TITANOX_SCAN_SCAN_H

#include "core/types.h"

extern uintptr_t t_scene_object;

extern int t_prev_state;
extern uintptr_t t_own_ptr_a;
extern const char *t_own_from_a;
extern int t_hop_chosen;
extern int t_hop_sticky;
extern int t_modesig_hits;
extern int t_floor_logged;
extern int t_fallback_logged;
extern int t_elem_dumps;
extern int t_hop2_census;
extern int t_type3_floats;
extern uintptr_t t_census_container;
extern uintptr_t t_census_array;
extern uintptr_t t_census_first;
extern uint64_t t_census_ms;
extern uintptr_t t_own_ptr_b;
extern int t_own_index_3;
extern uintptr_t t_scan_container;
extern int t_own_logged;
extern uint64_t t_wrote_tick;
extern int t_wrote_valid;
extern int t_check_done;
extern uint64_t t_pred_took;
extern uint64_t t_pred_miss;
extern uintptr_t t_hop_scene;
extern int t_gid_logs;
extern int t_coord_logs;
extern int t_dump_done;
extern int t_last_choice;
extern int t_hop_logs;
extern int t_setpred_state;
extern int t_probe_done;
extern uintptr_t t_probe_object;
extern uint64_t t_probe_last_ms;
extern int t_coord_ok;
extern int t_coord_usable;
extern int t_team_off;
extern int t_map_ok;
extern uint64_t t_last_write_ms;
extern tnx_obj_t t_dodge_probe_list[TNX_OBJECT_MAX];
extern int t_gidless;
extern int t_stage;
extern int32_t t_last_x;
extern int32_t t_last_y;
extern int t_dead;
extern int t_own_team_a;
extern int t_proj_own;
extern int t_proj_other;
extern int t_own_team_seen;
extern int t_team_other_seen;
extern uintptr_t t_proj_addr;
extern uint8_t t_proj_bytes[TNX_DIFF_BYTES];
extern int t_proj_have;
extern int t_proj_dumps;
extern uint64_t t_proj_diff_logs;
extern uintptr_t t_own_elem;
extern uint64_t t_own_stamp;
extern int t_own_logs_b;
extern int32_t t_own_gid;
extern tnx_proj_t t_projs[TNX_PROJ_MAX];
extern int t_side_hits;
extern int t_side_projs;
extern int t_signal_logs;
extern float t_walk_step;
extern int32_t t_prev_x_3;
extern int32_t t_prev_y_3;
extern int t_prev_ok;

int tnx_modesig_hit(uintptr_t at);
void tnx_modesig_tick(void);
int tnx_element_type(uintptr_t vt, uintptr_t *wordOut);
void tnx_container_census(uintptr_t array, int32_t count, uintptr_t container);
int tnx_container_header(uintptr_t object, uintptr_t *arrayOut, int32_t *countOut, int32_t *capOut, char *why, size_t whyLen);
int32_t tnx_gid_at(uintptr_t element, uintptr_t off);
int32_t tnx_gid(uintptr_t element, int32_t *offOut);
void tnx_own_dump(uintptr_t element);
int tnx_container_score(uintptr_t container);
int tnx_own_verdict(uintptr_t element, char *why, size_t whyLen);
int tnx_scan_ready(int battle);
void tnx_resolve_addresses(void);
void tnx_locate_battle_mode(void);
int tnx_verify_setprediction(void);
void tnx_read_map(uintptr_t mode);
void tnx_gidless_scan(uintptr_t manager);
uintptr_t tnx_list_gid_off(uintptr_t array, int32_t count);
void tnx_proj_track(uintptr_t elem, uintptr_t classRva, int32_t gid, int32_t team);
int tnx_mode_real(uintptr_t mode, uintptr_t *vtOut, uintptr_t *chainOut, uintptr_t *innerOut);
void tnx_own_probe(void);
int tnx_own_latch(const tnx_obj_t *objects, int usable, int *indexOut, const char **fromOut);
int tnx_vt_ok(uintptr_t obj, uintptr_t *vtOut);
int tnx_cand_ok(uintptr_t cand, const char **why, uintptr_t *vtOut);
uintptr_t tnx_hop(uintptr_t base, int *whyOut);
uintptr_t tnx_own_obj(void);
uintptr_t tnx_client(void);
int tnx_own_by_min_gid(uintptr_t array, int32_t count, uintptr_t *elemOut, int32_t *gidOut);
int tnx_own_from_list(const tnx_obj_t *objects, int usable, int *indexOut, const char **fromOut);
void tnx_state_note(int state);
int tnx_own_scan(void);
int tnx_resolve_own_2(const tnx_obj_t *objects, int usable, int *indexOut, const char **fromOut);
int tnx_proj_scan(uintptr_t manager, int32_t count);

uintptr_t tnx_controller(void);
void tnx_watch(int32_t ownX, int32_t ownY);
void tnx_death_signals(uintptr_t ownElem, int32_t ownX, int32_t ownY);
void tnx_alive(int32_t ownX, int32_t ownY);
int tnx_own(int32_t *xOut, int32_t *yOut);
float tnx_step(void);
void tnx_measure(void);
int tnx_proj_mine(const tnx_proj_t *p);
void tnx_state(void);
uint64_t tnx_word_2(uintptr_t address);
const char *tnx_header_reason(uintptr_t manager, int32_t *countOut, int32_t *capOut);
uintptr_t tnx_coord_x_off(void);
uintptr_t tnx_coord_y_off(void);

extern int32_t t_gid_hi;
extern int32_t t_gid_lo;
extern const uintptr_t t_mode_vtables[36];
extern tnx_trail_t t_trail[TNX_TRAIL_MAX];
int tnx_ctrl_bounds(uintptr_t base, int32_t *wOut, int32_t *hOut);
void tnx_paircal(void);
void tnx_probe(uintptr_t manager, uintptr_t mode, int verbose);

#endif
