#ifndef TITANOX_HELPERS_MOVE_H
#define TITANOX_HELPERS_MOVE_H

#include "core/types.h"

extern uint64_t g_diag_us;
extern uint64_t g_diag_max_us;
extern int g_dead_probe_done;
extern uint64_t g_clamped;
extern uint64_t g_ctrl_dead;
extern uint64_t g_stuck_3;
extern uint64_t g_mask_before;
extern int g_body_blocks;
extern int g_body_mine;
extern int g_body_enemy;
extern int g_body_logs;
extern uint64_t g_human_live;
extern int g_input_skips;
extern int g_wrote_input;
extern int g_engaged_frame;
extern int g_neutral_logs;
extern int g_test_state_2;
extern uint64_t g_test_tick;
extern int g_test_before_x;
extern int g_test_before_y;
extern int g_test_after_x_2;
extern int g_test_after_y_2;
extern int g_moved_2;
extern int g_moved2_2;
extern int g_kept_2;
extern int g_tested_2;
extern uint64_t g_enqueues;
extern int g_enq_x;
extern int g_enq_y;
extern int g_q_before;
extern int g_q_after;
extern int g_readback;
extern int g_readback_tick;
extern int g_hop2_logs;
extern int g_hop2_filled;
extern uintptr_t g_hop2;
extern int g_queue_logs;
extern int g_window_logs;
extern uint64_t g_push_frame;
extern int g_frame_logs;
extern uint64_t g_test_tickbase;
extern int g_enq_ok;
extern const char *g_alloc_how;
extern void *g_msg;
extern int g_seq_before;
extern int g_seq_after;
extern int g_q_before_2;
extern int g_q_after_2;
extern void *g_q_last;
extern int32_t g_scene_before_x;
extern int32_t g_scene_before_y;
extern uint64_t g_watch_from;
extern int g_watch_logs;
extern uintptr_t g_pred_last;
extern int g_predict_logs;
extern uint64_t g_pred_calls;
extern uint64_t g_pred_fails;
extern uintptr_t g_wit_elem;
extern int32_t g_wit_x0;
extern int32_t g_wit_y0;
extern int32_t g_wit_x1;
extern int32_t g_wit_y1;
extern int32_t g_own_held_x;
extern int32_t g_own_held_y;
extern int32_t g_own_flag;
extern int g_have_wit;
extern int g_active;
extern int g_calls;
extern int g_act_logs;
extern int g_wit_logs;
extern int g_own_logs_3;
extern int g_probe_done;
extern int64_t g_moves;
extern int64_t g_elem_moves;
extern uintptr_t g_joystick;
extern uint64_t g_joystick_writes;
extern uint64_t g_joystick_took;
extern int32_t g_stick_x;
extern int32_t g_stick_y;
extern int g_stick_hold;
extern uint64_t g_stick_tick;
extern int g_engaged_ticks;
extern long long g_sum_x;
extern long long g_sum_y;
extern int g_route_seeded;
extern int32_t g_last_own_x;
extern int32_t g_last_own_y;
extern uint64_t g_drag_writes_2;
extern uint64_t g_back_ok;
extern uint64_t g_back_bad;
extern int g_precond;
extern int g_gate;
extern int g_accepted;
extern int g_proofs;
extern int g_drove;
extern uint64_t g_drive_tick;
extern float g_mark;
extern float g_dot;
extern float g_last_dx;
extern float g_last_dy;
extern int32_t g_raw_x;
extern int32_t g_raw_y;
extern int32_t g_app_x;
extern int32_t g_app_y;

int tnx_mode_2(void);
float tnx_look_ms(void);
int tnx_ctrl_ok(uintptr_t ctrl);
void *tnx_msg_alloc(void);
void *tnx_q_last(void);
uintptr_t tnx_entry_2(uintptr_t rva);
void *tnx_manager(void);
int tnx_queue_count(uintptr_t *mgrOut);
int tnx_predict(int32_t x, int32_t y);
int tnx_pending(int want, uint64_t *mask);
int tnx_enqueue(int x, int y);
const char *tnx_state_x(int32_t v);
const char *tnx_state_y(int32_t v);
int tnx_witness(int32_t *x, int32_t *y);
void tnx_probe(void);
int tnx_resolve_own(const tnx_obj_t *objects, int usable, int *indexOut, const char **fromOut);
void tnx_actuate(void);
void tnx_witness_line(int plus);
int tnx_fields_pair(uintptr_t *srcOut, int32_t *xOut, int32_t *yOut);
int tnx_fields(void);
void tnx_frame_window(void);
void tnx_window(int plus);
void tnx_test(const tnx_obj_t *objects, int usable, int ownIndex);
void tnx_queue_line(void);
void tnx_hop2(void);
float tnx_seg_dist(float ax, float ay, float bx, float by, float px, float py);
int tnx_proj_vel(const tnx_proj_t *p, float *vxOut, float *vyOut);
uintptr_t tnx_input_mgr(void);
void tnx_input_release(void);
int tnx_sign(void);
void tnx_snapshot_3(void);
void tnx_drag(int engaged, int haveOwn, int32_t ownX, int32_t ownY, float dirX, float dirY);
void tnx_stick(int engaged, float dirX, float dirY);
void tnx_route(int engaged);
void tnx_threats(void);
int tnx_body_blocked(float x, float y, float ownX, float ownY);

#endif
