#ifndef TITANOX_HELPERS_SCAN_H
#define TITANOX_HELPERS_SCAN_H

#include "core/types.h"

extern uintptr_t g_v103_mgr;
extern int g_v103_mgr_logs;
extern int g_v103_test_state;
extern int g_v103_test_after_x;
extern int g_v103_test_after_y;
extern int g_v103_moved;
extern int g_v103_moved2;
extern int g_v103_kept;
extern int g_v103_tested;
extern int g_v103_ok;
extern uint64_t g_v103_writes;
extern uint64_t g_v103_tick;
extern int g_v103_attempt;
extern int g_v103_prev_state;
extern int g_v103_other_logs;
extern int g_v103_other_detail;
extern uintptr_t g_v102_own_ptr;
extern int g_v102_own_index;
extern int g_v102_own_team;
extern int g_v102_own_base;
extern int g_v102_own_logs;
extern int g_v102_audited;
extern int g_v102_inject_logs;
extern const char *g_v102_own_from;
extern uint64_t g_v102_tick;
extern uint64_t g_v102_write_last;
extern int g_v102_write_phase;
extern int g_v102_write_count;
extern int g_v102_write_base_ok;
extern int g_v102_write_base_x;
extern int g_v102_write_base_y;
extern int g_v102_trace_logs;
extern int g_v102_trace_n;
extern uintptr_t g_v102_trace_obj[TNX_V47_OBJECT_MAX];
extern int g_v102_trace_x[TNX_V47_OBJECT_MAX];
extern int g_v102_trace_y[TNX_V47_OBJECT_MAX];
extern int g_v82_hop_chosen;
extern int g_v82_hop_sticky;
extern int g_v57_coord_off;
extern int g_v64_modesig_hits;
extern int g_v64_modesig_notfound;
extern int g_v68_probe_logs;
extern int g_v68_gate_logs;
extern int g_v68_dump_logs;
extern int g_v71_array_reject_logs;
extern int g_v76_floor_logged;
extern int g_v76_fallback_logged;
extern int g_v81_census_logs;
extern int g_v86_elem_dumps;
extern int g_v86_hop2_census;
extern int g_v86_type3_floats;
extern uintptr_t g_v134_census_container;
extern int32_t g_v134_census_count;
extern uintptr_t g_v134_census_array;
extern uintptr_t g_v134_census_first;
extern uint64_t g_v134_census_ms;
extern int g_v90_slot_dumped;
extern int g_v90_gate_calls;
extern uintptr_t g_v91_own_ptr;
extern int g_v91_own_index;
extern int g_v91_own_src;
extern uintptr_t g_v91_own_off;
extern uintptr_t g_v91_scan_container;
extern int g_v91_scan_logs;
extern int g_v91_own_logged;
extern int32_t g_v92_wrote_x;
extern int32_t g_v92_wrote_y;
extern int32_t g_v92_own_pos_x;
extern int32_t g_v92_own_pos_y;
extern uint64_t g_v92_wrote_tick;
extern int g_v92_wrote_valid;
extern int g_v92_check_done;
extern uint64_t g_v93_test_tick;
extern uint64_t g_v93_test_writes;
extern int g_v93_class_dumps;
extern } tnx_v96_slot_t;
extern const char *g_v91_own_from;
extern int g_v81_players_dumps;
extern int g_v82_hop_dumps;
extern int g_v71_modehit_dump;
extern uint64_t g_v239_prev_upd;
extern uint64_t g_v239_prev_rend;
extern uint64_t g_v198_pred_took;
extern uint64_t g_v198_pred_miss;
extern int g_v198_pred_logs;
extern uintptr_t g_v82_hop_scene;
extern int g_v106_gid_logs;
extern int g_v106_coord_logs;
extern int g_v106_dump_done;
extern int g_v105_score_logs;
extern int g_v105_last_choice;
extern int g_v105_hop_logs;
extern int g_v105_start_logged;
extern } tnx_v47_obj_t;
extern uintptr_t g_v47_setpred;
extern int g_v47_setpred_state;
extern int g_v47_probe_done;
extern uintptr_t g_v47_probe_object;
extern uint64_t g_v47_probe_last_ms;
extern int g_v47_coord_ok;
extern int g_v47_coord_usable;
extern int g_v47_coord_distinct;
extern int g_v47_map_w;
extern int g_v47_map_h;
extern int g_v47_map_ok;
extern uint64_t g_v47_ticks;
extern uint64_t g_v47_threat_ticks;
extern uint64_t g_v47_writes;
extern uint64_t g_v47_last_write_ms;
extern int g_v47_giveup_logs;
extern uint64_t g_v135_probe_tick;
extern tnx_v47_obj_t g_dodge_probe_list[TNX_V47_OBJECT_MAX];
extern int g_v127_gidless;
extern int g_v127_gidless_logs;
extern int g_v135_gidoff_logs;
extern int g_v167_stage;
extern int g_v167_stuck;
extern int32_t g_v167_last_x;
extern int32_t g_v167_last_y;
extern int g_v167_logs;
extern int g_v167_moves_logs;
extern int g_v167_dead;
extern int g_v167_revive_logs;
extern int g_v167_own_team;
extern int g_v167_proj_own;
extern int g_v167_proj_other;
extern int g_v167_own_team_seen;
extern int g_v167_filter_logs;
extern int g_v167_drop_along;
extern int g_v167_drop_reach;
extern int g_v167_live_threats;
extern int g_v167_team_other_seen;
extern int g_v167_stick_cleared;
extern uintptr_t g_v140_proj_addr;
extern uint8_t g_v140_proj_bytes[TNX_V140_DIFF_BYTES];
extern int g_v140_proj_have;
extern int g_v140_proj_dumps;
extern uint64_t g_v140_proj_diff_logs;
extern uint64_t g_v140_proj_firsts;
extern int g_v183_latch_logs;
extern int g_v115_mode_wait_logs;
extern int g_v115_mode_seen7;
extern int g_v115_mode_max;
extern int g_v115_gate_seen;
extern uintptr_t g_v127_own_obj;
extern uintptr_t g_v127_elem;
extern int32_t g_v127_elem_x0;
extern int32_t g_v127_elem_y0;
extern int32_t g_v127_own_before_x;
extern int32_t g_v127_own_before_y;
extern int g_v127_setter_called;
extern int g_v127_elem_called;
extern int g_v127_rb_logs;
extern uintptr_t g_v144_own_elem;
extern uint64_t g_v144_own_stamp;
extern int g_v144_own_logs;
extern uint64_t g_v144_raw_writes;
extern uint64_t g_v144_raw_skips;
extern uintptr_t g_v134_own_ptr;
extern int32_t g_v134_own_gid;
extern int g_v134_own_logs;
extern int g_v135_own_logs;
extern } tnx_v140_proj_t;
extern tnx_v140_proj_t g_v140_projs[TNX_V140_PROJ_MAX];
extern int g_v140_side_hits;
extern int g_v140_side_projs;
extern int g_v169_signal_logs;
extern int g_v163_map_dumps;
extern float g_v231_walk_step;
extern int32_t g_v231_prev_x;
extern int32_t g_v231_prev_y;
extern int g_v231_prev_ok;
extern uint64_t g_v231_measured;
extern const char *const g_v173_names[TNX_V173_BASES];
extern } tnx_v173_win_t;
extern tnx_v173_win_t g_v173_win[TNX_V173_BASES];
extern int g_v204_owner_logs;
extern uint64_t g_v204_dropped;
extern int g_v198_logs;
extern int g_v198_probe_done;

void tnx_v62_alert_menu(NSString *info);
int tnx_v64_modesig_hit(uintptr_t at);
void tnx_v64_modesig_tick(void);
void tnx_v81_players_dump(uintptr_t players, uintptr_t array, int32_t count, int32_t capacity);
void tnx_v132_battle_alert(uintptr_t scene, uintptr_t scenePrev);
int tnx_v86_element_type(uintptr_t vt, uintptr_t *wordOut);
void tnx_v81_container_census(uintptr_t array, int32_t count, uintptr_t container);
int tnx_v82_container_header(uintptr_t object, uintptr_t *arrayOut, int32_t *countOut, int32_t *capOut, char *why, size_t whyLen);
void tnx_v82_hop_dump(uintptr_t client, uintptr_t inner);
int32_t tnx_v106_gid_at(uintptr_t element, uintptr_t off);
int32_t tnx_v106_gid(uintptr_t element, int32_t *offOut);
void tnx_v106_own_dump(uintptr_t element);
int tnx_v105_container_score(uintptr_t container);
int tnx_v105_own_verdict(uintptr_t element, char *why, size_t whyLen);
NSString *tnx_v132_status_text(void);
int tnx_v76_scan_ready(int battle);
void tnx_resolve_addresses(void);
int tnx_mode_score(uintptr_t mode);
BOOL tnx_is_mode_vtable(uintptr_t value, uintptr_t *rvaOut);
void tnx_locate_battle_mode(void);
BOOL tnx_candidate_is_stable(uintptr_t address, int32_t count);
int tnx_trail_beats_slot(int live, int nonEmpty, int32_t count, int slot);
int tnx_trail_qualifies(int slot);
int tnx_trail_ranked(int *out, int max);
void tnx_trail_rebest(void);
int tnx_v47_verify_setprediction(void);
void tnx_v47_read_map(uintptr_t mode);
void tnx_v127_gidless_scan(uintptr_t manager);
uintptr_t tnx_v135_list_gid_off(uintptr_t array, int32_t count);
void tnx_v140_proj_track(uintptr_t elem, uintptr_t classRva, int32_t gid, int32_t team);
void tnx_v92_team_dump(const tnx_v47_obj_t *objects, int usable);
void tnx_v93_class_dump(const tnx_v47_obj_t *objects, int usable);
int tnx_v90_slot_probe(void);
int tnx_v91_mode_real(uintptr_t mode, uintptr_t *vtOut, uintptr_t *chainOut, uintptr_t *innerOut);
void tnx_v102_own_probe(void);
int tnx_v102_inject_own(tnx_v47_obj_t *objects, int usable, int capacity);
int tnx_v183_own_latch(const tnx_v47_obj_t *objects, int usable, int *indexOut, const char **fromOut);
int tnx_v102_take_own(const tnx_v47_obj_t *objects, int usable, int *indexOut, const char **fromOut);
void tnx_v102_pos_trace(const tnx_v47_obj_t *objects, int usable);
void tnx_v102_write_test(const tnx_v47_obj_t *objects, int usable, int ownIndex);
void tnx_v102_audit_all(void);
int tnx_v112_read_flag(void);
int tnx_v144_vt_ok(uintptr_t obj, uintptr_t *vtOut);
int tnx_v144_cand_ok(uintptr_t cand, const char **why, uintptr_t *vtOut);
uintptr_t tnx_v144_hop(uintptr_t base, int *whyOut);
uintptr_t tnx_v127_own_obj(void);
void tnx_v127_setter(int32_t vx, int32_t vy);
void tnx_v127_elem_write(uintptr_t element, int32_t vx, int32_t vy);
int tnx_v115_mode(void);
int tnx_v115_inner(void);
int tnx_v115_gate(void);
uintptr_t tnx_v115_client(void);
int tnx_v134_own_by_min_gid(uintptr_t array, int32_t count, uintptr_t *elemOut, int32_t *gidOut);
int tnx_v134_own_from_list(const tnx_v47_obj_t *objects, int usable, int *indexOut, const char **fromOut);
void tnx_v127_statics(void);
void tnx_v127_readback(int plus);
void tnx_v103_state_note(int state);
int tnx_v91_own_scan(void);
int tnx_v91_resolve_own(const tnx_v47_obj_t *objects, int usable, int *indexOut, const char **fromOut);
void tnx_v90_gate_report(int slotHit);
int tnx_v140_proj_scan(uintptr_t manager, int32_t count);
uintptr_t tnx_v150_controller(void);
void tnx_v167_watch(int32_t ownX, int32_t ownY);
void tnx_v169_death_signals(uintptr_t ownElem, int32_t ownX, int32_t ownY);
void tnx_v167_alive(int32_t ownX, int32_t ownY);
void tnx_v163_map_dump(uintptr_t bounds);
void tnx_v179_census(void);
int tnx_v178_own(int32_t *xOut, int32_t *yOut);
float tnx_v231_step(void);
void tnx_v231_measure(void);
uintptr_t tnx_v173_hop(uintptr_t base, uintptr_t off);
int tnx_v173_snapshot(uintptr_t base, uint32_t *out);
void tnx_v173_slot_line(const char *name, const tnx_v173_win_t *w, int slot, uint32_t before, uint32_t after);
void tnx_v173_scan(void);
int tnx_v204_proj_mine(const tnx_v140_proj_t *p);
void tnx_v198_probe(uintptr_t target, const char *name);
void tnx_v198_settle(uintptr_t target, const char *name, float nx, float ny, uint64_t *took);
uint64_t tnx_v239_upd_delta(void);
uint64_t tnx_v239_rend_delta(void);
void tnx_v198_state(void);
uint64_t tnx_v68_word(uintptr_t address);
int tnx_v71_array_probe(uintptr_t array, int32_t count, char *why, size_t whyLen);
int tnx_v68_container_gate(uintptr_t manager, uintptr_t *containerOut, int32_t *countOut, int32_t *capOut, char *why, size_t whyLen);
void tnx_v68_multiteam_dump(uintptr_t owner, uint32_t teamMask, int teamCount);
const char *tnx_v57_header_reason(uintptr_t manager, int32_t *countOut, int32_t *capOut);
uintptr_t tnx_v57_coord_x_off(void);
uintptr_t tnx_v57_coord_y_off(void);

#endif
