#ifndef OFFSETS_H
#define OFFSETS_H

#include <stddef.h>
#include <stdint.h>
#include <mach-o/loader.h>

#define RVA_BATTLESCREEN__UPDATEAUTOSHOOT 0x807668ULL
#define RVA_COMBATHUD__SETMOVESTICKSTATE 0x5857ecULL
#define RVA_LOGICGAMEPLAYUTIL__GETCLOSESTANYCOLLISION 0xbd55c4ULL
#define RVA_MESSAGEMANAGER__RECEIVEMESSAGE 0x7bace8ULL
#define RVA_STAGE_ADDCHILD 0xc33690ULL

#define RVA_LOGICBATTLEMODECLIENT_SETCLIENTPREDICTIONMOVETO 0xac3f20ULL


#define RVA_BATTLEMODE_GETINSTANCE 0ULL
#define RVA_BATTLESCREEN__BATTLESCREEN 0ULL
#define RVA_BATTLESCREEN__TRYTOACTIVATESKILL 0ULL
#define RVA_BATTLESCREEN__UPDATEMOVEMENT 0x7a60f4ULL
#define RVA_BATTLESCREEN_ACTIVATESKILL 0ULL
#define RVA_BATTLESCREEN_FIREWRAPPERFN 0ULL
#define RVA_BATTLESCREEN_GETCLOSESTTARGETFORAUTOSHOOT 0ULL
#define RVA_CLIENTINPUTMESSAGE_SENDMOVEMENT 0ULL
#define RVA_COMBATHUD__SETSHOOTSTICKSTATE 0ULL
#define RVA_DISPLAYOBJECT__SETXY 0ULL
#define RVA_LOGICBATTLEMODECLIENT_GETOWNCHARACTER 0ULL
#define RVA_LOGICBATTLEMODECLIENT_GETOWNPLAYERTEAM 0ULL
#define RVA_LOGICBATTLEMODECLIENT_UPDATE 0ULL
#define RVA_LOGICCHARACTERDATA_GETCOLLISIONRADIUS 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETDATA 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETGLOBALID 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETX 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETY 0ULL
#define RVA_LOGICGAMEOBJECTMANAGERCLIENT__GETGAMEOBJECTS 0ULL
#define RVA_LOGICPROJECTILEDATA_GETRADIUS 0ULL
#define RVA_LOGICPROJECTILEDATA_GETSPEED 0ULL
#define RVA_LOGICTILEMAP__ISPLAYERLINEOFSIGHTCLEAR 0ULL
#define RVA_MOVIECLIP__GETTEXTFIELDBYNAME 0ULL
#define RVA_STRINGTABLE_GETMOVIECLIP 0ULL
#define RVA_TEXTFIELD_SETTEXT 0ULL

#define OFF_BATTLEMODE_OBJECTMANAGERPTR 0x28ULL
#define OFF_BATTLESCREEN_AUTOFIREX 0xe6cULL
#define OFF_BATTLESCREEN_AUTOFIREY 0xe70ULL
#define OFF_CHARDATA_SPEED 0x1c4ULL
#define OFF_GAMEOBJ_DEADFLAG 0xd0ULL
#define OFF_GAMEOBJ_TEAM 0x40ULL
#define OFF_OBJECTMANAGER_COUNT 0xcULL
#define OFF_OBJECTMANAGER_OBJECTSARRAY 0x0ULL
#define OFF_OBJECTMANAGER_PTRSTRIDE 0x8ULL

#define OFF_GAMEOBJ_X 0x30
#define OFF_GAMEOBJ_Y 0x34

#define RCL_TOUCH_GATE_OFF 0xf7fULL
#define RCL_TOUCH_ID_OFF 0xf84ULL
#define RCL_TOUCH_STATE_OFF 0xf80ULL
#define RCL_FLAG_OFF_2 0xf9cULL
#define RCL_JOYSTATE_OFF 0xed7ULL
#define RCL_GATE_OFF 0x70ULL
#define RCL_MODE_MANAGER_OFF 0x28ULL
#define RCL_MGR_ARRAY_OFF 0x0ULL
#define RCL_MGR_COUNT_OFF 0xcULL
#define RCL_MGR_CAP_OFF 0x8ULL
#define RCL_MODE_INPUTMGR_OFF 0x58ULL
#define RCL_DC_RVA_LO 0xf74000ULL
#define RCL_OBJ_GLOBALID_OFF 0x8ULL
#define RCL_GID_FALLBACK_OFF 0x50ULL
#define RCL_SETINPUT_RVA 0xac3a58ULL
#define RCL_MOVE_RVA 0xac3a58ULL
#define RCL_MOVE_FLAG_10 1
#define RCL_MOVE_X_OFF 0x10cULL
#define RCL_MOVE_Y_OFF 0x110ULL
#define RCL_MOVE_KEY_OFF 0x114ULL
#define RCL_MOVE_ARM_OFF 0xacULL
#define RCL_MOVE_ARM_ON 1
#define RCL_MOVE_COORD_LIMIT 200000
#define RCL_MOVE_SCAN_END 0x4f8ULL
#define RCL_MOVE_PROBE_TICK 900ULL
#define RCL_ALLOC_RVA 0x00d8da2cULL
#define RCL_MSGCTOR_RVA 0x00a95798ULL
#define RCL_CI_MGR_QUEUE_OFF 0x20ULL
#define RCL_TYPE_MOVE_ALT 0xaULL

#define RCL_TYPE_ATTACK RCL_TYPE_MOVE_ALT

#define RCL_AIM_HIT_DIST 400.0f

#define RCL_ADDINPUT_RVA 0x74675cULL
#define RCL_GETBATTLE_RVA 0x008c5130ULL
#define RCL_MGR_OFF 0x58ULL
#define RCL_QUEUE_OFF 0x20ULL
#define RCL_QUEUE_COUNT_OFF 0xcULL
#define RCL_TYPE_OFF 0x08ULL
#define RCL_X_OFF 0x0cULL
#define RCL_Y_OFF 0x10ULL
#define RCL_ALLOC_GOT_RVA 0x00f78180ULL
#define RCL_OWN_INNER_OFF 0x28ULL
#define RCL_BOX_PTR_OFF 0xf8ULL
#define RCL_MGR_SEQ_OFF 0x0cULL
#define RCL_OWN_ALIVE_OFF 0x140ULL
#define RCL_GATE_FLAG_OFF 0xacULL
#define RCL_CTRL_RAW_X_OFF 0xfa4ULL
#define RCL_CTRL_RAW_Y_OFF 0xfa8ULL
#define RCL_CTRL_DIRTY_OFF 0xfa0ULL
#define RCL_CTRL_MOVE_OFF 0xf78ULL
#define RCL_CTRL_ALIVE_OFF 0xf80ULL
#define RCL_CTRL_APPLIED_X_OFF 0xfccULL
#define RCL_CTRL_APPLIED_Y_OFF 0xfd0ULL

#define RVA_INPUT_COMMIT_10 0x79d594ULL
#define RVA_MGR_OBJ_LOOKUP_10 0xa267dcULL
#define RVA_JOY_FLIP_10 0x1123798ULL
#define RVA_WALK_MODE_10 0x536534ULL
#define RVA_DEAD_A_11 0xd5155cULL
#define RVA_DEAD_B_11 0xd51568ULL
#define RCL_DEAD_CONST 19.0908f
#define RCL_WALK_OBJ_OFF 0xa08ULL
#define RCL_JOY_CUR_X_OFF 0xa40ULL
#define RCL_JOY_CUR_Y_OFF 0xa44ULL
#define RCL_JOY_ORG_X_OFF 0xa48ULL
#define RCL_JOY_ORG_Y_OFF 0xa4cULL
#define RCL_CI_MGR_OBJLIST_OFF 0xa20ULL
#define RCL_WALK_PUSH_RAW 600.0f
#define RCL_WALK_PUSH_MIN_JUMP 50562

#define RCL_BATTLE_RVA 0x1123e58ULL
#define RCL_OFF_BATTLE_SCREEN 0x48ULL
#define RCL_JOY_PAIR_a 0x9b8ULL
#define RCL_JOY_PAIR_b 0x9d0ULL
#define RCL_JOY_PAIR_c 0xA20ULL
#define RCL_JOY_DRAG_OFF 0xF48ULL
#define RCL_JOY_DRAG2_OFF 0xF6EULL
#define RCL_JOY_TARGET_OFF 0x58ULL
#define RCL_CLIENT_OFF 0x28ULL
#define RCL_CLIENT_POS_X_OFF 0x80ULL
#define RCL_CLIENT_POS_Y_OFF 0x84ULL
#define RCL_OBJ_TEAM_OFF 0x40ULL
#define RCL_OBJ_OWNERINDEX_OFF 0x3cULL
#define RCL_OBJ_DEADFLAG_OFF 0xd0ULL
#define RCL_MODE_PREDICTX_OFF 0x1d4ULL
#define RCL_MODE_PREDICTY_OFF 0x1d8ULL
#define RCL_SLOT_OWNER_OFF 0x20ULL
#define RCL_CUR_X_OFF 0xa40ULL
#define RCL_ORG_Y_OFF 0xa4cULL
#define RCL_MARK_OFF 0xf74ULL
#define RCL_TILES_OFF 0x20ULL
#define RCL_TYPE_MOVE_OFF 0x56ULL
#define RCL_TYPE_PROJ_OFF 0x57ULL
#define RCL_BOUNDS_X_OFF 0xccULL
#define RCL_BOUNDS_Y_OFF 0xd0ULL
#define RCL_CTRL_MODE_OFF 0x918ULL
#define RCL_RVA_SETPREDICTION 0x00ac3f20ULL
#define RCL_OBJ_X_OFF 0x30ULL
#define RCL_OBJ_Y_OFF 0x34ULL
#define RCL_OBJ_ACTIVEFLAG_OFF 0x1e8ULL
#define RCL_MODE_TILEMAP_OFF 0xf8ULL
#define RCL_TILEMAP_WIDTH_OFF 0xc4ULL
#define RCL_TILEMAP_HEIGHT_OFF 0xc8ULL
#define RCL_TYPE_SLOT_OFF 0x28ULL
#define RCL_ELEM_BACK_OFF 0x18ULL
#define RCL_TEAM_OFF 0x4cULL
#define RCL_DEAD_OFF 0xd4ULL
#define RCL_ELEM_ID_OFF_2 0x48ULL
#define RCL_ELEM_TEAM_OFF_2 0x4cULL
#define RCL_ARRAY_OFF 0x0ULL
#define RCL_COUNT_OFF_4 0xdcULL

#define RCL_COUNT_OFF 0xcULL
#define RCL_OWNIDX_OFF_2 0xe0ULL
#define RCL_OWNTEAM_OFF_2 0xe4ULL
#define RCL_OWNIDX_OFF 0xe0ULL
#define RCL_OWNTEAM_OFF 0xe4ULL
#define RCL_MODEPAIRSET_RVA RCL_SETINPUT_RVA
#define RCL_STATE_RVA 0x1123e58ULL
#define RCL_STATE_ENUM_OFF 0x50ULL
#define RCL_SCENE_OFF 0x48ULL
#define RCL_CLIENT_HOP_OFF 0x28ULL
#define RCL_ELEM_DEF_OFF 0x10ULL
#define RCL_OFF 0x70ULL
#define RCL_NP_PTR_OFF 0x38ULL

#define RCL_MAP_BASE_OFF RCL_MODE_MANAGER_OFF
#define RCL_MAP_PTR_OFF RCL_MODE_TILEMAP_OFF
#define RCL_MAP_WIDTH_OFF RCL_TILEMAP_WIDTH_OFF
#define RCL_MAP_HEIGHT_OFF RCL_TILEMAP_HEIGHT_OFF
#define RCL_MAP_COUNT_OFF RCL_COUNT_OFF_4
#define RCL_MAP_TILES_OFF RCL_TILES_OFF
#define RCL_TILE_PTR_STRIDE OFF_OBJECTMANAGER_PTRSTRIDE
#define RCL_TILE_TYPE_MOVE_OFF RCL_TYPE_MOVE_OFF
#define RCL_TILE_TYPE_PROJ_OFF RCL_TYPE_PROJ_OFF

#define RCL_STATE_BATTLE 5

#define RCL_CI_TYPE_TABLE_RVA 0x00e1e058ULL
#define RCL_CI_TABLE_TYPES 0x17ULL
#define RCL_CI_MAX_TABLE_TYPE 0x16UL
#define RCL_CI_FALLBACK_TYPE_CONST 0xdeadbeefUL
#define RCL_CI_HASH_MASK_SIZE 0x10UL
#define RCL_CI_HASH_PAD_INNER 0x36
#define RCL_CI_HASH_PAD_OUTER 0x5c
#define RCL_CI_HASH_INNER_MASK_RVA 0x00e1bbd0ULL
#define RCL_CI_HASH_OUTER_MASK_RVA 0x00e1bbf0ULL
#define RCL_BM_HASH_ENABLED_OFF 0x70ULL
#define RCL_BM_HASH_KEY_OFF 0x60ULL
#define RCL_CI_TOKEN_OFF 0x34UL
#define RCL_CI_TOKEN_READ_OFF 0x4UL
#define RCL_CI_TOKEN_READ_LEN 0x10UL
#define RCL_CI_TOKEN_MSG_LEN 0x14UL
#define RCL_CI_TOKEN_MASK 0x7fUL
#define RCL_CI_TOKEN_MIN 1UL
#define RCL_CTRL_LATCH_OFF 0xf9cULL
#define RCL_CTRL_LATCH_VAL 1
#define RCL_CTRL_DIRTY_VAL 0


#define RCL_IMAGE_TEXT_WINDOW 0x4000ULL
#define RCL_CLASS_PROJ_RVA 0x000ff57b0ULL
#define RCL_PROJ_CLASS_ONLY 1



























































#define RCL_WRITE_GUARD 1
#define RCL_ESCAPE 1
#define RCL_MODE_TUNE 1
#define RCL_HORIZON 1.0f
#define RCL_SEL_MAX 8
#define RCL_MGR_CAP_MAX 4096
#define RCL_MANAGER_MAX_OBJECTS 96
#define RCL_DC_RVA_SIZE 0xd4000ULL
#define RCL_OBJ_HIT_DUMP_MAX 64
#define RCL_QUEUE_GUARD 0
#define RCL_OBJ_TEAM_MAX 7
#define RCL_JOURNAL 24
#define RCL_TILE_SIZE 300.0f
#define RCL_GRID_MAX 128
#define RCL_SEG_MAX 32
#define RCL_BS_MODE 0x8ac
#define RCL_PLAYER_GID 1000000
#define RCL_SHOT_GID 2000000
#define RCL_STEP_b 60.0f
#define RCL_MATE_MAX 8
#define RCL_PLAYER_MAX 12
#define RCL_CAND 3
#define RCL_REACH 600.0f
#define RCL_PROJ_MAX 16
#define RCL_DIFF_BYTES 0x100
#define RCL_COORD_ABS_MAX 1000000
#define RCL_MAP_MIN 4
#define RCL_OBJECT_MAX 64
#define RCL_IMAGE_SPAN 0x1164000ULL
#define RCL_OBJ_SLOTS 3
#define RCL_HOPS 2
#define RCL_TEAM_MAX_2 15
#define RCL_PLAYER_GID_MAX 2000000
#define RCL_VTABLE_SEGMENT "__DATA_CONST"
#define RCL_VTABLE_SEGMENT_ALT "__DATA"
#define RCL_SLOT_COUNT 34
#define RCL_HEAP_REGION_MAX 512
#define RCL_HEAP_REGION_MAX_SIZE 0x100000000ULL
#define RCL_TRAIL_MAX 8
#define RCL_DIR_COUNT 64
#define RCL_ADV_BUCKETS 8
#define RCL_GEOM 1
#define RCL_GEOM_LOGS 6
#define RCL_RADIUS_MIN 0.0f
#define RCL_RADIUS_MAX 600.0f
#define RCL_RADIUS_MARGIN 8.0f
#define RCL_CAL_OFF_LO 0x20
#define RCL_CAL_OFF_HI 0x120
#define RCL_CAL_STEP 4
#define RCL_CAL_TOL 0.06f
#define RCL_CONTACT_LOGS 8
#define RCL_SNAP 1
#define RCL_SNAP_MAG 600.0f
#define RCL_SNAP_LOGS 8
#define RCL_SIDE_FLIP 1
#define RCL_SIDE_STALE 45
#define RCL_CAL_TICKS 6
#define RCL_CAL_MISS 40
#define RCL_WALL_LOGS 8
#define RCL_TEAM_LOGS 6
#ifndef RCL_DODGE_PROJ_ONLY
#define RCL_DODGE_PROJ_ONLY 1

#ifndef RCL_PROJ_ANGLE_OFF
#define RCL_PROJ_ANGLE_OFF 0xb8

#ifndef RCL_JS_ENEMY_W
#define RCL_JS_ENEMY_W 300.0f
#endif

#endif

#ifndef RCL_JS_SPEED_FALLBACK
#define RCL_JS_SPEED_FALLBACK 1200.0f
#endif

#ifndef RCL_JS_RADIUS_FALLBACK
#define RCL_JS_RADIUS_FALLBACK 8.0f
#endif

#endif
#ifndef RCL_HIT_MARGIN
#define RCL_HIT_MARGIN 60.0f
#endif
#ifndef RCL_DODGE_CLEAR_R
#define RCL_DODGE_CLEAR_R 96.0f
#endif
#ifndef RCL_RAGE_FORCE
#define RCL_RAGE_FORCE 0
#endif
#ifndef RCL_LOOKAHEAD_MAX
#define RCL_LOOKAHEAD_MAX 400.0f
#endif
#ifndef RCL_ENGAGE_NEAR
#define RCL_ENGAGE_NEAR 24.0f
#endif
#ifndef RCL_JS_DODGE
#define RCL_JS_DODGE 1
#endif
#ifndef RCL_DIR_COUNT
#define RCL_DIR_COUNT 48
#endif
#ifndef RCL_HORIZON_S
#define RCL_HORIZON_S 1.0f
#endif
#ifndef RCL_DATA_MOMENTUM
#define RCL_DATA_MOMENTUM 300.0f
#endif
#ifndef RCL_WALL_PENALTY
#define RCL_WALL_PENALTY 9000.0f
#endif
#ifndef RCL_DATA_SPEED
#define RCL_DATA_SPEED 750.0f
#endif
#ifndef RCL_DATA_OWN_R
#define RCL_DATA_OWN_R 120.0f
#endif
#ifndef RCL_DATA_PROJ_R
#define RCL_DATA_PROJ_R 150.0f
#endif
#ifndef RCL_DATA_HOLD
#define RCL_DATA_HOLD 10
#endif
#ifndef RCL_DATA_BAND
#define RCL_DATA_BAND 300.0f
#endif
#ifndef RCL_DATA_CRIT_EVERY
#define RCL_DATA_CRIT_EVERY 4
#endif
#ifndef RCL_JS_CLEAR_STEPS
#define RCL_JS_CLEAR_STEPS 4
#endif
#ifndef RCL_PROJ_LIFE_MS
#define RCL_PROJ_LIFE_MS 1200.0f
#endif
#ifndef RCL_OVERSHOOT
#define RCL_OVERSHOOT 220.0f
#endif
#ifndef RCL_FREEST_RADII
#define RCL_FREEST_RADII 3
#endif
#ifndef RCL_FREEST_LOGS
#define RCL_FREEST_LOGS 6
#endif
#ifndef RCL_BODY_GAIN
#define RCL_BODY_GAIN 0.0f
#endif
#ifndef RCL_ETA_PENALTY
#define RCL_ETA_PENALTY 100000.0f
#endif
#ifndef RCL_JS_NOPREDICT
#define RCL_JS_NOPREDICT 0
#endif
#ifndef RCL_GEOM
#define RCL_GEOM 1
#endif
#ifndef RCL_GEOM_LOGS
#define RCL_GEOM_LOGS 6
#endif
#ifndef RCL_RADIUS_MIN
#define RCL_RADIUS_MIN 0.0f
#endif
#ifndef RCL_RADIUS_MAX
#define RCL_RADIUS_MAX 600.0f
#endif
#ifndef RCL_RADIUS_MARGIN
#define RCL_RADIUS_MARGIN 8.0f
#endif
#ifndef RCL_CAL_OFF_LO
#define RCL_CAL_OFF_LO 0x20
#endif
#ifndef RCL_CAL_OFF_HI
#define RCL_CAL_OFF_HI 0x120
#endif
#ifndef RCL_CAL_STEP
#define RCL_CAL_STEP 4
#endif
#ifndef RCL_CAL_TOL
#define RCL_CAL_TOL 0.06f
#endif
#ifndef RCL_CONTACT_LOGS
#define RCL_CONTACT_LOGS 8
#endif
#ifndef RCL_SNAP
#define RCL_SNAP 1
#endif
#ifndef RCL_SNAP_DELTA
#define RCL_SNAP_DELTA 0
#endif
#ifndef RCL_SNAP_HARD_OFF
#define RCL_SNAP_HARD_OFF 1
#endif
#ifndef RCL_SNAP_MAG
#define RCL_SNAP_MAG 600.0f
#endif
#ifndef RCL_SNAP_LOGS
#define RCL_SNAP_LOGS 8
#endif
#ifndef RCL_SIDE_FLIP
#define RCL_SIDE_FLIP 1
#endif
#ifndef RCL_SIDE_STALE
#define RCL_SIDE_STALE 45
#endif
#ifndef RCL_CAL_TICKS
#define RCL_CAL_TICKS 6
#endif
#ifndef RCL_CAL_MISS
#define RCL_CAL_MISS 40
#endif
#ifndef RCL_WALL_LOGS
#define RCL_WALL_LOGS 8
#endif
#ifndef RCL_TEAM_LOGS
#define RCL_TEAM_LOGS 6
#endif
#define RCL_CONTACT_LOGS 8
#define RCL_DATA_OWN_R 120.0f
#define RCL_GEOM 1
#define RCL_RADIUS_MAX 600.0f
#define RCL_SIDE_FLIP 1
#define RCL_SIDE_STALE 45
#ifndef RCL_DODGE_PROJ_ONLY
#define RCL_DODGE_PROJ_ONLY 1
#endif
#ifndef RCL_PROJ_ACTIVE_BYPASS
#define RCL_PROJ_ACTIVE_BYPASS 1
#endif
#ifndef RCL_JS_STICK
#define RCL_JS_STICK 1
#endif
#ifndef RCL_JS_HOLD
#define RCL_JS_HOLD 2
#endif
#ifndef RCL_STICK_RAW_WRITE
#define RCL_STICK_RAW_WRITE 0
#define RCL_PRED_SPAN 0x118
#endif
#ifndef RCL_LOG_PLANS
#define RCL_LOG_PLANS 0
#endif

#endif
