#ifndef TITANOX_CORE_HOOKS_H
#define TITANOX_CORE_HOOKS_H

#include "core/types.h"

extern uintptr_t g_v101_own_ptr;
extern int g_v101_own_index;
extern int g_v101_own_team;
extern int g_v101_own_idhit;
extern uintptr_t g_v101_setpred;
extern int g_v101_own_logs;
extern int g_v101_wide_runs;
extern int g_v101_miss_logs;
extern const char *g_v101_own_from;
extern int g_v77_live_objs;
extern int g_v77_live_teams;
extern int g_v77_fb_on;
extern int g_v77_fb_logged;
extern int g_v77_bar_logged;
extern unsigned g_v77_vt_text_rejects;
extern unsigned long long g_v79_obj_prev;
extern uintptr_t g_v80_site;
extern int g_v80_state;
extern int g_v80_scan_armed;
extern volatile uint32_t g_v142_seq;
extern uintptr_t g_v142_pub_object;
extern uintptr_t g_v142_pub_array;
extern int32_t g_v142_pub_count;
extern int32_t g_v142_pub_cap;
extern int g_v142_pub_logs;
extern uintptr_t g_v142_tick_object;
extern uintptr_t g_v142_tick_array;
extern int32_t g_v142_tick_count;
extern uint64_t g_v142_tick_stamp;
extern uint64_t g_v142_tick_logs;
extern int g_v142_score_logs;
extern uint64_t g_v142_walk_aborts;
extern uint64_t g_v99_inputmgr_writes;
extern uint64_t g_v99_inputmgr_last_tick;
extern uint64_t g_v78_idle_start;
extern int g_v78_idle_on;
extern int g_v78_idle_logged;
extern int g_v78_idle_skips;
extern int g_v129_ascii_logs;
extern const int tnx_v79_object_slots[TNX_V79_OBJ_SLOTS];
extern int g_v142_walk_aborted;
extern int g_v142_walk_abort_i;
extern uintptr_t g_v142_walk_arr;
extern int32_t g_v142_walk_n;
extern const char *g_v145_own_from;
extern int g_v145_pub_logs;
extern int g_v145_stale_logs;
extern int g_v145_actuate_logs;
extern uintptr_t g_v129_own_slot;
extern int32_t g_v129_own_slot_idx;
extern int32_t g_v129_own_slot_gid;
extern int g_v129_own_slot_ok;
extern int g_v129_own_slot_logs;
extern int g_v117_gate2_seen;
extern int g_v117_gate3_seen;
extern int32_t g_v118_src30_prev_x;
extern int32_t g_v118_src30_prev_y;
extern int32_t g_v118_src38_prev_x;
extern int32_t g_v118_src38_prev_y;
extern int g_v118_src30_have;
extern int g_v118_src38_have;
extern uint64_t g_v118_src30_moves;
extern uint64_t g_v118_src38_moves;
extern int g_v118_w_eq_x;
extern int g_v118_w_eq_y;
extern int g_v148_probe_logs;

void tnx_v142_publish(uintptr_t object, uintptr_t array, int32_t count, int32_t cap, const char *why);
int tnx_v142_snapshot(uintptr_t *objectOut, uintptr_t *arrayOut, int32_t *countOut);
void tnx_v142_tick_begin(const char *phase);
void tnx_slot_install_one(int index);
void tnx_slot_hooks_install(void);
const char *tnx_prologue_rule(uintptr_t address);
BOOL tnx_looks_like_start(uintptr_t address);
size_t tnx_start_index(uintptr_t address, BOOL *exact);
BOOL tnx_start_word(uint32_t word);
BOOL tnx_start_boundary(const uint8_t *bytes, size_t offset);
void tnx_load_function_starts(void);
void *tnx_sc_string(const char *utf8);
const char *tnx_skip_compound(const char *p);
int tnx_objc_arg_types(const char *types, char *out, size_t capacity);
BOOL tnx_class_owns_method(Class cls, SEL sel);
Class tnx_owner_class(Class cls, SEL sel);
tnx_objc_hook_t *tnx_objc_find(id self, SEL _cmd);
BOOL tnx_objc_targets(id self, tnx_objc_hook_t *hook);
void tnx_run_autododge(int from_update);
void tnx_run_autoaim(void);
void tnx_overlay_attach(NSString *text);
void tnx_overlay_update(void);
int tnx_v77_vtable_is_data(uintptr_t vtable);
int tnx_v80_state_tick(void);
uint64_t tnx_v78_hook_dispatches(void);
uint64_t tnx_v79_object_dispatches(void);
int tnx_v78_scan_allowed(uint64_t fired, uint64_t total);
int tnx_v77_battle_gate(int v63);
void tnx_alert_battle_check(void);
void tnx_render_watermark(void);
void tnx_start_timer(void);
void tnx_run_workload(void);
void tnx_objc_rep0(id self, SEL _cmd);
void tnx_objc_rep1(id self, SEL _cmd, id a1);
void tnx_objc_rep1b(id self, SEL _cmd, BOOL a1);
void tnx_objc_rep2(id self, SEL _cmd, id a1, id a2);
int tnx_objc_arm(const char *clsName, const char *selName);
void tnx_v99_inputmgr_probe(void);
int tnx_v101_word(uintptr_t address, uint32_t *out);
int tnx_v101_is_term(uint32_t w);
int tnx_v101_is_prologue(uint32_t w);
uintptr_t tnx_v101_entry(uintptr_t rva);
void tnx_v101_own_index_probe(void);
void tnx_v101_actuator(uintptr_t mode, int x, int y);
void tnx_v145_publish_own(uintptr_t elem, const char *from);
uintptr_t tnx_v129_battle_global(void);
int tnx_v129_container_has(uintptr_t container, uintptr_t own);
int tnx_v129_own_from_slot(uintptr_t *objectOut, int32_t *gidOut);
void tnx_v129_chain(void);
int tnx_v117_pair(uintptr_t obj, int32_t *x, int32_t *y);
int tnx_v117_src(uintptr_t off, int32_t *x, int32_t *y, int *flag);
int tnx_v118_weq(int32_t a, int32_t b, int32_t out, int32_t d);
uintptr_t tnx_v118_mode_ptr(uintptr_t off);
uintptr_t tnx_v148_cls(uintptr_t obj);
void tnx_v148_receiver_line(const char *name, uintptr_t holder);
void tnx_v148_receiver_probe(void);
void tnx_slot_pump(void);
void setup(void);

#endif
