#ifndef TITANOX_CORE_HOOKS_H
#define TITANOX_CORE_HOOKS_H

#include "core/types.h"

extern uintptr_t g_own_ptr;
extern int g_own_index;
extern int g_own_team;
extern int g_own_idhit;
extern uintptr_t g_setpred;
extern int g_own_logs;
extern int g_wide_runs;
extern int g_miss_logs;
extern const char *g_own_from;
extern int g_live_objs;
extern int g_live_teams;
extern int g_fb_on;
extern int g_fb_logged;
extern int g_bar_logged;
extern unsigned g_vt_text_rejects;
extern unsigned long long g_obj_prev;
extern uintptr_t g_site;
extern int g_state_2;
extern int g_scan_armed;
extern volatile uint32_t g_seq;
extern uintptr_t g_pub_object;
extern uintptr_t g_pub_array;
extern int32_t g_pub_count;
extern int32_t g_pub_cap;
extern int g_pub_logs;
extern uintptr_t g_tick_object;
extern uintptr_t g_tick_array;
extern int32_t g_tick_count;
extern uint64_t g_tick_stamp;
extern uint64_t g_tick_logs;
extern int g_score_logs_2;
extern uint64_t g_walk_aborts;
extern uint64_t g_idle_start;
extern int g_idle_on;
extern int g_idle_logged;
extern int g_idle_skips;
extern int g_ascii_logs;
extern const int tnx_object_slots[TNX_OBJ_SLOTS];
extern int g_walk_aborted;
extern int g_walk_abort_i;
extern uintptr_t g_walk_arr;
extern int32_t g_walk_n;
extern const char *g_own_from_3;
extern int g_pub_logs_2;
extern int g_stale_logs;
extern int g_actuate_logs;
extern uintptr_t g_own_slot;
extern int32_t g_own_slot_idx;
extern int32_t g_own_slot_gid;
extern int g_own_slot_ok;
extern int g_own_slot_logs;
extern int g_gate2_seen;
extern int g_gate3_seen;
extern int32_t g_src30_prev_x;
extern int32_t g_src30_prev_y;
extern int32_t g_src38_prev_x;
extern int32_t g_src38_prev_y;
extern int g_src30_have;
extern int g_src38_have;
extern uint64_t g_src30_moves;
extern uint64_t g_src38_moves;
extern int g_w_eq_x;
extern int g_w_eq_y;
extern int g_probe_logs;

void tnx_publish(uintptr_t object, uintptr_t array, int32_t count, int32_t cap, const char *why);
int tnx_snapshot(uintptr_t *objectOut, uintptr_t *arrayOut, int32_t *countOut);
void tnx_tick_begin(const char *phase);
void tnx_slot_install_one(int index);
void tnx_slot_hooks_install(void);
const char *tnx_prologue_rule(uintptr_t address);
BOOL tnx_looks_like_start(uintptr_t address);
size_t tnx_start_index(uintptr_t address, BOOL *exact);
BOOL tnx_start_word(uint32_t word);
BOOL tnx_start_boundary(const uint8_t *bytes, size_t offset);
void tnx_load_function_starts(void);
void *tnx_sc_string(const char *utf8);
const char *tnx_skip_compound(const char *p);
int tnx_objc_arg_types(const char *types, char *out, size_t capacity);
BOOL tnx_class_owns_method(Class cls, SEL sel);
Class tnx_owner_class(Class cls, SEL sel);
tnx_objc_hook_t *tnx_objc_find(id self, SEL _cmd);
BOOL tnx_objc_targets(id self, tnx_objc_hook_t *hook);
void tnx_run_autododge(int from_update);
void tnx_run_autoaim(void);
void tnx_overlay_attach(NSString *text);
void tnx_overlay_update(void);
int tnx_vtable_is_data(uintptr_t vtable);
int tnx_state_tick(void);
uint64_t tnx_hook_dispatches(void);
uint64_t tnx_object_dispatches(void);
int tnx_scan_allowed(uint64_t fired, uint64_t total);
int tnx_battle_gate_2(int v63);
void tnx_alert_battle_check(void);
void tnx_render_watermark(void);
void tnx_start_timer(void);
void tnx_run_workload(void);
void tnx_objc_rep0(id self, SEL _cmd);
void tnx_objc_rep1(id self, SEL _cmd, id a1);
void tnx_objc_rep1b(id self, SEL _cmd, BOOL a1);
void tnx_objc_rep2(id self, SEL _cmd, id a1, id a2);
int tnx_objc_arm(const char *clsName, const char *selName);
int tnx_word(uintptr_t address, uint32_t *out);
int tnx_is_term(uint32_t w);
int tnx_is_prologue(uint32_t w);
uintptr_t tnx_entry(uintptr_t rva);
void tnx_own_index_probe(void);
void tnx_publish_own(uintptr_t elem, const char *from);
uintptr_t tnx_battle_global(void);
int tnx_container_has(uintptr_t container, uintptr_t own);
int tnx_own_from_slot(uintptr_t *objectOut, int32_t *gidOut);
void tnx_chain(void);
int tnx_pair(uintptr_t obj, int32_t *x, int32_t *y);
int tnx_src(uintptr_t off, int32_t *x, int32_t *y, int *flag);
int tnx_weq(int32_t a, int32_t b, int32_t out, int32_t d);
uintptr_t tnx_mode_ptr(uintptr_t off);
uintptr_t tnx_cls(uintptr_t obj);
void tnx_receiver_line(const char *name, uintptr_t holder);
void tnx_receiver_probe(void);
void tnx_slot_pump(void);
void setup(void);

#endif
