#ifndef RECOIL_CORE_MEMORY_H
#define RECOIL_CORE_MEMORY_H

#include "core/types.h"

extern uintptr_t rcl_base;


extern const char *rcl_image_names[4];
extern const rcl_rva_entry_t rcl_rvas[32];
extern uintptr_t *rcl_starts;
extern size_t rcl_starts_count;
extern BOOL rcl_setup_done;
extern BOOL rcl_aim_rejected;
extern __thread BOOL rcl_inside_hook;
extern uint64_t rcl_dodge_calls;
extern int rcl_dump_np;
extern BOOL rcl_mode_strong;
extern uintptr_t rcl_players_object;
extern int rcl_manager_count;
extern uintptr_t rcl_objvote_best_owner;
extern int rcl_objvote_best_teamcount;
extern rcl_objhit_t rcl_objhits[RCL_OBJ_HIT_DUMP_MAX];
extern int rcl_objhit_count;
extern int rcl_objvote_max_votes;
extern int rcl_heap_region_capped;
extern uintptr_t rcl_img_span_lo;
extern uintptr_t rcl_img_span_hi;
extern int rcl_trail_best;
extern int rcl_votescan_attempts;
extern double rcl_votescan_last;
extern BOOL rcl_snapshot_first;
extern BOOL rcl_snapshot_second;
extern double rcl_snapshot_start;
extern rcl_objc_hook_t rcl_objc_hooks[OBJC_HOOK_MAX];
extern uintptr_t rcl_addr_getinstance;
extern uintptr_t rcl_addr_getownchar;
extern uintptr_t rcl_addr_getteam;
extern uintptr_t rcl_addr_getx;
extern uintptr_t rcl_addr_gety;
extern uintptr_t rcl_addr_setprediction;
extern uintptr_t rcl_addr_battlescreen;
extern volatile int rcl_at;
extern uint64_t rcl_stale;
extern int rcl_no_source_passes;
extern int rcl_route_logged;
extern int rcl_sig_ticks;
extern uintptr_t rcl_sig_last;
extern uintptr_t rcl_players_array;
extern int rcl_players_count;
extern uint64_t rcl_walk_tick;
extern int rcl_walk_count;
extern int rcl_coord_fixed_logged;
extern uint64_t rcl_time;
extern uint64_t rcl_slow;
extern uint64_t rcl_drain;
extern uint64_t rcl_q_max;
extern int32_t rcl_gid_lo;
extern int32_t rcl_gid_hi;
extern uintptr_t rcl_owner;
extern int rcl_wired;
extern dispatch_source_t rcl_scan_timer;
extern rcl_region_t rcl_heap_regions[RCL_HEAP_REGION_MAX];
extern int rcl_heap_region_count;
extern uintptr_t rcl_heap_window_low;
extern uintptr_t rcl_heap_window_high;
extern const uintptr_t rcl_mode_vtables[36];
extern rcl_trail_t rcl_trail[RCL_TRAIL_MAX];
extern int rcl_trail_count;
extern int rcl_gate_last;
extern int rcl_dodge_probe_usable;
extern uintptr_t rcl_last_own;
extern int32_t rcl_last_tx;
extern int32_t rcl_last_ty;
extern int rcl_issued;
extern uintptr_t rcl_own_elem_2;
extern int rcl_human_2;
extern uint64_t rcl_queue_skips;
extern int32_t rcl_tx_b;
extern int32_t rcl_ty_b;
extern uint64_t rcl_hold;

uintptr_t rcl_strip_imp(IMP imp);
BOOL rcl_query_region(uintptr_t address, vm_prot_t *protection, vm_prot_t *maxProtection, mach_vm_size_t *regionSize, uintptr_t *regionStart);
BOOL rcl_addr_writable(uintptr_t address, size_t length);
BOOL rcl_read_bytes(uintptr_t address, void *out, size_t length);
BOOL rcl_pointer_plausible(uintptr_t value);
BOOL rcl_read_byte(uintptr_t address, uint8_t *out);
BOOL rcl_read_int(uintptr_t address, int32_t *out);
BOOL rcl_read_float(uintptr_t address, float *out);
BOOL rcl_writable(uintptr_t address, size_t length);
void rcl_note(uintptr_t address, const void *src, size_t length, int denied);
BOOL rcl_write_bytes(uintptr_t address, const void *src, size_t length);
BOOL rcl_write_float(uintptr_t address, float value);
BOOL rcl_read_ptr(uintptr_t address, void **out);
void *rcl_read_global_ptr(uintptr_t rva);
uintptr_t rcl_callable(uintptr_t rva);
BOOL rcl_copy(uintptr_t source, void *destination, size_t length);
BOOL rcl_text_section(uintptr_t *address, uint64_t *size);
BOOL rcl_valid_header(uintptr_t base);
BOOL find_game_image(uintptr_t *out_base);
BOOL rcl_segment_range(const char *name, uintptr_t *lo, uintptr_t *hi);
void rcl_image_span_refresh(void);
const char *rcl_image_segment_name(uintptr_t value);
void rcl_heap_regions_refresh(void);
BOOL rcl_heap_contains(uintptr_t value);
BOOL rcl_vtable_shaped(uintptr_t value);
BOOL rcl_heap_resident(uintptr_t value);
BOOL rcl_gameobject_shape(uintptr_t object);
BOOL rcl_instance_shaped(uintptr_t object);
BOOL rcl_manager_shape(uintptr_t manager);
BOOL rcl_vtable_in_image(uintptr_t vtable);
uintptr_t rcl_strip_ptr(uintptr_t value);
void poll_for_game(int tick);

#endif
