#ifndef TITANOX_CORE_MEMORY_H
#define TITANOX_CORE_MEMORY_H

#include "core/types.h"

struct tnx_t_g_slot_specs {
    const char *tag;
    const char *shortTag;
    uintptr_t rva;
    uintptr_t slotRva;
    tnx_slot_fn_t replacement;
    int control;
};

extern const char *g_image_names[4];
extern const tnx_rva_entry_t g_rvas[32];
extern uintptr_t g_base;
extern uintptr_t *g_starts;
extern size_t g_starts_count;
extern FILE *g_log;
extern long g_log_written;
extern BOOL g_setup_done;
extern BOOL g_wm_failed;
extern BOOL g_wm_ready;
extern BOOL g_aim_rejected;
extern __thread BOOL g_inside_hook;
extern int g_v123_defer_logs;
extern uint64_t g_v138_dodge_calls;
extern uint64_t g_v138_render_calls;
extern int g_v138_dump_np;
extern uintptr_t g_v138_prev_scene;
extern const uintptr_t g_mode_vtables_verified[3];
extern uintptr_t g_scene_object;
extern BOOL g_mode_strong;
extern int g_mode_best_objects;
extern int g_mode_last_types;
extern int g_mode_verified_hits;
extern uintptr_t g_players_object;
extern int g_manager_count;
extern int g_manager_probes;
extern int g_manager_probes_total;
extern int g_manager_skipped;
extern int g_manager_last_live;
extern int g_manager_last_nonempty;
extern int g_manager_last_capacity;
extern int g_manager_saw_cap;
extern int g_manager_loose_count;
extern int g_chain_checks;
extern int g_chain_probes;
extern int g_chain_skipped;
extern int g_chain_best_own;
extern int g_chain_best_gid;
extern int g_seen_stable;
extern int g_owner_vote_count;
extern unsigned long long g_objvote_hits;
extern unsigned long long g_objvote_skipped;
extern int g_objvote_dead_seen;
extern uintptr_t g_objvote_best_owner;
extern int g_objvote_best_gids;
extern int g_objvote_confirm;
extern BOOL g_objvote_owner_ok;
extern unsigned long long g_objvote_owner_img;
extern unsigned long long g_objvote_obj_img;
extern int g_objvote_best_teamcount;
extern int g_objvote_best_gids_full;
extern tnx_objhit_t g_objhits[TNX_OBJ_HIT_DUMP_MAX];
extern int g_objhit_count;
extern unsigned long long g_objvote_owner_reg;
extern unsigned long long g_objvote_owner_above_win;
extern int g_objvote_max_votes;
extern unsigned long long g_objvote_shaped;
extern tnx_vtcensus_t g_vtcensus[TNX_VTCENSUS_MAX];
extern int g_vtcensus_used;
extern unsigned long long g_vtcensus_total;
extern int g_heap_big_skip;
extern int g_heap_region_capped;
extern uintptr_t g_img_span_lo;
extern uintptr_t g_img_span_hi;
extern int g_img_span_ok;
extern int g_trail_best;
extern int g_manager_cap_rejects;
extern int g_manager_best_count;
extern int g_manager_best_live;
extern int g_heap_passes;
extern unsigned long long g_heap_covered;
extern uintptr_t g_mode_source;
extern int g_votescan_attempts;
extern double g_votescan_last;
extern BOOL g_snapshot_first;
extern BOOL g_snapshot_second;
extern double g_snapshot_start;
extern tnx_objc_hook_t g_objc_hooks[OBJC_HOOK_MAX];
extern int g_objc_armed;
extern uintptr_t g_addr_getinstance;
extern uintptr_t g_addr_getownchar;
extern uintptr_t g_addr_getteam;
extern uintptr_t g_addr_getx;
extern uintptr_t g_addr_gety;
extern uintptr_t g_addr_setprediction;
extern uintptr_t g_addr_sendmovement;
extern uintptr_t g_addr_getclip;
extern uintptr_t g_addr_gettf;
extern uintptr_t g_addr_settext;
extern uintptr_t g_addr_setxy;
extern uintptr_t g_addr_addchild;
extern uintptr_t g_addr_battlescreen;
extern void *g_label_clip;
extern void *g_label_tf;
extern void *g_label_sc;
extern char g_label_text[64];
extern int g_label_updates;
extern FILE *g_battle_log;
extern BOOL g_battle_capture;
extern BOOL g_battle_header;
extern uintptr_t g_v245_addr[TNX_V245_JOURNAL];
extern uint32_t g_v245_value[TNX_V245_JOURNAL];
extern uint64_t g_v245_tick[TNX_V245_JOURNAL];
extern const char *g_v245_phase[TNX_V245_JOURNAL];
extern uint8_t g_v245_size[TNX_V245_JOURNAL];
extern uint8_t g_v245_denied[TNX_V245_JOURNAL];
extern volatile int g_v245_at;
extern volatile uint64_t g_v245_writes;
extern uint64_t g_v245_stale;
extern tnx_slot_fn_t g_slot_orig[TNX_SLOT_COUNT];
extern uintptr_t g_slot_object[TNX_SLOT_COUNT];
extern uintptr_t g_slot_arg1[TNX_SLOT_COUNT];
extern uint64_t g_slot_hits[TNX_SLOT_COUNT];
extern uint64_t g_slot_hits_total;
extern int g_slot_installed[TNX_SLOT_COUNT];
extern int g_slot_slots[TNX_SLOT_COUNT];
extern int g_v55_chain_rej[20];
extern int g_v55_chain_probes_pass;
extern int g_v55_layout_logs;
extern int g_v54_no_source_passes;
extern int g_v54_route_logged;
extern uint32_t g_slot_reported_mask;
extern uint64_t g_slot_first_tick[TNX_SLOT_COUNT];
extern uintptr_t g_slot_adopted;
extern int g_ag_adopted;
extern int g_v59_chain_hits;
extern int g_v59_mode_from_chain;
extern int g_v59_idle_probe_logged;
extern uintptr_t g_v59_last_cand;
extern uintptr_t g_v59_last_vt;
extern char g_v59_last_why[96];
extern char g_v59_drop_tags[TNX_V59_TAG_MAX][8];
extern char g_v59_keep_tags[TNX_V59_TAG_MAX][8];
extern int g_v65_sig_ticks;
extern int g_v65_sig_logs;
extern uintptr_t g_v65_sig_last;
extern int g_v67_layout_used;
extern int g_v67_layout_logs;
extern int g_v72_trail_refusals;
extern uintptr_t g_players_array;
extern int g_players_count;
extern int g_players_cap;
extern int g_v85_field_scans;
extern int g_v88_elem_full_dumps;
extern int g_v88_walk_relogs;
extern uint64_t g_v89_walk_tick;
extern uint64_t g_v89_enter_tick;
extern int g_v89_walk_count;
extern int g_v89_coord_fixed_logged;
extern int g_v62_class_pass;
extern int g_v62_alerts_off;
extern const char *g_v62_mode_source;
extern uint64_t g_v224_t0;
extern uint64_t g_v224_slow;
extern const struct tnx_t_g_slot_specs g_slot_specs[TNX_SLOT_COUNT];
extern int g_ag_installed;
extern uint64_t g_ag_hits;
extern uintptr_t g_ag_manager;
extern uintptr_t g_ag_objects[TNX_AG_OBJECT_MAX];
extern int g_ag_objectCount;
extern uint64_t g_v201_write_denied;
extern int g_v201_deny_logs;
extern UILabel *g_overlay;
extern double g_overlay_last;
extern int g_scan_ticks;
extern uint64_t g_v219_drain;
extern uint64_t g_v219_q_max;
extern uint64_t g_v217_drag_writes;
extern uint64_t g_v217_drag_back;
extern int g_alert_shown;
extern uint64_t g_alert_cleared_ms;
extern int32_t g_v132_gid_lo;
extern int32_t g_v132_gid_hi;
extern uintptr_t g_v132_alert_scene;
extern uint64_t g_v132_alert_ms;
extern uintptr_t g_v108_owner;
extern int g_v109_done;
extern uintptr_t g_v110_owner;
extern int g_v110_wired;
extern dispatch_source_t g_scan_timer;
extern tnx_region_t g_heap_regions[TNX_HEAP_REGION_MAX];
extern int g_heap_region_count;
extern uintptr_t g_heap_window_low;
extern uintptr_t g_heap_window_high;
extern int g_heap_window_ok;
extern const uintptr_t g_mode_vtables[36];
extern tnx_trail_t g_trail[TNX_TRAIL_MAX];
extern int g_trail_count;
extern uint64_t g_trail_total;
extern tnx_seen_t g_seen[TNX_SEEN_MAX];
extern int g_v176_gate_last;
extern int g_v176_gate_logs;
extern int g_dodge_probe_usable;
extern int g_v170_step_logs;
extern int g_v170_elem_logs;
extern uintptr_t g_v170_last_own;
extern int g_v151_logs;
extern int32_t g_v152_last_tx;
extern int32_t g_v152_last_ty;
extern int g_v152_issued;
extern uintptr_t g_v182_own_elem;
extern uintptr_t g_v185_enemy_elem;
extern uint64_t g_v156_push_logs;
extern uint64_t g_v120_reloads;
extern uint64_t g_v122_pre_reloads;
extern uint64_t g_v122_pre_frames;
extern uint64_t g_v121_push_frame;
extern uint64_t g_v121_win_reloads;
extern int g_v121_win_stage;
extern float g_v165_dir_x;
extern float g_v165_dir_y;
extern int g_v244_human;
extern int g_v244_touch;
extern int g_v244_moved;
extern uint64_t g_v244_stops;
extern uint64_t g_v244_queue_skips;
extern int g_v244_logs;
extern float g_v244_org_x;
extern float g_v244_org_y;
extern float g_v244_cur_x;
extern float g_v244_cur_y;
extern int32_t g_v180_tx;
extern int32_t g_v180_ty;
extern uint64_t g_v180_hold;

int tnx_verified_vtable(uintptr_t vtable);
uintptr_t tnx_strip_imp(IMP imp);
void tnx_battle_write(const char *utf8, size_t len);
uint64_t tnx_slot_repl_0(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_1(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_2(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_3(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_4(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_5(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_6(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_7(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_8(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_9(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_10(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_11(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_12(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_13(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_14(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_15(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_16(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_17(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_18(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_19(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_20(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_21(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_22(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_23(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_24(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_25(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_26(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_27(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_28(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_29(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_30(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_31(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_32(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
uint64_t tnx_slot_repl_33(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7);
BOOL tnx_query_region(uintptr_t address, vm_prot_t *protection, vm_prot_t *maxProtection, mach_vm_size_t *regionSize, uintptr_t *regionStart);
BOOL tnx_addr_writable(uintptr_t address, size_t length);
BOOL tnx_read_bytes(uintptr_t address, void *out, size_t length);
BOOL tnx_pointer_plausible(uintptr_t value);
BOOL tnx_read_u8(uintptr_t address, uint8_t *out);
BOOL tnx_read_i32(uintptr_t address, int32_t *out);
BOOL tnx_read_f32(uintptr_t address, float *out);
BOOL tnx_v201_writable(uintptr_t address, size_t length);
void tnx_v245_note(uintptr_t address, const void *src, size_t length, int denied);
BOOL tnx_write_bytes(uintptr_t address, const void *src, size_t length);
BOOL tnx_write_f32(uintptr_t address, float value);
BOOL tnx_read_ptr(uintptr_t address, void **out);
void *tnx_read_global_ptr(uintptr_t rva);
uintptr_t tnx_callable(uintptr_t rva);
uintptr_t tnx_pick(uintptr_t rvaA, uintptr_t rvaB);
BOOL tnx_copy(uintptr_t source, void *destination, size_t length);
BOOL tnx_text_section(uintptr_t *address, uint64_t *size);
BOOL tnx_valid_header(uintptr_t base);
BOOL find_game_image(uintptr_t *out_base);
BOOL tnx_segment_range(const char *name, uintptr_t *lo, uintptr_t *hi);
BOOL tnx_image_contains(uintptr_t value);
void tnx_image_span_refresh(void);
BOOL tnx_in_image_span(uintptr_t value);
const char *tnx_image_segment_name(uintptr_t value);
void tnx_heap_regions_refresh(void);
BOOL tnx_heap_window_shaped(uintptr_t value);
BOOL tnx_heap_contains(uintptr_t value);
BOOL tnx_vtable_shaped(uintptr_t value);
BOOL tnx_heap_resident(uintptr_t value);
BOOL tnx_owner_is_heap(uintptr_t owner);
char tnx_v72_seg_code(uintptr_t value);
BOOL tnx_v72_image_resident(uintptr_t value);
BOOL tnx_gameobject_shape(uintptr_t object);
BOOL tnx_instance_shaped(uintptr_t object);
BOOL tnx_manager_shape(uintptr_t manager);
uintptr_t tnx_vtable_rva(void *object);
void tnx_trail_note(uintptr_t manager, int32_t count, int32_t capacity, int live, int nonEmpty, int ascii, int sampled, int noVt, int teamDistinct, int posDistinct, int refused);
int tnx_write_i32(uintptr_t address, int32_t value);
BOOL tnx_v56_vtable_in_image(uintptr_t vtable);
int tnx_v59_container_at(uintptr_t object, int32_t *countOut, int32_t *capOut, char *why, size_t whyLen);
int tnx_v60_container_resolve(uintptr_t manager, uintptr_t *containerOut, int32_t *countOut, int32_t *capOut, char *why, size_t whyLen);
uintptr_t tnx_v60_strip_ptr(uintptr_t value);
void poll_for_game(int tick);

#endif
