#ifndef TITANOX_CORE_MEMORY_H
#define TITANOX_CORE_MEMORY_H

#include "core/types.h"


extern const char *t_image_names[4];
extern const tnx_rva_entry_t t_rvas[32];
extern uintptr_t t_base;
extern uintptr_t *t_starts;
extern size_t t_starts_count;
extern FILE *t_log;
extern long t_log_written;
extern BOOL t_setup_done;
extern BOOL t_wm_failed;
extern BOOL t_wm_ready;
extern BOOL t_aim_rejected;
extern __thread BOOL t_inside_hook;
extern uint64_t t_dodge_calls;
extern uint64_t t_render_calls;
extern int t_dump_np;
extern uintptr_t t_prev_scene;
extern const uintptr_t t_mode_vtables_verified[3];
extern uintptr_t t_scene_object;
extern BOOL t_mode_strong;
extern int t_mode_best_objects;
extern int t_mode_last_types;
extern int t_mode_verified_hits;
extern uintptr_t t_players_object;
extern int t_manager_count;
extern int t_manager_probes;
extern int t_manager_probes_total;
extern int t_manager_skipped;
extern int t_manager_last_live;
extern int t_manager_last_nonempty;
extern int t_manager_last_capacity;
extern int t_manager_saw_cap;
extern int t_manager_loose_count;
extern int t_chain_checks;
extern int t_chain_probes;
extern int t_chain_skipped;
extern int t_chain_best_own;
extern int t_chain_best_gid;
extern int t_seen_stable;
extern int t_owner_vote_count;
extern unsigned long long t_objvote_hits;
extern unsigned long long t_objvote_skipped;
extern int t_objvote_dead_seen;
extern uintptr_t t_objvote_best_owner;
extern int t_objvote_best_gids;
extern int t_objvote_confirm;
extern BOOL t_objvote_owner_ok;
extern unsigned long long t_objvote_owner_img;
extern unsigned long long t_objvote_obj_img;
extern int t_objvote_best_teamcount;
extern int t_objvote_best_gids_full;
extern tnx_objhit_t t_objhits[TNX_OBJ_HIT_DUMP_MAX];
extern int t_objhit_count;
extern unsigned long long t_objvote_owner_reg;
extern unsigned long long t_objvote_owner_above_win;
extern int t_objvote_max_votes;
extern unsigned long long t_objvote_shaped;
extern tnx_vtcensus_t t_vtcensus[TNX_VTCENSUS_MAX];
extern int t_vtcensus_used;
extern unsigned long long t_vtcensus_total;
extern int t_heap_big_skip;
extern int t_heap_region_capped;
extern uintptr_t t_img_span_lo;
extern uintptr_t t_img_span_hi;
extern int t_img_span_ok;
extern int t_trail_best;
extern int t_manager_cap_rejects;
extern int t_manager_best_count;
extern int t_manager_best_live;
extern int t_heap_passes;
extern unsigned long long t_heap_covered;
extern uintptr_t t_mode_source;
extern int t_votescan_attempts;
extern double t_votescan_last;
extern BOOL t_snapshot_first;
extern BOOL t_snapshot_second;
extern double t_snapshot_start;
extern tnx_objc_hook_t t_objc_hooks[OBJC_HOOK_MAX];
extern int t_objc_armed;
extern uintptr_t t_addr_getinstance;
extern uintptr_t t_addr_getownchar;
extern uintptr_t t_addr_getteam;
extern uintptr_t t_addr_getx;
extern uintptr_t t_addr_gety;
extern uintptr_t t_addr_setprediction;
extern uintptr_t t_addr_sendmovement;
extern uintptr_t t_addr_getclip;
extern uintptr_t t_addr_gettf;
extern uintptr_t t_addr_settext;
extern uintptr_t t_addr_setxy;
extern uintptr_t t_addr_addchild;
extern uintptr_t t_addr_battlescreen;
extern void *t_label_clip;
extern void *t_label_tf;
extern void *t_label_sc;
extern char t_label_text[64];
extern int t_label_updates;
extern uintptr_t t_addr[TNX_JOURNAL];
extern uint32_t t_value[TNX_JOURNAL];
extern uint64_t t_tick_3[TNX_JOURNAL];
extern const char *t_phase_2[TNX_JOURNAL];
extern uint8_t t_size[TNX_JOURNAL];
extern uint8_t t_denied[TNX_JOURNAL];
extern volatile int t_at;
extern volatile uint64_t t_writes_2;
extern uint64_t t_stale;
extern int t_chain_rej[20];
extern int t_chain_probes_pass;
extern int t_layout_logs;
void tnx_mirror_probe(int dodging);
extern int t_no_source_passes;
extern int t_route_logged;
extern int t_ag_adopted;
extern int t_chain_hits;
extern int t_mode_from_chain;
extern int t_idle_probe_logged;
extern uintptr_t t_last_cand;
extern uintptr_t t_last_vt;
extern char t_last_why[96];
extern int t_sig_ticks;
extern int t_sig_logs;
extern uintptr_t t_sig_last;
extern int t_trail_refusals;
extern uintptr_t t_players_array;
extern int t_players_count;
extern int t_players_cap;
extern int t_field_scans;
extern int t_elem_full_dumps;
extern int t_walk_relogs;
extern uint64_t t_walk_tick;
extern uint64_t t_enter_tick;
extern int t_walk_count;
extern int t_coord_fixed_logged;
extern int t_class_pass;
extern int t_alerts_off;
extern const char *t_mode_source_2;
extern uint64_t t_t0;
extern uint64_t t_slow;
extern int t_ag_installed;
extern uint64_t t_ag_hits;
extern uintptr_t t_ag_manager;
extern uintptr_t t_ag_objects[TNX_AG_OBJECT_MAX];
extern int t_ag_objectCount;
extern uint64_t t_write_denied;
extern int t_deny_logs;
extern UILabel *t_overlay;
extern int t_scan_ticks;
extern uint64_t t_drain;
extern uint64_t t_q_max;
extern uint64_t t_drag_writes;
extern uint64_t t_drag_back;
extern int t_alert_shown;
extern uint64_t t_alert_cleared_ms;
extern int32_t t_gid_lo;
extern int32_t t_gid_hi;
extern uintptr_t t_alert_scene;
extern uint64_t t_alert_ms;
extern uintptr_t t_owner;
extern int t_done;
extern uintptr_t t_owner_2;
extern int t_wired;
extern dispatch_source_t t_scan_timer;
extern tnx_region_t t_heap_regions[TNX_HEAP_REGION_MAX];
extern int t_heap_region_count;
extern uintptr_t t_heap_window_low;
extern uintptr_t t_heap_window_high;
extern int t_heap_window_ok;
extern const uintptr_t t_mode_vtables[36];
extern tnx_trail_t t_trail[TNX_TRAIL_MAX];
extern int t_trail_count;
extern uint64_t t_trail_total;
extern int t_gate_last;
extern int t_gate_logs;
extern int t_dodge_probe_usable;
extern int t_step_logs;
extern int t_elem_logs;
extern uintptr_t t_last_own;
extern int t_logs;
extern int32_t t_last_tx;
extern int32_t t_last_ty;
extern int t_issued;
extern uintptr_t t_own_elem_2;
extern uintptr_t t_enemy_elem;
extern uint64_t t_push_logs;
extern uint64_t t_reloads;
extern uint64_t t_pre_reloads;
extern uint64_t t_pre_frames;
extern uint64_t t_push_frame_2;
extern uint64_t t_win_reloads;
extern int t_win_stage;
extern float t_dir_x;
extern float t_dir_y;
extern int t_human_2;
extern int t_touch;
extern int t_moved_3;
extern uint64_t t_stops;
extern uint64_t t_queue_skips_2;
extern float t_org_x;
extern float t_org_y;
extern float t_cur_x;
extern float t_cur_y;
extern int32_t t_tx_3;
extern int32_t t_ty_3;
extern uint64_t t_hold;

int tnx_verified_vtable(uintptr_t vtable);
uintptr_t tnx_strip_imp(IMP imp);
BOOL tnx_query_region(uintptr_t address, vm_prot_t *protection, vm_prot_t *maxProtection, mach_vm_size_t *regionSize, uintptr_t *regionStart);
BOOL tnx_addr_writable(uintptr_t address, size_t length);
BOOL tnx_read_bytes(uintptr_t address, void *out, size_t length);
BOOL tnx_pointer_plausible(uintptr_t value);
BOOL tnx_read_u8(uintptr_t address, uint8_t *out);
BOOL tnx_read_i32(uintptr_t address, int32_t *out);
BOOL tnx_read_f32(uintptr_t address, float *out);
BOOL tnx_writable(uintptr_t address, size_t length);
void tnx_note(uintptr_t address, const void *src, size_t length, int denied);
BOOL tnx_write_bytes(uintptr_t address, const void *src, size_t length);
BOOL tnx_write_f32(uintptr_t address, float value);
BOOL tnx_read_ptr(uintptr_t address, void **out);
void *tnx_read_global_ptr(uintptr_t rva);
uintptr_t tnx_callable(uintptr_t rva);
uintptr_t tnx_pick(uintptr_t rvaA, uintptr_t rvaB);
BOOL tnx_copy(uintptr_t source, void *destination, size_t length);
BOOL tnx_text_section(uintptr_t *address, uint64_t *size);
BOOL tnx_valid_header(uintptr_t base);
BOOL find_game_image(uintptr_t *out_base);
BOOL tnx_segment_range(const char *name, uintptr_t *lo, uintptr_t *hi);
BOOL tnx_image_contains(uintptr_t value);
void tnx_image_span_refresh(void);
BOOL tnx_in_image_span(uintptr_t value);
const char *tnx_image_segment_name(uintptr_t value);
void tnx_heap_regions_refresh(void);
BOOL tnx_heap_contains(uintptr_t value);
BOOL tnx_vtable_shaped(uintptr_t value);
BOOL tnx_heap_resident(uintptr_t value);
BOOL tnx_owner_is_heap(uintptr_t owner);
BOOL tnx_gameobject_shape(uintptr_t object);
BOOL tnx_instance_shaped(uintptr_t object);
BOOL tnx_manager_shape(uintptr_t manager);
uintptr_t tnx_vtable_rva(void *object);
int tnx_write_i32(uintptr_t address, int32_t value);
BOOL tnx_vtable_in_image(uintptr_t vtable);
uintptr_t tnx_strip_ptr(uintptr_t value);
void poll_for_game(int tick);

#endif
