#ifndef OFFSETS_H
#define OFFSETS_H

#include <stddef.h>
#include <stdint.h>
#include <mach-o/loader.h>

#define RVA_ANALYTICEVENT__SETSTRING 0xb47828ULL
#define RVA_BATTLESCREEN__UPDATEAUTOSHOOT 0x807668ULL
#define RVA_COMBATHUD__SETMOVESTICKSTATE 0x5857ecULL
#define RVA_LOGICCHARACTERCLIENTOWN__CLIENTPREDICTIONPAUSEMOVEMENTFORSKILLCASTING 0xab7094ULL
#define RVA_LOGICGAMEPLAYUTIL__GETCLOSESTANYCOLLISION 0xbd55c4ULL
#define RVA_LOGICSKILLDATA__GETRECHARGETIME 0xa943bcULL
#define RVA_MAPEDITORSCREEN__INITITEMS 0x82c500ULL
#define RVA_MESSAGEMANAGER__RECEIVEMESSAGE 0x7bace8ULL
#define RVA_SPRITE_SPRITE 0xc2d680ULL
#define RVA_STAGE_ADDCHILD 0xc33690ULL
#define RVA_LOGICSKILLDATA__GETMAXCHARGE 0xa943bcULL
#define RVA_LOGICSKILLDATA__GETMSBETWEENATTACKS 0xa943bcULL

#define RVA_LOGICBATTLEMODECLIENT_SETCLIENTPREDICTIONMOVETO 0xac3f20ULL
#define RVA_SETCLIENTPREDICTION 0xac3f20ULL

#define RVA_CLIENTINPUTMANAGER_ADDINPUT 0x74675cULL

#define RVA_BATTLEMODE_GETINSTANCE 0ULL
#define RVA_BATTLESCREEN__BATTLESCREEN 0ULL
#define RVA_BATTLESCREEN__TRYTOACTIVATESKILL 0ULL
#define RVA_BATTLESCREEN__UPDATEMOVEMENT 0x7a60f4ULL
#define RVA_BATTLESCREEN_ACTIVATESKILL 0ULL
#define RVA_BATTLESCREEN_FIREWRAPPERFN 0ULL
#define RVA_BATTLESCREEN_GETCLOSESTTARGETFORAUTOSHOOT 0ULL
#define RVA_CLIENTINPUTMESSAGE_SENDMOVEMENT 0ULL
#define RVA_COMBATHUD__SETSHOOTSTICKSTATE 0ULL
#define RVA_DISPLAYOBJECT__SETXY 0ULL
#define RVA_LOGICBATTLEMODECLIENT_GETOWNCHARACTER 0ULL
#define RVA_LOGICBATTLEMODECLIENT_GETOWNPLAYERTEAM 0ULL
#define RVA_LOGICBATTLEMODECLIENT_UPDATE 0ULL
#define RVA_LOGICCHARACTERDATA_GETCOLLISIONRADIUS 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETDATA 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETGLOBALID 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETX 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETY 0ULL
#define RVA_LOGICGAMEOBJECTMANAGERCLIENT__GETGAMEOBJECTS 0ULL
#define RVA_LOGICPROJECTILEDATA_GETRADIUS 0ULL
#define RVA_LOGICPROJECTILEDATA_GETSPEED 0ULL
#define RVA_LOGICTILEMAP__ISPLAYERLINEOFSIGHTCLEAR 0ULL
#define RVA_MOVIECLIP__GETTEXTFIELDBYNAME 0ULL
#define RVA_STRINGTABLE_GETMOVIECLIP 0ULL
#define RVA_TEXTFIELD_SETTEXT 0ULL

#define OFF_APPLICATION__COPYSTRING 0xe4a7b4ULL
#define OFF_BATTLEMODE_CLIENTINPUTMANAGER 0x58ULL
#define OFF_BATTLEMODE_OBJECTMANAGERPTR 0x28ULL
#define OFF_BATTLESCREEN_AUTOFIREX 0xe6cULL
#define OFF_BATTLESCREEN_AUTOFIREY 0xe70ULL
#define OFF_BATTLESCREEN_AUTOSHOOTPREDOFF 0x66cULL
#define OFF_BATTLESCREEN_MANUALFIREX 0xf04ULL
#define OFF_BATTLESCREEN_MANUALFIREY 0xf08ULL
#define OFF_BATTLESCREEN_SCREENHEIGHT 0x888ULL
#define OFF_BATTLESCREEN_SCREENWIDTH 0x884ULL
#define OFF_BATTLESCREEN_VIEWMATRIX 0x7e8ULL
#define OFF_CHARDATA_BRAWLERID 0x18ULL
#define OFF_CHARDATA_SPEED 0x1c4ULL
#define OFF_CLIENTINPUT_X 0xcULL
#define OFF_CLIENTINPUT_Y 0x10ULL
#define OFF_FRAMERATEMANAGER__SETSEGMENT 0xddbde0ULL
#define OFF_GAMEOBJ_DEADFLAG 0xd0ULL
#define OFF_GAMEOBJ_TEAM 0x40ULL
#define OFF_HERODATA_NAMEPTR 0x48ULL
#define OFF_JOY_CENTERX 0x9cULL
#define OFF_JOY_CENTERY 0xa0ULL
#define OFF_JOY_CURRENTX 0x94ULL
#define OFF_JOY_CURRENTY 0x98ULL
#define OFF_JOY_ISDRAGGING 0x10ULL
#define OFF_MESSAGE_IPPTR 0x98ULL
#define OFF_MESSAGE_PORT 0x90ULL
#define OFF_OBJECTMANAGER_COUNT 0xcULL
#define OFF_OBJECTMANAGER_OBJECTSARRAY 0x0ULL
#define OFF_OBJECTMANAGER_PTRSTRIDE 0x8ULL
#define OFF_PROJECTILE_SPAWNANGLE 0xb8ULL
#define OFF_SCSTRING_DATA 0x8ULL
#define OFF_SCSTRING_LENGTH 0x4ULL
#define OFF_SCREEN__GETDPICLASS 0xde2200ULL
#define OFF_SCREEN__GETHEIGHT 0xde21f4ULL
#define OFF_SOCKADDR_ADDR0 0x4ULL
#define OFF_SOCKADDR_ADDR1 0x5ULL
#define OFF_SOCKADDR_ADDR2 0x6ULL
#define OFF_SOCKADDR_ADDR3 0x7ULL
#define OFF_SOCKADDR_PORTHI 0x2ULL
#define OFF_SOCKADDR_PORTLO 0x3ULL
#define OFF_STAGEINSTANCEGLOBALPTR 0x12393e0ULL
#define OFF_STRINGCTOR 0xdcf8f0ULL
#define OFF_STRING__FORMAT 0xdd244cULL
#define OFF_TILEMAP_HEIGHT 0xc8ULL
#define OFF_TILEMAP_TILESARRAY 0x20ULL
#define OFF_TILEMAP_WIDTH 0xc4ULL
#define OFF_TILETYPEDATA_BLOCKSMOVEMENT 0x56ULL
#define OFF_TILETYPEDATA_BLOCKSPROJECTILES 0x57ULL
#define OFF_VTABLE_CHARACTER_DATA 0x000ff5440ULL
#define OFF_VTABLE_PROJECTILE_DATA 0x000ff57b0ULL
#define OFF_NATIVECOPYTOCLIPBOARD 0xdd91f8ULL

#define OFF_GAMEOBJ_GID 0x8
#define OFF_GAMEOBJ_X 0x30
#define OFF_GAMEOBJ_Y 0x34
#define OFF_GAMEOBJ_OWNERINDEX 0x3c
#define OFF_GAMEOBJ_ACTIVEFLAG 0x1e8
#define OFF_CTRL_STICK_X 0xfa4
#define OFF_CTRL_STICK_Y 0xfa8
#define OFF_CTRL_APPLIED_X 0xfcc
#define OFF_CTRL_APPLIED_Y 0xfd0
#define OFF_CTRL_TOUCH_GATE 0xf7f
#define OFF_CTRL_TOUCH_STATE 0xf80
#define OFF_CTRL_TOUCH_ID 0xf84
#define OFF_MODE_PREDICT_X 0x1d4
#define OFF_MODE_PREDICT_Y 0x1d8
#define OFF_CTRL_APPLIED_IDLE -300

#define RCL_TOUCH_GATE_OFF 0xf7fULL
#define RCL_TOUCH_ID_OFF 0xf84ULL
#define RCL_TOUCH_STATE_OFF 0xf80ULL
#define RCL_JOY_STATE_OFF 0xed7ULL
#define RCL_JOY_AA_OFF 0x8f4ULL
#define RCL_JOY_AB_OFF 0x8f8ULL
#define RCL_FLAG_OFF_2 0xf9cULL
#define RCL_JOYSTATE_OFF 0xed7ULL
#define RCL_LIST_OFF 0x20ULL
#define RCL_GATE_OFF 0x70ULL
#define RCL_RVA_GETTEXTFIELDBYNAME_A 0xc1d7b0ULL
#define RCL_RVA_GETTEXTFIELDBYNAME_B 0xc1d550ULL
#define RCL_RVA_SETTEXT_A 0x990c20ULL
#define RCL_RVA_SETTEXT_B 0xc4a978ULL
#define RCL_RVA_SETXY_A 0xc16b54ULL
#define RCL_RVA_SETXY_B 0xc16b4cULL
#define RCL_MODE_MANAGER_OFF 0x28ULL
#define RCL_MGR_ARRAY_OFF 0x0ULL
#define RCL_MGR_COUNT_OFF 0xcULL
#define RCL_MGR_CAP_OFF 0x8ULL
#define RCL_MODE_INPUTMGR_OFF 0x58ULL
#define RCL_DC_RVA_LO 0xf74000ULL
#define RCL_OBJ_GLOBALID_OFF 0x8ULL
#define RCL_GID_FALLBACK_OFF 0x50ULL
#define RCL_FLAG_OFF 0xacULL
#define RCL_INPUT_X_OFF 0x10cULL
#define RCL_INPUT_FLAG_OFF 0x114ULL
#define RCL_INPUT_ARM_OFF 0xacULL
#define RCL_INPUT_Y_OFF 0x110ULL
#define RCL_INPUT_K_OFF 0x114ULL
#define RCL_SETINPUT_RVA 0xac3a58ULL
#define RCL_MOVE_RVA 0xac3a58ULL
#define RCL_MOVE_FLAG 0
#define RCL_MOVE_FLAG_10 1
#define RCL_MOVE_X_OFF 0x10cULL
#define RCL_MOVE_Y_OFF 0x110ULL
#define RCL_MOVE_KEY_OFF 0x114ULL
#define RCL_MOVE_ARM_OFF 0xacULL
#define RCL_MOVE_ARM_ON 1
#define RCL_MOVE_COORD_LIMIT 200000
#define RCL_MOVE_SCAN_END 0x4f8ULL
#define RCL_MOVE_PROBE_TICK 900ULL
#define RCL_READER_RVA 0x00ac3424ULL
#define RCL_ALLOC_RVA 0x00d8da2cULL
#define RCL_MSGCTOR_RVA 0x00a95798ULL
#define RCL_HOP_RVA 0x7b9050ULL
#define RCL_CI_MGR_QUEUE_OFF 0x20ULL
#define RCL_TYPE_MOVE_ALT 0xaULL

#define RCL_TYPE_ATTACK RCL_TYPE_MOVE_ALT

#define RCL_AIM_HIT_DIST 400.0f

#define RCL_AIM_DOT_MIN 0.9f
#define RCL_ADDINPUT_RVA 0x74675cULL
#define RCL_GETBATTLE_RVA 0x008c5130ULL
#define RCL_MGR_OFF 0x58ULL
#define RCL_QUEUE_OFF 0x20ULL
#define RCL_QUEUE_COUNT_OFF 0xcULL
#define RCL_TYPE_OFF 0x08ULL
#define RCL_X_OFF 0x0cULL
#define RCL_Y_OFF 0x10ULL
#define RCL_SEQ_OFF 0x00ULL
#define RCL_READER_ENTRY_RVA 0x00ac1ee8ULL
#define RCL_READER_CALLER_RVA 0x008cc004ULL
#define RCL_MODE_OFF 0x124ULL
#define RCL_GATE_PTR_OFF 0x30ULL
#define RCL_ALLOC_GOT_RVA 0x00f78180ULL
#define RCL_OWN_OFF 0x918ULL
#define RCL_OWN_INNER_OFF 0x28ULL
#define RCL_BOX_PTR_OFF 0xf8ULL
#define RCL_MGR_SEQ_OFF 0x0cULL
#define RCL_OWN_ALIVE_OFF 0x140ULL
#define RCL_GATE_FLAG_OFF 0xacULL
#define RCL_GATE_X_OFF 0x10cULL
#define RCL_GATE_Y_OFF 0x110ULL
#define RCL_CTRL_RAW_X_OFF 0xfa4ULL
#define RCL_CTRL_RAW_Y_OFF 0xfa8ULL
#define RCL_CTRL_DIRTY_OFF 0xfa0ULL
#define RCL_CTRL_MOVE_OFF 0xf78ULL
#define RCL_CTRL_ALIVE_OFF 0xf80ULL
#define RCL_CTRL_ID_OFF 0xf84ULL
#define RCL_CTRL_GATE_OFF 0xf9eULL
#define RCL_CTRL_APPLIED_X_OFF 0xfccULL
#define RCL_CTRL_APPLIED_Y_OFF 0xfd0ULL

#define RVA_INPUT_COMMIT_10 0x79d594ULL
#define RVA_MGR_OBJ_LOOKUP_10 0xa267dcULL
#define RVA_JOY_FLIP_10 0x1123798ULL
#define RVA_WALK_MODE_10 0x536534ULL
#define RVA_DEAD_A_11 0xd5155cULL
#define RVA_DEAD_B_11 0xd51568ULL
#define RCL_DEAD_CONST 19.0908f
#define RCL_WALK_OBJ_OFF 0xa08ULL
#define RCL_JOY_CUR_X_OFF 0xa40ULL
#define RCL_JOY_CUR_Y_OFF 0xa44ULL
#define RCL_JOY_ORG_X_OFF 0xa48ULL
#define RCL_JOY_ORG_Y_OFF 0xa4cULL
#define RCL_CI_MGR_OBJLIST_OFF 0xa20ULL
#define RCL_LOCAL_ENT_FLAG_OFF 0x32bULL
#define RCL_WALK_PUSH_RAW 600.0f
#define RCL_WALK_PUSH_MIN_JUMP 50562

#define RCL_BATTLE_RVA 0x1123e58ULL
#define RCL_RVA_BATTLE_SCREEN_GET 0x008ce9d8ULL
#define RCL_RVA_BATTLE_ISSTATE 0x008ce9e8ULL
#define RCL_RVA_SCREEN_SLOT 0x008cdfd4ULL
#define RCL_OFF_BATTLE_STATE 0x50ULL
#define RCL_OFF_BATTLE_SCREEN 0x48ULL
#define RCL_JOY_PAIR_a 0x9b8ULL
#define RCL_JOY_PAIR_b 0x9d0ULL
#define RCL_JOY_PAIR_c 0xA20ULL
#define RCL_JOY_DRAG_OFF 0xF48ULL
#define RCL_JOY_DRAG2_OFF 0xF6EULL
#define RCL_JOY_TARGET_OFF 0x58ULL
#define RCL_OFF_CTRL_TOUCH_GATE 0xf7fULL
#define RCL_GATE_BYTE_OFF 0x7aULL
#define RCL_CLIENT_OFF 0x28ULL
#define RCL_CLIENT_POS_X_OFF 0x80ULL
#define RCL_CLIENT_POS_Y_OFF 0x84ULL
#define RCL_OBJ_TEAM_OFF 0x40ULL
#define RCL_OBJ_OWNERINDEX_OFF 0x3cULL
#define RCL_OBJ_DEADFLAG_OFF 0xd0ULL
#define RCL_MODE_MODEVAR_OFF 0x124ULL
#define RCL_MODE_PREDICTX_OFF 0x1d4ULL
#define RCL_MODE_PREDICTY_OFF 0x1d8ULL
#define RCL_SLOT_BRIDGE_OFF 0x8ULL
#define RCL_SLOT_OWNER_OFF 0x20ULL
#define RCL_SLOT_LIST_OFF 0x80ULL
#define RCL_SLOT_LISTCOUNT_OFF 0x8cULL
#define RCL_HP_OFF 0xacULL
#define RCL_HPMAX_OFF 0xb0ULL
#define RCL_CUR_X_OFF 0xa40ULL
#define RCL_CUR_Y_OFF 0xa44ULL
#define RCL_ORG_X_OFF 0xa48ULL
#define RCL_ORG_Y_OFF 0xa4cULL
#define RCL_PRECOND_OFF 0xf78ULL
#define RCL_MARK_OFF 0xf74ULL
#define RCL_SIGN_RVA 0x1123798ULL
#define RCL_TILES_OFF 0x20ULL
#define RCL_TYPE_MOVE_OFF 0x56ULL
#define RCL_TYPE_PROJ_OFF 0x57ULL
#define RCL_BOUNDS_RVA 0x00991440ULL
#define RCL_BOUNDS_X_OFF 0xccULL
#define RCL_BOUNDS_Y_OFF 0xd0ULL
#define RCL_MODEPAIR_RVA RCL_SETINPUT_RVA
#define RCL_CTRL_MODE_OFF 0x918ULL
#define RCL_RVA_SETPREDICTION 0x00ac3f20ULL
#define RCL_OBJ_X_OFF 0x30ULL
#define RCL_OBJ_Y_OFF 0x34ULL
#define RCL_OBJ_TEAMENGINE_OFF 0x4cULL
#define RCL_OBJ_ACTIVEFLAG_OFF 0x1e8ULL
#define RCL_MODE_TILEMAP_OFF 0xf8ULL
#define RCL_TILEMAP_WIDTH_OFF 0xc4ULL
#define RCL_TILEMAP_HEIGHT_OFF 0xc8ULL
#define RCL_TYPE_SLOT_OFF 0x28ULL
#define RCL_HYP_TEAM_OFF 0x4cULL
#define RCL_HYP_BYTE_OFF 0x48ULL
#define RCL_DEF_68_OFF 0x68ULL
#define RCL_ELEMCLASS_RVA 0x00f9e248ULL
#define RCL_ELEM_BACK_OFF 0x18ULL
#define RCL_TEAM_OFF 0x4cULL
#define RCL_DEAD_OFF 0xd4ULL
#define RCL_ELEM_ID_OFF_2 0x48ULL
#define RCL_ELEM_TEAM_OFF_2 0x4cULL
#define RCL_ARRAY_OFF 0x0ULL
#define RCL_COUNT_OFF_4 0xdcULL

#define RCL_COUNT_OFF 0xcULL
#define RCL_OWNIDX_OFF_2 0xe0ULL
#define RCL_OWNTEAM_OFF_2 0xe4ULL
#define RCL_GETTEAMSTARS_RVA 0xac3cfcULL
#define RCL_SETPRED_RVA 0xac3f20ULL
#define RCL_TILELOOKUP_RVA 0xac3f48ULL
#define RCL_SUBGETTER_RVA 0xac3f2cULL
#define RCL_OWNIDX_OFF 0xe0ULL
#define RCL_OWNTEAM_OFF 0xe4ULL
#define RCL_ELEM_ID_OFF 0x48ULL
#define RCL_ELEM_TEAM_OFF 0x4cULL
#define RCL_MODEPAIRSET_RVA RCL_SETINPUT_RVA
#define RCL_INPUTMGR_COS_OFF 0x8ULL
#define RCL_INPUTMGR_SIN_OFF 0xcULL
#define RCL_KIND_OFF 0x35cULL
#define RCL_STATE_RVA 0x1123e58ULL
#define RCL_STATE_ENUM_OFF 0x50ULL
#define RCL_SCENE_OFF 0x48ULL
#define RCL_SCENE_CLASS_RVA 0xfe9d00ULL
#define RCL_PLAYERS_NEXT_OFF 0xf8ULL
#define RCL_NEXT_MEMBER_OFF 0x68ULL
#define RCL_CLIENT_HOP_OFF 0x28ULL
#define RCL_ELEM_DEF_OFF 0x10ULL
#define RCL_OFF 0x70ULL
#define RCL_NP_PTR_OFF 0x38ULL

#define RCL_MAP_BASE_OFF RCL_MODE_MANAGER_OFF
#define RCL_MAP_PTR_OFF RCL_MODE_TILEMAP_OFF
#define RCL_MAP_WIDTH_OFF RCL_TILEMAP_WIDTH_OFF
#define RCL_MAP_HEIGHT_OFF RCL_TILEMAP_HEIGHT_OFF
#define RCL_MAP_COUNT_OFF RCL_COUNT_OFF_4
#define RCL_MAP_TILES_OFF RCL_TILES_OFF
#define RCL_TILE_PTR_STRIDE OFF_OBJECTMANAGER_PTRSTRIDE
#define RCL_TILE_TYPE_MOVE_OFF RCL_TYPE_MOVE_OFF
#define RCL_TILE_TYPE_PROJ_OFF RCL_TYPE_PROJ_OFF

#define RCL_SCREEN_ALLOC_SIZE 0x98ULL
#define RCL_STATE_BATTLE 5
#define RCL_RVA_BATTLE_SCREEN_FACTORY 0x8ce048ULL
#define RCL_RVA_BATTLE_SCREEN_CTOR 0x8c51f8ULL
#define RCL_RVA_SLOT_GLOBAL 0x1123e58ULL
#define RCL_RVA_SCENE_FROM_SLOT 0x8ce9d8ULL
#define RCL_RVA_STATE_FROM_SLOT 0x8ce9e8ULL
#define RCL_RVA_TILE_AT 0x941598ULL
#define RCL_RVA_TILE_BLOCKSMOVE 0x9ee4d4ULL
#define RCL_RVA_TILE_BLOCKSPROJ 0x9ee4dcULL
#define RCL_RVA_TILELOOKUP_CACHE 0xac3f48ULL
#define RCL_RVA_TILELOOKUP_CACHE_ARRAY 0x1f0ULL
#define RCL_RVA_TILELOOKUP_CACHE_COUNT 0x1fcULL

#define RCL_CI_CMD_BUF_SIZE RCL_MSG_SIZE
#define RCL_CI_TYPE_TABLE_RVA 0x00e1e058ULL
#define RCL_CI_TABLE_TYPES 0x17ULL
#define RCL_CI_MAX_TABLE_TYPE 0x16UL
#define RCL_CI_FALLBACK_TYPE_CONST 0xdeadbeefUL
#define RCL_CI_HASH_MASK_SIZE 0x10UL
#define RCL_CI_HASH_PAD_INNER 0x36
#define RCL_CI_HASH_PAD_OUTER 0x5c
#define RCL_CI_HASH_INNER_MASK_RVA 0x00e1bbd0ULL
#define RCL_CI_HASH_OUTER_MASK_RVA 0x00e1bbf0ULL
#define RCL_BM_HASH_ENABLED_OFF 0x70ULL
#define RCL_BM_HASH_KEY_OFF 0x60ULL
#define RCL_CI_TOKEN_OFF 0x34UL
#define RCL_CI_TOKEN_READ_OFF 0x4UL
#define RCL_CI_TOKEN_READ_LEN 0x10UL
#define RCL_CI_TOKEN_MSG_LEN 0x14UL
#define RCL_CI_TOKEN_MASK 0x7fUL
#define RCL_CI_TOKEN_MIN 1UL
#define RCL_CI_SIGN_SITE_RVA 0x007a6554ULL
#define RCL_CI_MOVE_TYPE 2
#define RCL_ENGINE_MOVE_RVA 0x007a64f0ULL
#define RCL_ENGINE_STICK_NORM_RVA 0x0079d678ULL
#define RCL_ENGINE_MOVE_BUILD_RVA 0x0079de88ULL
#define RCL_CTRL_LATCH_OFF 0xf9cULL
#define RCL_CTRL_LATCH_VAL 1
#define RCL_CTRL_DIRTY_VAL 0
#define RCL_CTRL_APPLIED_LIVE 1

#define RCL_MGR_UPDATE_RVA 0x00746898ULL
#define RCL_MGR_UPDATE_BODY_RVA 0x007468a4ULL
#define RCL_MGR_ALLOWED_RVA 0x00746e30ULL
#define RCL_SCREEN_UPDATE_RVA 0x008cbfa0ULL
#define RCL_MGR_ENABLE_OFF 0x18ULL
#define RCL_MGR_ALLOWED_FLAG_OFF 0x19ULL
#define RCL_MGR_COOLDOWN_OFF 0x08ULL
#define RCL_MGR_ACK_OFF 0x0cULL
#define RCL_MGR_QUEUE_OFF 0x20ULL
#define RCL_MGR_SEQ_A_OFF 0x10ULL
#define RCL_MGR_SEQ_B_OFF 0x14ULL
#define RCL_MGR_SENT_FLAG_OFF 0x1aULL
#define RCL_MGR_TIMER_OFF 0x3cULL
#define RCL_MGR_TIMER_B_OFF 0x40ULL
#define RCL_MGR_TICK_OFF 0x30ULL
#define RCL_MGR_TICK_B_OFF 0x34ULL
#define RCL_MGR_PEND_OFF 0x28ULL
#define RCL_MGR_COOLDOWN_MIN 1e-05f
#define RCL_MGR_ALLOW_LIMIT 0.3f
#define RCL_MGR_MS_LIMIT 0x7d1
#define RCL_CLIENT_ACK_SRC_OFF 0x48ULL

#define RCL_CLASS_PLAYER_RVA 0x000f9e248ULL
#define RCL_IMAGE_TEXT_WINDOW 0x4000ULL
#define RCL_SLOT_ALIVE_OFF 0x28ULL
#define RCL_SLOT_KIND_OFF 0x48ULL
#define RCL_CLASS_PROJ_ALT_RVA 0x000ff5100ULL
#define RCL_CLASS_PROJ_RVA 0x000ff57b0ULL
#define RCL_CLASS_THIRD_RVA 0x000ff56d8ULL
#define RCL_TYPEWORD_PLAYER 0x0014c81cULL
#define RCL_TYPEWORD_PROJ 0x00a31768ULL
#define RCL_TYPEWORD_THIRD 0x00a2e094ULL
#define RCL_VT_OFF 0x0ULL
#define RCL_TYPEWORD_OFF 0x28ULL
#define RCL_PROJ_OBJ_SIZE 0x138ULL
#define RCL_RVA_PROJ_CTOR 0x00a313f8ULL
#define RCL_RVA_PROJ_DTOR 0x00a319a0ULL
#define RCL_RVA_PROJ_ALLOC 0x00a313e0ULL
#define RCL_PROJ_CLASS_ONLY 1

typedef struct {
    uintptr_t base;
    const struct mach_header_64 *hdr;
} image_ref_t;

#ifdef __cplusplus
extern "C" {
#endif

uintptr_t rt_resolve_method(image_ref_t img, const char *cls, const char *meth, uintptr_t *func_starts, size_t starts_n, uintptr_t *xref_pc_out);
void rt_dump_image(image_ref_t img);
void rt_dump_target(const char *name, uintptr_t target);
int rt_is_code(image_ref_t img, uintptr_t target);

#ifdef __cplusplus
}
#endif

#define RCL_RECON_VT_SLOTS 12

#define RCL_RECON_SEED_BYTES 0x200

#define RCL_RECON_SEED_SCAN 0x1c0



#define RCL_RECON_CALL_RVA_MAX 0x2000000ULL

#define RCL_RECON_OFF_MANAGER_FROM 0x0ULL

#define RCL_RECON_OFF_MANAGER_TO 0x30ULL

#define RCL_RECON_OFF_SCENE_FROM 0x0ULL

#define RCL_RECON_OFF_SCENE_TO 0x60ULL

#define RCL_RECON_OFF_CTRL_FROM 0x0ULL

#define RCL_RECON_OFF_CTRL_TO 0x60ULL

#define RCL_RECON_OFF_JOY_FROM 0x9a0ULL

#define RCL_RECON_OFF_JOY_TO 0xa00ULL



#define RCL_RECON_OFF_CLIENT_FROM 0x8a0ULL

#define RCL_RECON_OFF_CLIENT_WIDE_FROM 0x800ULL

#define RCL_RECON_OFF_CLIENT_WIDE_TO 0xb40ULL

#define RCL_RECON_OFF_CLIENT_TAIL_FROM 0xe00ULL

#define RCL_RECON_OFF_CLIENT_TAIL_TO 0xfa0ULL

#define RCL_RECON_BATTLE_TICKS 900







#define RCL_RECON_HOPS 3

#define RCL_RECON_OFF_CLIENT_TO 0x9e0ULL



#define RCL_RECON_OFF_OWN_FROM 0x0ULL

#define RCL_RECON_OFF_OWN_TO 0x60ULL

#define RCL_RECON_OFF_CHARDATA_FROM 0x0ULL

#define RCL_RECON_OFF_CHARDATA_TO 0x240ULL

#define RCL_RECON_OFF_ELEM_FROM 0x0ULL

#define RCL_RECON_OFF_ELEM_TO 0x120ULL

#define RCL_RECON_OFF_HEAD_FROM 0x0ULL

#define RCL_RECON_OFF_HEAD_TO 0x60ULL

#define RCL_RECON_SEED_AUTOSHOOT_PRED_RVA 0x008072c8ULL




#define RCL_RECON_SEED_SCREEN_A_RVA 0x008c7ef0ULL

#define RCL_RECON_SEED_SCREEN_B_RVA 0x008c8050ULL

#define RCL_RECON_SEED_SCREEN_C_RVA 0x008cc57cULL

#define RCL_RECON_SEED_SCREEN_D_RVA 0x008cc6dcULL

#define RCL_RECON_SEED_SCREEN_E_RVA 0x008ce3b0ULL

#define RCL_RECON_SEED_SCREEN_F_RVA 0x008cf4c4ULL

#define RCL_RECON_SEED_CTOR_RVA 0x008c53fcULL

#define RCL_RECON_SEED_AUX_A_RVA 0x008cc514ULL

#define RCL_RECON_SEED_AUX_B_RVA 0x008ce3f8ULL

#define RCL_RECON_SEED_AUX_C_RVA 0x008ce27cULL

#define RCL_RECON_SEED_AUX_D_RVA 0x008c5130ULL

#define RCL_RECON_SEED_HELPER_RVA 0x009a9dacULL

#endif
