#ifndef OFFSETS_H
#define OFFSETS_H

#include <stddef.h>
#include <stdint.h>
#include <mach-o/loader.h>

#define RVA_ANALYTICEVENT__SETSTRING 0xb47828ULL
#define RVA_BATTLESCREEN__UPDATEAUTOSHOOT 0x807668ULL
#define RVA_COMBATHUD__SETMOVESTICKSTATE 0x5857ecULL
#define RVA_LOGICCHARACTERCLIENTOWN__CLIENTPREDICTIONPAUSEMOVEMENTFORSKILLCASTING 0xab7094ULL
#define RVA_LOGICGAMEPLAYUTIL__GETCLOSESTANYCOLLISION 0xbd55c4ULL
#define RVA_LOGICSKILLDATA__GETRECHARGETIME 0xa943bcULL
#define RVA_MAPEDITORSCREEN__INITITEMS 0x82c500ULL
#define RVA_MESSAGEMANAGER__RECEIVEMESSAGE 0x7bace8ULL
#define RVA_SPRITE_SPRITE 0xc2d680ULL
#define RVA_STAGE_ADDCHILD 0xc33690ULL
#define RVA_LOGICSKILLDATA__GETMAXCHARGE 0xa943bcULL
#define RVA_LOGICSKILLDATA__GETMSBETWEENATTACKS 0xa943bcULL

#define RVA_LOGICBATTLEMODECLIENT_SETCLIENTPREDICTIONMOVETO 0xac3f20ULL
#define RVA_SETCLIENTPREDICTION 0xac3f20ULL

#define RVA_CLIENTINPUTMANAGER_ADDINPUT 0x74675cULL

#define RVA_BATTLEMODE_GETINSTANCE 0ULL
#define RVA_BATTLESCREEN__BATTLESCREEN 0ULL
#define RVA_BATTLESCREEN__TRYTOACTIVATESKILL 0ULL
#define RVA_BATTLESCREEN__UPDATEMOVEMENT 0ULL
#define RVA_BATTLESCREEN_ACTIVATESKILL 0ULL
#define RVA_BATTLESCREEN_FIREWRAPPERFN 0ULL
#define RVA_BATTLESCREEN_GETCLOSESTTARGETFORAUTOSHOOT 0ULL
#define RVA_CLIENTINPUTMESSAGE_SENDMOVEMENT 0ULL
#define RVA_COMBATHUD__SETSHOOTSTICKSTATE 0ULL
#define RVA_DISPLAYOBJECT__SETXY 0ULL
#define RVA_LOGICBATTLEMODECLIENT_GETOWNCHARACTER 0ULL
#define RVA_LOGICBATTLEMODECLIENT_GETOWNPLAYERTEAM 0ULL
#define RVA_LOGICBATTLEMODECLIENT_UPDATE 0ULL
#define RVA_LOGICCHARACTERDATA_GETCOLLISIONRADIUS 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETDATA 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETGLOBALID 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETX 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETY 0ULL
#define RVA_LOGICGAMEOBJECTMANAGERCLIENT__GETGAMEOBJECTS 0ULL
#define RVA_LOGICPROJECTILEDATA_GETRADIUS 0ULL
#define RVA_LOGICPROJECTILEDATA_GETSPEED 0ULL
#define RVA_LOGICTILEMAP__ISPLAYERLINEOFSIGHTCLEAR 0ULL
#define RVA_MOVIECLIP__GETTEXTFIELDBYNAME 0ULL
#define RVA_STRINGTABLE_GETMOVIECLIP 0ULL
#define RVA_TEXTFIELD_SETTEXT 0ULL

#define OFF_APPLICATION__COPYSTRING 0xe4a7b4ULL
#define OFF_BATTLEMODE_CLIENTINPUTMANAGER 0x58ULL
#define OFF_BATTLEMODE_OBJECTMANAGERPTR 0x28ULL
#define OFF_BATTLESCREEN_AUTOFIREX 0xe6cULL
#define OFF_BATTLESCREEN_AUTOFIREY 0xe70ULL
#define OFF_BATTLESCREEN_AUTOSHOOTPREDOFF 0x66cULL
#define OFF_BATTLESCREEN_MANUALFIREX 0xf04ULL
#define OFF_BATTLESCREEN_MANUALFIREY 0xf08ULL
#define OFF_BATTLESCREEN_SCREENHEIGHT 0x888ULL
#define OFF_BATTLESCREEN_SCREENWIDTH 0x884ULL
#define OFF_BATTLESCREEN_VIEWMATRIX 0x7e8ULL
#define OFF_CHARDATA_BRAWLERID 0x18ULL
#define OFF_CHARDATA_SPEED 0x1c4ULL
#define OFF_CLIENTINPUT_X 0xcULL
#define OFF_CLIENTINPUT_Y 0x10ULL
#define OFF_FRAMERATEMANAGER__SETSEGMENT 0xddbde0ULL
#define OFF_GAMEOBJ_DEADFLAG 0xd0ULL
#define OFF_GAMEOBJ_TEAM 0x40ULL
#define OFF_HERODATA_NAMEPTR 0x48ULL
#define OFF_JOY_CENTERX 0x9cULL
#define OFF_JOY_CENTERY 0xa0ULL
#define OFF_JOY_CURRENTX 0x94ULL
#define OFF_JOY_CURRENTY 0x98ULL
#define OFF_JOY_ISDRAGGING 0x10ULL
#define OFF_MESSAGE_IPPTR 0x98ULL
#define OFF_MESSAGE_PORT 0x90ULL
#define OFF_OBJECTMANAGER_COUNT 0xcULL
#define OFF_OBJECTMANAGER_OBJECTSARRAY 0x0ULL
#define OFF_OBJECTMANAGER_PTRSTRIDE 0x8ULL
#define OFF_PROJECTILE_SPAWNANGLE 0xb8ULL
#define OFF_SCSTRING_DATA 0x8ULL
#define OFF_SCSTRING_LENGTH 0x4ULL
#define OFF_SCREEN__GETDPICLASS 0xde2200ULL
#define OFF_SCREEN__GETHEIGHT 0xde21f4ULL
#define OFF_SOCKADDR_ADDR0 0x4ULL
#define OFF_SOCKADDR_ADDR1 0x5ULL
#define OFF_SOCKADDR_ADDR2 0x6ULL
#define OFF_SOCKADDR_ADDR3 0x7ULL
#define OFF_SOCKADDR_PORTHI 0x2ULL
#define OFF_SOCKADDR_PORTLO 0x3ULL
#define OFF_STAGEINSTANCEGLOBALPTR 0x12393e0ULL
#define OFF_STRINGCTOR 0xdcf8f0ULL
#define OFF_STRING__FORMAT 0xdd244cULL
#define OFF_TILEMAP_HEIGHT 0xc8ULL
#define OFF_TILEMAP_TILESARRAY 0x20ULL
#define OFF_TILEMAP_WIDTH 0xc4ULL
#define OFF_TILETYPEDATA_BLOCKSMOVEMENT 0x56ULL
#define OFF_TILETYPEDATA_BLOCKSPROJECTILES 0x57ULL
#define OFF_VTABLE_CHARACTER_DATA 0x44bf6f8ULL
#define OFF_VTABLE_PROJECTILE_DATA 0x11501b0ULL
#define OFF_NATIVECOPYTOCLIPBOARD 0xdd91f8ULL

#define OFF_GAMEOBJ_GID 0x8
#define OFF_GAMEOBJ_X 0x30
#define OFF_GAMEOBJ_Y 0x34
#define OFF_GAMEOBJ_OWNERINDEX 0x3c
#define OFF_GAMEOBJ_ACTIVEFLAG 0x1e8
#define OFF_CTRL_STICK_X 0xfa4
#define OFF_CTRL_STICK_Y 0xfa8
#define OFF_CTRL_APPLIED_X 0xfcc
#define OFF_CTRL_APPLIED_Y 0xfd0
#define OFF_CTRL_TOUCH_GATE 0xf7f
#define OFF_CTRL_TOUCH_STATE 0xf80
#define OFF_CTRL_TOUCH_ID 0xf84
#define OFF_MODE_PREDICT_X 0x1d4
#define OFF_MODE_PREDICT_Y 0x1d8
#define OFF_CTRL_APPLIED_IDLE -300

#define TNX_TOUCH_GATE_OFF 0xf7fULL
#define TNX_TOUCH_ID_OFF 0xf84ULL
#define TNX_TOUCH_STATE_OFF 0xf80ULL
#define TNX_JOY_STATE_OFF 0xed7ULL
#define TNX_JOY_AA_OFF 0x8f4ULL
#define TNX_JOY_AB_OFF 0x8f8ULL
#define TNX_FLAG_OFF_2 0xf9cULL
#define TNX_JOYSTATE_OFF 0xed7ULL
#define TNX_LIST_OFF 0x20ULL
#define TNX_COUNT_OFF_2 0x0cULL
#define TNX_GATE_OFF 0x70ULL
#define TNX_RVA_GETTEXTFIELDBYNAME_A 0xc1d7b0ULL
#define TNX_RVA_GETTEXTFIELDBYNAME_B 0xc1d550ULL
#define TNX_RVA_SETTEXT_A 0x990c20ULL
#define TNX_RVA_SETTEXT_B 0xc4a978ULL
#define TNX_RVA_SETXY_A 0xc16b54ULL
#define TNX_RVA_SETXY_B 0xc16b4cULL
#define TNX_MODE_MANAGER_OFF 0x28ULL
#define TNX_MGR_ARRAY_OFF 0x0ULL
#define TNX_MGR_COUNT_OFF 0xcULL
#define TNX_MGR_CAP_OFF 0x8ULL
#define TNX_MODE_INPUTMGR_OFF 0x58ULL
#define TNX_DC_RVA_LO 0xf74000ULL
#define TNX_OBJ_GLOBALID_OFF 0x8ULL
#define TNX_GID_FALLBACK_OFF 0x50ULL
#define TNX_FLAG_OFF 0xacULL
#define TNX_INPUT_X_OFF 0x10cULL
#define TNX_INPUT_Y_OFF 0x110ULL
#define TNX_INPUT_K_OFF 0x114ULL
#define TNX_SETPRED4_RVA 0xac3a58ULL
#define TNX_READER_RVA 0x00ac3424ULL
#define TNX_ALLOC_RVA 0x00d8da2cULL
#define TNX_MSGCTOR_RVA 0x00a95798ULL
#define TNX_ADDINPUT_RVA 0x0074675cULL
#define TNX_GETBATTLE_RVA 0x008c5130ULL
#define TNX_MGR_OFF 0x58ULL
#define TNX_QUEUE_OFF 0x20ULL
#define TNX_QUEUE_COUNT_OFF 0xcULL
#define TNX_TYPE_OFF 0x08ULL
#define TNX_X_OFF 0x0cULL
#define TNX_Y_OFF 0x10ULL
#define TNX_SEQ_OFF 0x00ULL
#define TNX_HOP2_OWNER_OFF 0x28ULL
#define TNX_HOP2_INNER_OFF 0x28ULL
#define TNX_READER_ENTRY_RVA 0x00ac1ee8ULL
#define TNX_READER_CALLER_RVA 0x008cc004ULL
#define TNX_MODE_OFF 0x124ULL
#define TNX_GATE_PTR_OFF 0x30ULL
#define TNX_GATE3_PTR_OFF 0x38ULL
#define TNX_ALLOC_GOT_RVA 0x00f78180ULL
#define TNX_OWN_OFF 0x918ULL
#define TNX_OWN_INNER_OFF 0x28ULL
#define TNX_BOX_PTR_OFF 0xf8ULL
#define TNX_MGR_SEQ_OFF 0x14ULL
#define TNX_OWN_ALIVE_OFF 0x140ULL
#define TNX_GATE_FLAG_OFF 0xacULL
#define TNX_GATE_X_OFF 0x10cULL
#define TNX_GATE_Y_OFF 0x110ULL
#define TNX_CTRL_RAW_X_OFF 0xfa4ULL
#define TNX_CTRL_RAW_Y_OFF 0xfa8ULL
#define TNX_CTRL_DIRTY_OFF 0xfa0ULL
#define TNX_CTRL_ALIVE_OFF 0xf80ULL
#define TNX_CTRL_ID_OFF 0xf84ULL
#define TNX_CTRL_GATE_OFF 0xf9eULL
#define TNX_CTRL_APPLIED_X_OFF 0xfccULL
#define TNX_CTRL_APPLIED_Y_OFF 0xfd0ULL
#define TNX_BATTLE_RVA 0x1123b48ULL
#define TNX_GATE_BYTE_OFF 0x7aULL
#define TNX_CLIENT_OFF 0x28ULL
#define TNX_CLIENT_POS_X_OFF 0x80ULL
#define TNX_CLIENT_POS_Y_OFF 0x84ULL
#define TNX_OBJ_TEAM_OFF 0x40ULL
#define TNX_OBJ_OWNERINDEX_OFF 0x3cULL
#define TNX_OBJ_DEADFLAG_OFF 0xd0ULL
#define TNX_MODE_MODEVAR_OFF 0x124ULL
#define TNX_MODE_PREDICTX_OFF 0x1d4ULL
#define TNX_MODE_PREDICTY_OFF 0x1d8ULL
#define TNX_SLOT_BRIDGE_OFF 0x8ULL
#define TNX_SLOT_OWNER_OFF 0x20ULL
#define TNX_SLOT_LIST_OFF 0x80ULL
#define TNX_SLOT_LISTCOUNT_OFF 0x8cULL
#define TNX_HP_OFF 0xacULL
#define TNX_HPMAX_OFF 0xb0ULL
#define TNX_CUR_X_OFF 0xa40ULL
#define TNX_CUR_Y_OFF 0xa44ULL
#define TNX_ORG_X_OFF 0xa48ULL
#define TNX_ORG_Y_OFF 0xa4cULL
#define TNX_PRECOND_OFF 0xf78ULL
#define TNX_GATE_OFF_2 0xf9eULL
#define TNX_MARK_OFF 0xf74ULL
#define TNX_SIGN_RVA 0x1123798ULL
#define TNX_TILES_OFF 0x20ULL
#define TNX_COUNT_OFF_3 0xdcULL
#define TNX_TYPE_MOVE_OFF 0x56ULL
#define TNX_TYPE_PROJ_OFF 0x57ULL
#define TNX_BOUNDS_RVA 0x00991440ULL
#define TNX_BOUNDS_X_OFF 0xccULL
#define TNX_BOUNDS_Y_OFF 0xd0ULL
#define TNX_MODEPAIR_RVA 0x00ac3a58ULL
#define TNX_CTRL_MODE_OFF 0x918ULL
#define TNX_RVA_SETPREDICTION 0x00ac3f20ULL
#define TNX_OBJ_X_OFF 0x30ULL
#define TNX_OBJ_Y_OFF 0x34ULL
#define TNX_OBJ_TEAMENGINE_OFF 0x4cULL
#define TNX_OBJ_ACTIVEFLAG_OFF 0x1e8ULL
#define TNX_MODE_TILEMAP_OFF 0xf8ULL
#define TNX_TILEMAP_WIDTH_OFF 0xc4ULL
#define TNX_TILEMAP_HEIGHT_OFF 0xc8ULL
#define TNX_TYPE_SLOT_OFF 0x28ULL
#define TNX_HYP_TEAM_OFF 0x4cULL
#define TNX_HYP_BYTE_OFF 0x48ULL
#define TNX_DEF_68_OFF 0x68ULL
#define TNX_TYPE3_CLASS_RVA 0x00fd4840ULL
#define TNX_ELEMCLASS_RVA 0x00ff5440ULL
#define TNX_ELEM_BACK_OFF 0x18ULL
#define TNX_TEAM_OFF 0x4cULL
#define TNX_DEAD_OFF 0xd4ULL
#define TNX_ELEM_ID_OFF_2 0x48ULL
#define TNX_ELEM_TEAM_OFF_2 0x4cULL
#define TNX_ARRAY_OFF 0x0ULL
#define TNX_COUNT_OFF 0xcULL
#define TNX_OWNIDX_OFF_2 0xe0ULL
#define TNX_OWNTEAM_OFF_2 0xe4ULL
#define TNX_GETTEAMSTARS_RVA 0xac3cfcULL
#define TNX_SETPRED_RVA 0xac3f20ULL
#define TNX_MODEPAIRSET_RVA_2 0xac3a58ULL
#define TNX_TILELOOKUP_RVA 0xac3f48ULL
#define TNX_SUBGETTER_RVA 0xac3f2cULL
#define TNX_OWNIDX_OFF 0xe0ULL
#define TNX_OWNTEAM_OFF 0xe4ULL
#define TNX_ELEM_ID_OFF 0x48ULL
#define TNX_ELEM_TEAM_OFF 0x4cULL
#define TNX_MODEPAIRSET_RVA 0xac3a58ULL
#define TNX_INPUTMGR_COS_OFF 0x8ULL
#define TNX_INPUTMGR_SIN_OFF 0xcULL
#define TNX_KIND_OFF 0x35cULL
#define TNX_STATE_RVA 0x1123e58ULL
#define TNX_STATE_ENUM_OFF 0x50ULL
#define TNX_SCENE_OFF 0x48ULL
#define TNX_SCENE_CLASS_RVA 0xfe9d00ULL
#define TNX_PLAYERS_NEXT_OFF 0xf8ULL
#define TNX_NEXT_MEMBER_OFF 0x68ULL
#define TNX_CLIENT_HOP_OFF 0x28ULL
#define TNX_ELEM_DEF_OFF 0x10ULL
#define TNX_OFF 0x70ULL
#define TNX_NP_PTR_OFF 0x38ULL

#define TNX_MAP_BASE_OFF TNX_MODE_MANAGER_OFF
#define TNX_MAP_PTR_OFF TNX_MODE_TILEMAP_OFF
#define TNX_MAP_WIDTH_OFF TNX_TILEMAP_WIDTH_OFF
#define TNX_MAP_HEIGHT_OFF TNX_TILEMAP_HEIGHT_OFF
#define TNX_MAP_COUNT_OFF TNX_COUNT_OFF_3
#define TNX_MAP_TILES_OFF TNX_TILES_OFF
#define TNX_TILE_PTR_STRIDE OFF_OBJECTMANAGER_PTRSTRIDE
#define TNX_TILE_TYPE_MOVE_OFF TNX_TYPE_MOVE_OFF
#define TNX_TILE_TYPE_PROJ_OFF TNX_TYPE_PROJ_OFF

#define TNX_SCREEN_ALLOC_SIZE 0x98ULL
#define TNX_STATE_BATTLE 5
#define TNX_RVA_BATTLE_SCREEN_FACTORY 0x8ce048ULL
#define TNX_RVA_BATTLE_SCREEN_CTOR 0x8c51f8ULL
#define TNX_RVA_SLOT_GLOBAL 0x1123e58ULL
#define TNX_RVA_SCENE_FROM_SLOT 0x8ce9d8ULL
#define TNX_RVA_STATE_FROM_SLOT 0x8ce9e8ULL
#define TNX_RVA_TILE_AT 0x941598ULL
#define TNX_RVA_TILE_BLOCKSMOVE 0x9ee4d4ULL
#define TNX_RVA_TILE_BLOCKSPROJ 0x9ee4dcULL
#define TNX_RVA_TILE_BYTE_53 0x9ee4e4ULL
#define TNX_RVA_TILE_BYTE_52 0x9ee4ecULL
#define TNX_RVA_TILELOOKUP_CACHE 0xac3f48ULL
#define TNX_RVA_TILELOOKUP_CACHE_ARRAY 0x1f0ULL
#define TNX_RVA_TILELOOKUP_CACHE_COUNT 0x1fcULL

typedef struct {
    uintptr_t base;
    const struct mach_header_64 *hdr;
} image_ref_t;

#ifdef __cplusplus
extern "C" {
#endif

uintptr_t rt_resolve_method(image_ref_t img, const char *cls, const char *meth, uintptr_t *func_starts, size_t starts_n, uintptr_t *xref_pc_out);
void rt_dump_image(image_ref_t img);
void rt_dump_target(const char *name, uintptr_t target);
int rt_is_code(image_ref_t img, uintptr_t target);

#ifdef __cplusplus
}
#endif

#endif
