#ifndef OFFSETS_H
#define OFFSETS_H

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <objc/runtime.h>
#import <mach/mach.h>
#import <mach/vm_map.h>
#import <mach/mach_time.h>
#import <mach-o/dyld.h>
#import <mach-o/loader.h>
#import <dlfcn.h>
#import <dispatch/dispatch.h>
#import <math.h>
#import <stdarg.h>
#import <stdint.h>
#import <stdio.h>
#import <stdlib.h>
#import <string.h>
#import <unistd.h>
#import <signal.h>
#import "./offsets.h"
#include "hook.h"
#if __has_include(<ptrauth.h>)
#import <ptrauth.h>
#endif

typedef void (*fn_void_2_t)(void *, void *);
typedef void *(*fn_ptr_2_t)(void *, void *);
typedef void (*fn_settext_t)(void *, void *, int, int);
typedef void (*fn_setxy_t)(void *, float, float);
typedef void (*fn_send_movement_t)(void *, float, float);
typedef void (*fn_set_prediction_t)(void *, int, int);
typedef void *(*fn_get_inst_t)(void);
typedef void *(*fn_get_own_char_t)(void *);
typedef int (*fn_get_team_t)(void *);
typedef int (*fn_get_coord_t)(void *);
typedef struct
{
    uintptr_t at;
    uintptr_t vt;
    uintptr_t owner;
    int32_t gid;
    int32_t team;
    int32_t ownerIdx;
    int dead;
    int ownerClass;
} rcl_objhit_t;
typedef uint64_t (*rcl_slot_fn_t)(void *a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4,
                                  uint64_t a5, uint64_t a6, uint64_t a7);
typedef struct
{
    uintptr_t low;
    uintptr_t high;
} rcl_region_t;
typedef struct
{
    uintptr_t manager;
    int32_t count;
    int32_t capacity;
    int live;
    int nonEmpty;
    int stable;
    int rawOk;
    char rawSeg;
    int ascii;
    int sampled;
    int noVt;
    int teamDistinct;
    int posDistinct;
    int refused;
} rcl_trail_t;
typedef void (*rcl_setpred_t)(void *self, int x, int y);
typedef struct
{
    uintptr_t object;
    int32_t gid;
    int32_t x;
    int32_t y;
    int32_t ownerIndex;
    int32_t teamOld;
    int32_t teamNew;
    int32_t typeWord;
    uint8_t dead;
    uint8_t activeFlag;
} rcl_obj_t;
typedef struct
{
    uintptr_t elem;
    uintptr_t classRva;
    int32_t x;
    int32_t y;
    int32_t px;
    int32_t py;
    int32_t team;
    int32_t spawnX;
    int32_t spawnY;
    int32_t gid;
    uint64_t ptick;
    uint64_t qtick;
    int hasPrev;
    const char *name;
    const char *ownerName;
    int32_t targetX;
    int32_t targetY;
    int32_t ownerX;
    int32_t ownerY;
    float speed;
    float radius;
    float angle;
    uint64_t spawnedAt;
    float vx;
    float vy;
    int isThrower;
    int isBeam;
    int32_t spawnAreaRadius;
    int32_t spawnAreaActiveTime;
    int32_t castRange;
} rcl_proj_t;

typedef struct
{
    const char *name;
    float angle;
    int32_t spawnX;
    int32_t spawnY;
    int32_t x;
    int32_t y;
} rcl_proj_death_t;

#define RCL_SC_LEN_OFF 0x4ULL
#define RCL_SC_DATA_OFF 0x8ULL
#define RCL_SC_INLINE_MAX 7
#define RCL_PROJ_ANGLE_OFF 0x1d4ULL
#define RCL_PROJ_ISTHROWER_OFF 0xb8ULL
#define RCL_PROJ_DATA_NAME_OFF 0x58ULL
#define RCL_PROJ_NAME_MAX 64
#define RCL_PROJ_DEATH_MAX 16

#define RVA_BATTLEMODE_GETINSTANCE 0ULL
#define RVA_BATTLESCREEN__UPDATEMOVEMENT 0x7a60f4ULL
#define RVA_LOGICBATTLEMODECLIENT_GETOWNCHARACTER 0ULL
#define RVA_LOGICBATTLEMODECLIENT_GETOWNPLAYERTEAM 0ULL
#define RVA_LOGICBATTLEMODECLIENT_UPDATE 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETX 0xa23afcULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETY 0xa23b04ULL

#define OFF_BATTLESCREEN_AUTOFIREX 0xe6cULL
#define OFF_BATTLESCREEN_AUTOFIREY 0xe70ULL
#define OFF_CHARDATA_SPEED 0x1c4ULL

#define RCL_GATE_OFF 0x70ULL
#define RCL_MODE_MANAGER_OFF 0x28ULL
#define RCL_MGR_ARRAY_OFF 0x0ULL
#define RCL_MGR_COUNT_OFF 0xcULL
#define RCL_MGR_CAP_OFF 0x8ULL
#define RCL_MODE_INPUTMGR_OFF 0x58ULL
#define RCL_DC_RVA_LO 0xf74000ULL
#define RCL_OBJ_GLOBALID_OFF 0x8ULL
#define RCL_GID_FALLBACK_OFF 0x50ULL
#define RCL_SETINPUT_RVA 0xac3a58ULL
#define RCL_MOVE_RVA 0xac3a58ULL
#define RCL_HOOK_DEDUP_US 500ULL
#define RCL_CTRL_MOVE_X_OFF 0xfccULL
#define RCL_CTRL_MOVE_Y_OFF 0xfd0ULL
#define RCL_CTRL_MOVE_ON_OFF 0xf9cULL
#define RCL_CTRL_MOVE_ZERO_OFF 0xfa0ULL
#define RCL_CTRL_ANIM_RATE_OFF 0xf74ULL
#define RCL_CTRL_ANIM_FLAGS_OFF 0xf7fULL
#define RCL_CTRL_ANIM_RATE_BITS 0x3d4ccccdUL
#define RCL_CTRL_ANIM_FLAGS_VAL 0x0101U
#define RCL_MOVE_FLAG_10 1
#define RCL_MOVE_X_OFF 0x10cULL
#define RCL_MOVE_Y_OFF 0x110ULL
#define RCL_MOVE_KEY_OFF 0x114ULL
#define RCL_MOVE_ARM_OFF 0xacULL
#define RCL_MOVE_COORD_LIMIT 200000
#define RCL_ALLOC_RVA 0x00d8da2cULL
#define RCL_MSGCTOR_RVA 0x00a95798ULL
#define RCL_CI_MGR_QUEUE_OFF 0x20ULL

#define RCL_ADDINPUT_RVA 0x74675cULL
#define RCL_GETBATTLE_RVA 0x008c5130ULL
#define RCL_MGR_OFF 0x58ULL
#define RCL_QUEUE_OFF 0x20ULL
#define RCL_QUEUE_COUNT_OFF 0xcULL
#define RCL_TYPE_OFF 0x08ULL
#define RCL_X_OFF 0x0cULL
#define RCL_Y_OFF 0x10ULL
#define RCL_ALLOC_GOT_RVA 0x00f78180ULL
#define RCL_OWN_INNER_OFF 0x28ULL
#define RCL_BOX_PTR_OFF 0xf8ULL
#define RCL_MGR_SEQ_OFF 0x0cULL
#define RCL_OWN_ALIVE_OFF 0x140ULL
#define RCL_GATE_FLAG_OFF 0xacULL
#define RCL_CTRL_RAW_X_OFF 0xfa4ULL
#define RCL_CTRL_RAW_Y_OFF 0xfa8ULL
#define RCL_CTRL_ALIVE_OFF 0xf80ULL

#define RCL_BATTLE_RVA 0x1123e58ULL
#define RCL_CLIENT_OFF 0x28ULL
#define RCL_CLIENT_POS_X_OFF 0x80ULL
#define RCL_CLIENT_POS_Y_OFF 0x84ULL
#define RCL_OBJ_TEAM_OFF 0x40ULL
#define RCL_OBJ_OWNERINDEX_OFF 0x3cULL
#define RCL_OBJ_DEADFLAG_OFF 0xd0ULL
#define RCL_TYPE_MOVE_OFF 0x56ULL
#define RCL_TYPE_PROJ_OFF 0x57ULL
#define RCL_BOUNDS_X_OFF 0xccULL
#define RCL_BOUNDS_Y_OFF 0xd0ULL
#define RCL_CTRL_MODE_OFF 0x918ULL
#define RCL_OBJ_X_OFF 0x30ULL
#define RCL_OBJ_Y_OFF 0x34ULL
#define RCL_OBJ_ACTIVEFLAG_OFF 0x1e8ULL
#define RCL_MODE_TILEMAP_OFF 0xf8ULL
#define RCL_TILEMAP_WIDTH_OFF 0xc4ULL
#define RCL_TILEMAP_HEIGHT_OFF 0xc8ULL
#define RCL_TYPE_SLOT_OFF 0x28ULL
#define RCL_ELEM_BACK_OFF 0x18ULL
#define RCL_TEAM_OFF 0x4cULL
#define RCL_DEAD_OFF 0xd4ULL
#define RCL_ELEM_ID_OFF_2 0x48ULL
#define RCL_ELEM_TEAM_OFF_2 0x4cULL
#define RCL_ARRAY_OFF 0x0ULL

#define RCL_COUNT_OFF 0xcULL
#define RCL_OWNIDX_OFF_2 0xe0ULL
#define RCL_OWNTEAM_OFF_2 0xe4ULL
#define RCL_OWNIDX_OFF 0xe0ULL
#define RCL_OWNTEAM_OFF 0xe4ULL
#define RCL_MODEPAIRSET_RVA RCL_SETINPUT_RVA
#define RCL_STATE_RVA 0x1123e58ULL
#define RCL_STATE_ENUM_OFF 0x50ULL
#define RCL_SCENE_OFF 0x48ULL
#define RCL_CLIENT_HOP_OFF 0x28ULL
#define RCL_ELEM_DEF_OFF 0x10ULL
#define RCL_OFF 0x70ULL
#define RCL_NP_PTR_OFF 0x38ULL

#define RCL_MAP_BASE_OFF RCL_MODE_MANAGER_OFF
#define RCL_MAP_PTR_OFF RCL_MODE_TILEMAP_OFF
#define RCL_MAP_WIDTH_OFF RCL_TILEMAP_WIDTH_OFF
#define RCL_MAP_HEIGHT_OFF RCL_TILEMAP_HEIGHT_OFF
#define RCL_TILE_PTR_STRIDE 0x8ULL
#define RCL_TILE_TYPE_MOVE_OFF RCL_TYPE_MOVE_OFF
#define RCL_TILE_TYPE_PROJ_OFF RCL_TYPE_PROJ_OFF

#define RCL_STATE_BATTLE 5

#define RCL_CI_TYPE_TABLE_RVA 0x00e1e058ULL
#define RCL_CI_TABLE_TYPES 0x17ULL
#define RCL_CI_MAX_TABLE_TYPE 0x16UL
#define RCL_CI_FALLBACK_TYPE_CONST 0xdeadbeefUL
#define RCL_CI_HASH_MASK_SIZE 0x10UL
#define RCL_CI_HASH_PAD_INNER 0x36
#define RCL_CI_HASH_PAD_OUTER 0x5c
#define RCL_CI_HASH_INNER_MASK_RVA 0x00e1bbd0ULL
#define RCL_CI_HASH_OUTER_MASK_RVA 0x00e1bbf0ULL
#define RCL_BM_HASH_ENABLED_OFF 0x70ULL
#define RCL_BM_HASH_KEY_OFF 0x60ULL
#define RCL_CI_TOKEN_OFF 0x34UL
#define RCL_CI_TOKEN_READ_OFF 0x4UL
#define RCL_CI_TOKEN_READ_LEN 0x10UL
#define RCL_CI_TOKEN_MSG_LEN 0x14UL
#define RCL_CI_TOKEN_MASK 0x7fUL
#define RCL_CI_TOKEN_MIN 1UL

#define RCL_IMAGE_TEXT_WINDOW 0x4000ULL
#define RCL_CLASS_PROJ_RVA 0x000ff57b0ULL
#define RCL_PROJ_CLASS_ONLY 1

#define RCL_WRITE_GUARD 1
#define RCL_MGR_CAP_MAX 4096
#define RCL_MANAGER_MAX_OBJECTS 96
#define RCL_DC_RVA_SIZE 0xd4000ULL
#define RCL_OBJ_HIT_DUMP_MAX 64
#define RCL_QUEUE_GUARD 0

#define RCL_DT_MAX 12

#define RCL_OBJ_TEAM_MAX 7
#define RCL_JOURNAL 24
#define RCL_TILE_SIZE 300.0f
#define RCL_BS_MODE 0x8ac
#define RCL_PLAYER_GID 1000000
#define RCL_SHOT_GID 2000000
#define RCL_MATE_MAX 8
#define RCL_PLAYER_MAX 12
#define RCL_CAND 3
#define RCL_PROJ_MAX 16
#define RCL_DIFF_BYTES 0x100
#define RCL_COORD_ABS_MAX 1000000
#define RCL_OBJECT_MAX 64
#define RCL_IMAGE_SPAN 0x1164000ULL
#define RCL_OBJ_SLOTS 3
#define RCL_HOPS 2
#define RCL_TEAM_MAX_2 15
#define RCL_PLAYER_GID_MAX 2000000
#define RCL_VTABLE_SEGMENT "__DATA_CONST"
#define RCL_VTABLE_SEGMENT_ALT "__DATA"
#define RCL_SLOT_COUNT 34
#define RCL_HEAP_REGION_MAX 512
#define RCL_HEAP_REGION_MAX_SIZE 0x100000000ULL
#define RCL_TRAIL_MAX 8
#define RCL_GEOM 1
#define RCL_RADIUS_MIN 0.0f
#define RCL_RADIUS_MAX 600.0f
#define RCL_CAL_OFF_LO 0x20
#define RCL_CAL_OFF_HI 0x120
#define RCL_CAL_STEP 4
#define RCL_CAL_TOL 0.06f
#define RCL_CAL_TICKS 6
#ifndef RCL_DODGE_PROJ_ONLY

#ifndef RCL_PROJ_ANGLE_OFF

#ifndef RCL_JS_ENEMY_W
#endif

#endif

#ifndef RCL_JS_SPEED_FALLBACK
#endif

#ifndef RCL_JS_RADIUS_FALLBACK
#endif

#endif
#ifndef RCL_HIT_MARGIN
#endif
#ifndef RCL_DODGE_CLEAR_R
#endif
#ifndef RCL_RAGE_FORCE
#endif
#ifndef RCL_LOOKAHEAD_MAX
#endif
#ifndef RCL_ENGAGE_NEAR
#endif
#ifndef RCL_JS_DODGE
#endif
#ifndef RCL_DIR_COUNT
#endif
#ifndef RCL_HORIZON_S
#endif
#ifndef RCL_DATA_MOMENTUM
#endif
#ifndef RCL_WALL_PENALTY
#endif
#ifndef RCL_DATA_SPEED
#endif
#ifndef RCL_DATA_OWN_R
#define RCL_DATA_OWN_R 120.0f
#endif
#ifndef RCL_DATA_PROJ_R
#define RCL_DATA_PROJ_R 150.0f
#endif
#ifndef RCL_DATA_HOLD
#endif
#ifndef RCL_DATA_BAND
#endif
#ifndef RCL_DATA_CRIT_EVERY
#endif
#ifndef RCL_JS_CLEAR_STEPS
#endif
#ifndef RCL_PROJ_LIFE_MS
#endif
#ifndef RCL_OVERSHOOT
#endif
#ifndef RCL_FREEST_RADII
#endif
#ifndef RCL_FREEST_LOGS
#endif
#ifndef RCL_BODY_GAIN
#endif
#ifndef RCL_ETA_PENALTY
#endif
#ifndef RCL_JS_NOPREDICT
#endif
#ifndef RCL_GEOM
#define RCL_GEOM 1
#endif
#ifndef RCL_GEOM_LOGS
#endif
#ifndef RCL_RADIUS_MIN
#define RCL_RADIUS_MIN 0.0f
#endif
#ifndef RCL_RADIUS_MAX
#define RCL_RADIUS_MAX 600.0f
#endif
#ifndef RCL_RADIUS_MARGIN
#endif
#ifndef RCL_CAL_OFF_LO
#define RCL_CAL_OFF_LO 0x20
#endif
#ifndef RCL_CAL_OFF_HI
#define RCL_CAL_OFF_HI 0x120
#endif
#ifndef RCL_CAL_STEP
#define RCL_CAL_STEP 4
#endif
#ifndef RCL_CAL_TOL
#define RCL_CAL_TOL 0.06f
#endif
#ifndef RCL_CONTACT_LOGS
#endif
#ifndef RCL_SNAP
#endif
#ifndef RCL_SNAP_DELTA
#endif
#ifndef RCL_SNAP_HARD_OFF
#endif
#ifndef RCL_SNAP_MAG
#endif
#ifndef RCL_SNAP_LOGS
#endif
#ifndef RCL_SIDE_FLIP
#endif
#ifndef RCL_SIDE_STALE
#endif
#ifndef RCL_CAL_TICKS
#define RCL_CAL_TICKS 6
#endif
#ifndef RCL_CAL_MISS
#endif
#ifndef RCL_WALL_LOGS
#endif
#ifndef RCL_TEAM_LOGS
#endif
#define RCL_DATA_OWN_R 120.0f
#define RCL_GEOM 1
#define RCL_RADIUS_MAX 600.0f
#ifndef RCL_DODGE_PROJ_ONLY
#endif
#ifndef RCL_PROJ_ACTIVE_BYPASS
#endif
#ifndef RCL_JS_STICK
#endif
#ifndef RCL_JS_HOLD
#endif
#ifndef RCL_STICK_RAW_WRITE
#define RCL_PRED_SPAN 0x118
#endif
#ifndef RCL_LOG_PLANS
#endif


#define RCL_OFFSET_TABLE_REV 3
#define RCL_CANDIDATES_UNVERIFIED 1

#define RVA_CLIENTINPUTMANAGER_ADDINPUT 0x74675cULL
#define RVA_CLIENTINPUT_CONSTRUCTOR_INT 0xa95798ULL
#define RVA_CLIENTINPUT_HASHINNERMASK 0xe1bbd0ULL
#define RVA_CLIENTINPUT_HASHOUTERMASK 0xe1bbf0ULL
#define RVA_CLIENTINPUT_TYPECONSTANTTABLE 0xe1e058ULL
#define RVA_GAMESCREEN__GETLOGICBATTLE 0x8c5130ULL
#define RVA_LOGICBATTLEMODECLIENT_SETCLIENTPREDICTIONMOVETO 0xac3f20ULL
#define RVA_MESSAGEMANAGER__RECEIVEMESSAGE 0x75d648ULL
#define RVA_SETCLIENTPREDICTION 0xac3f20ULL

#define OFF_BATTLEMODE_CLIENTINPUTMANAGER 0x58ULL
#define OFF_BATTLEMODE_HASHENABLED 0x70ULL
#define OFF_BATTLEMODE_HASHKEY 0x60ULL
#define OFF_BATTLEMODE_OBJECTMANAGERPTR 0x28ULL
#define OFF_BATTLESCREEN_AIMTARGETID 0xee4ULL
#define OFF_BATTLESCREEN_AIMX 0xf7cULL
#define OFF_BATTLESCREEN_AIMY 0xf80ULL
#define OFF_BATTLESCREEN_ATTACKJOYHELD 0xf4aULL
#define OFF_BATTLESCREEN_AUTOFIREBTNHELD 0xf49ULL
#define OFF_BATTLESCREEN_CAMERAMODE 0x90cULL
#define OFF_BATTLESCREEN_MOVEPENDING 0xf4fULL
#define OFF_BATTLESCREEN_SCREENHEIGHT 0x8e8ULL
#define OFF_BATTLESCREEN_SCREENWIDTH 0x8e4ULL
#define OFF_BATTLESCREEN_SPECTATETEXTFIELD 0x3f8ULL
#define OFF_BATTLESCREEN_SPECTATEWIDGET 0x3e8ULL
#define OFF_BATTLESCREEN_ULTIJOYHELD 0xf4bULL
#define OFF_BATTLESCREEN_VIEWMATRIX 0x848ULL
#define OFF_CHARDATA_BRAWLERID 0x18ULL
#define OFF_CLIENTINPUT_SKILLDATA 0x40ULL
#define OFF_CLIENTINPUT_X 0xcULL
#define OFF_CLIENTINPUT_Y 0x10ULL
#define OFF_DECORATEDTEXTFIELD_GRADIENT 0x268ULL
#define OFF_DECORATEDTEXTFIELD_MARKER 0x44ULL
#define OFF_DECORATEDTEXTFIELD_TEXT 0xe0ULL
#define OFF_DISPLAYOBJECT_ISMOVIECLIPSLOT 0x80ULL
#define OFF_DISPLAYOBJECT_PARENT 0x38ULL
#define OFF_DISPLAYOBJECT_SCALEX 0x10ULL
#define OFF_DISPLAYOBJECT_SCALEY 0x1cULL
#define OFF_DISPLAYOBJECT_VISIBLE 0x8ULL
#define OFF_DISPLAYOBJECT_X 0x20ULL
#define OFF_DISPLAYOBJECT_Y 0x24ULL
#define OFF_DROPGUICONTAINER_MOVIECLIP 0x80ULL
#define OFF_GAMEOBJ_DEADFLAG 0xd0ULL
#define OFF_GAMEOBJ_TEAM 0x40ULL
#define OFF_GRADIENT_TABLE_INDEX 0x2eULL
#define OFF_GUI_SPRITECONTAINER 0xa0ULL
#define OFF_HERODATA_NAMEPTR 0x48ULL
#define OFF_JOY_CENTERX 0x9cULL
#define OFF_JOY_CENTERY 0xa0ULL
#define OFF_JOY_CURRENTX 0x94ULL
#define OFF_JOY_CURRENTY 0x98ULL
#define OFF_JOY_ISDRAGGING 0x10ULL
#define OFF_LOGICCHARACTERCLIENTOWN_SPEEDBUFF 0x1fcULL
#define OFF_LOGICCHARACTERCLIENT_BODY 0x3e8ULL
#define OFF_LOGICCHARACTERCLIENT_HYPERACTIVE 0x31eULL
#define OFF_LOGICDATATABLE_FINDBYNAME 0x30ULL
#define OFF_LOGICGAMEOBJECTCLIENT_OWNERINDEX 0x3cULL
#define OFF_LOGICPROJECTILECLIENT_DATANAME 0x58ULL
#define OFF_LOGICPROJECTILECLIENT_OWNERTEAM 0x40ULL
#define OFF_LOGICSKILLDATA_KIND 0x1acULL
#define OFF_MESSAGE_IPPTR 0x98ULL
#define OFF_MESSAGE_PORT 0x90ULL
#define OFF_MOVIECLIP_FRAMECOUNT 0x9eULL
#define OFF_OBJECTMANAGER_COUNT 0xcULL
#define OFF_OBJECTMANAGER_OBJECTSARRAY 0x0ULL
#define OFF_OBJECTMANAGER_PTRSTRIDE 0x8ULL
#define OFF_PROJECTILE_ANGLE 0x1d4ULL
#define OFF_PROJECTILE_ISINDIRECT 0xb8ULL
#define OFF_SCSTRING_DATA 0x8ULL
#define OFF_SCSTRING_LENGTH 0x4ULL
#define OFF_SOCKADDR_ADDR0 0x4ULL
#define OFF_SOCKADDR_ADDR1 0x5ULL
#define OFF_SOCKADDR_ADDR2 0x6ULL
#define OFF_SOCKADDR_ADDR3 0x7ULL
#define OFF_SOCKADDR_PORTHI 0x2ULL
#define OFF_SOCKADDR_PORTLO 0x3ULL
#define OFF_SPRITE_CHILDARRAY 0x50ULL
#define OFF_SPRITE_CHILDCOUNT 0x4eULL
#define OFF_STAGE_SPRITECONTAINER 0xa8ULL
#define OFF_TEAMCHATMESSAGE_MESSAGEOFFSET 0x90ULL
#define OFF_TEAMSETMEMBERREADYMESSAGE_STATEOFFSET 0x90ULL
#define OFF_TILEMAP_HEIGHT 0xc8ULL
#define OFF_TILEMAP_TILESARRAY 0x20ULL
#define OFF_TILEMAP_WIDTH 0xc4ULL
#define OFF_TILETYPEDATA_BLOCKSMOVEMENT 0x56ULL
#define OFF_TILETYPEDATA_BLOCKSPROJECTILES 0x57ULL

#define CAND_ANALYTICEVENT__ANALYTICEVENT 0xa89738ULL
#define CAND_ANALYTICEVENT__SETSTRING 0xa897f8ULL
#define CAND_BATTLESCREEN_GETCLOSESTTARGETFORAUTOSHOOT 0x7b91b8ULL
#define CAND_BATTLESCREEN__UPDATEAUTOSHOOT 0x7a4254ULL
#define CAND_CHARACTER__UPDATEHEALTHBAR 0x51d390ULL
#define CAND_GAMESTATEMANAGER__ISSTATE 0xa0fcc8ULL
#define CAND_GLOBALID__GETINSTANCEID 0xa632a8ULL
#define CAND_GUI__SHOWPOPUP 0x53da64ULL
#define CAND_LOGICBATTLEMODECLIENT__SETPLAYERAVATAR 0xac1e5cULL
#define CAND_LOGICCHARACTERCLIENT__GETCURRENTACTIVEORCASTINGSKILL 0x9e1e6cULL
#define CAND_LOGICCHARACTERCLIENT__GETLINKEDCARRYABLE 0x9e15a8ULL
#define CAND_LOGICGAMEMODEUTIL__ISTILEONPOISONAREA 0xb0a068ULL
#define CAND_LOGICPROJECTILEDATA_GETRADIUS 0x9aa738ULL
#define CAND_LOGICTILEMAP_GETTILE 0x902c88ULL
#define CAND_LOGICTILE__SETDATA 0x901260ULL
#define CAND_MAPEDITORMODIFIERPOPUP__MAPEDITORMODIFIERPOPUP 0x685718ULL
#define CAND_MAPEDITORSCREEN__INITCHARACTERS 0x8d9034ULL
#define CAND_MAPEDITORSCREEN__INITITEMS 0x8d8d48ULL
#define CAND_MAPEDITORSCREEN__INITRENDERSYSTEM 0x8d8cc0ULL
#define CAND_MAPEDITORSCREEN__UPDATECAMERAPARAMETERS 0x8d8a74ULL
#define CAND_MESSAGEMANAGER__SENDMESSAGE 0x75d59cULL
#define CAND_MOVIECLIPHELPER__SETTEXTANDSCALEIFNECESSARY 0xa4ca68ULL
#define CAND_POPUPBASE__POPUPBASE 0x695598ULL
#define CAND_PROJECTILE__UPDATE 0x4b1a98ULL
#define CAND_SCROLLAREA__SCROLLTO 0xb1ab78ULL
#define CAND_SCROLLAREA__UPDATEBOUNDS 0xb89c18ULL
#define CAND_SCSTRING_DESTRUCT 0xd37a80ULL

#define GUESS_ALLIANCEMANAGER_INSTANCE 0ULL
#define GUESS_ALLIANCEMANAGER__STARTSPECTATE 0x7892bcULL
#define GUESS_APPLICATION__COPYSTRING 0xda5fc0ULL
#define GUESS_AREAEFFECTDATA__GETACTIVETIMEMS 0x947b5cULL
#define GUESS_AREAEFFECTDATA__GETRADIUS 0x947b5cULL
#define GUESS_BATTLEMODE_GETINSTANCE 0xa05cccULL
#define GUESS_BATTLEMODE__ADDRESOURCESTOLOAD 0xa077e0ULL
#define GUESS_BATTLEMODE__ENTER 0xa07588ULL
#define GUESS_BATTLESCREEN_ACTIVATESKILL 0x79f8d0ULL
#define GUESS_BATTLESCREEN_FIREWRAPPERFN 0x79f8d0ULL
#define GUESS_BATTLESCREEN__BATTLESCREEN 0x795834ULL
#define GUESS_BATTLESCREEN__CALCULATEPROJECTILEPATH 0x7b5d24ULL
#define GUESS_BATTLESCREEN__HANDLETOUCHRELEASED 0x79dc8cULL
#define GUESS_BATTLESCREEN__JOYSTICKTOWORLD 0x7b9e24ULL
#define GUESS_BATTLESCREEN__SHOULDSHOWACCESSORYBUTTON 0x7b10ecULL
#define GUESS_BATTLESCREEN__STOPWITHSTICK 0x79c4bcULL
#define GUESS_BATTLESCREEN__TRYTOACTIVATESKILL 0x7aed48ULL
#define GUESS_BATTLESCREEN__UPDATE 0x4dec14ULL
#define GUESS_BATTLESCREEN__UPDATECAMERAPARAMETERS 0x7998bcULL
#define GUESS_CLIENTINPUTMESSAGE_SENDMOVEMENT 0x50ae2cULL
#define GUESS_COMBATHUD__SENDPINCOMMAND 0x5124e0ULL
#define GUESS_COMBATHUD__SENDSPRAYCOMMAND 0x512de8ULL
#define GUESS_COMBATHUD__SETMOVESTICKSTATE 0x52f18cULL
#define GUESS_COMBATHUD__SETSHOOTSTICKSTATE 0x52f18cULL
#define GUESS_COMBATHUD__TOGGLEEDITING 0x5111b0ULL
#define GUESS_COMBATHUD__UPDATE 0x51b3c8ULL
#define GUESS_CSVROW__GETBOOLEANVALUEAT 0xb97804ULL
#define GUESS_CSVROW__GETINTEGERVALUEAT 0xb97804ULL
#define GUESS_CSVROW__GETNAME 0xb97804ULL
#define GUESS_CSVROW__GETVALUEAT 0xb97804ULL
#define GUESS_CSVTABLE__GETCOLUMNINDEXBYNAME 0xb97ff4ULL
#define GUESS_CUSTOMBUTTON_ONBUTTONPRESSED 0x543520ULL
#define GUESS_DECALMANAGER__DECALMANAGER 0x4a9ac8ULL
#define GUESS_DECORATEDTEXTFIELDSETPLAYERNAME 0x54332cULL
#define GUESS_DISPLAYOBJECT__REMOVEFROMPARENT 0xb4fd0cULL
#define GUESS_DISPLAYOBJECT__SETXY 0xb4f66cULL
#define GUESS_DROPGUICONTAINER__CTORFROMEXPORT 0x485b68ULL
#define GUESS_FRAMERATEMANAGER_TARGETFPS 0x118fe34ULL
#define GUESS_FRAMERATEMANAGER__SETLIMIT 0xd44558ULL
#define GUESS_FRAMERATEMANAGER__SETSEGMENT 0xd44054ULL
#define GUESS_GAMEBUTTONCTOR 0x542e38ULL
#define GUESS_GAMEBUTTON_SETTEXT 0x54332cULL
#define GUESS_GAMEMAIN__UPDATE 0x4483ccULL
#define GUESS_GAMEOBJECTMANAGER__GAMEOBJECTMANAGER 0x4ab19cULL
#define GUESS_GAMESETTINGS__ISFIXEDJOYSTICKENABLED 0x9f38f4ULL
#define GUESS_GAMESLIDERCOMPONENT__GAMESLIDERCOMPONENT 0x54708cULL
#define GUESS_GAMESLIDERCOMPONENT__SETVALUEBOUNDS 0x5476a4ULL
#define GUESS_GAMESTATEMANAGER__GETINSTANCE 0xa0f4fcULL
#define GUESS_GUI_GETINSTANCE 0x4e18e8ULL
#define GUESS_GUI_SHOWFLOATERTEXTATDEFAULTPOS 0x8c51fcULL
#define GUESS_GUI__GETDEFAULTFLOATERPOS 0x79eb7cULL
#define GUESS_GUI__SHOWFLOATERTEXTAT 0x53ce7cULL
#define GUESS_HANDLEJOYSTICK 0x532a00ULL
#define GUESS_HASHTAGCODEGENERATOR__CTOR 0xb06de4ULL
#define GUESS_HASHTAGCODEGENERATOR__DTOR 0xb06e64ULL
#define GUESS_HASHTAGCODEGENERATOR__ISVALID 0xb06f78ULL
#define GUESS_HASHTAGCODEGENERATOR__TOID 0xbb6380ULL
#define GUESS_HOMEMODE__GETINSTANCE 0xa12090ULL
#define GUESS_LOGICBATTLEMODECLIENT_GETOWNCHARACTER 0xac3dccULL
#define GUESS_LOGICBATTLEMODECLIENT_GETOWNPLAYERTEAM 0xac3a58ULL
#define GUESS_LOGICBATTLEMODECLIENT_UPDATE 0xac1e64ULL
#define GUESS_LOGICBATTLEMODECLIENT__GETOWNPLAYERINDEX 0xac3a58ULL
#define GUESS_LOGICBATTLEMODECLIENT__GETTILEMAP 0xac3d74ULL
#define GUESS_LOGICBATTLEMODECLIENT__LOGICBATTLEMODECLIENT 0xac1620ULL
#define GUESS_LOGICBATTLEMODECLIENT__SETRANDOMSEED 0xac1824ULL
#define GUESS_LOGICCHARACTERCLIENTOWN__CLIENTPREDICTIONPAUSEMOVEMENTFORSKILLCASTING 0x9e3884ULL
#define GUESS_LOGICCHARACTERCLIENTOWN__CLIENTPREDICTIONUPDATEATTACKDIRECTION 0x9e3884ULL
#define GUESS_LOGICCHARACTERCLIENT__CANMOVEANDUSETHISSKILLSIMULTANEOUSLY 0x9e0d3cULL
#define GUESS_LOGICCHARACTERCLIENT__GETCARRYABLEDATA 0x9dffe8ULL
#define GUESS_LOGICCHARACTERCLIENT__GETSKILLAT 0x9e0d3cULL
#define GUESS_LOGICCHARACTERCLIENT__GETWEAPONSKILL 0x9e0d3cULL
#define GUESS_LOGICCHARACTERCLIENT__ISIMMUNEORUNTARGETABLE 0x9e1878ULL
#define GUESS_LOGICCHARACTERDATA_GETCOLLISIONRADIUS 0x96340cULL
#define GUESS_LOGICCHARACTERDATA_GETSPEED 0x9633d8ULL
#define GUESS_LOGICCOMPRESSEDSTRING__LOGICCOMPRESSEDSTRING 0xbb5d40ULL
#define GUESS_LOGICDATATABLES_TABLEARRAY 0x1190eb4ULL
#define GUESS_LOGICDATATABLES__GETBASETILEDATA 0x985540ULL
#define GUESS_LOGICDATATABLES__GETOPENTILEDATA 0x985540ULL
#define GUESS_LOGICDATATABLES__GETSIEGEBOLTTILEDATA 0x985540ULL
#define GUESS_LOGICDATA_GETNAME 0x973a74ULL
#define GUESS_LOGICGAMEOBJECTCLIENT_GETDATA 0xa0d69cULL
#define GUESS_LOGICGAMEOBJECTCLIENT_GETGLOBALID 0xa0d968ULL
#define GUESS_LOGICGAMEOBJECTCLIENT_GETZ 0ULL
#define GUESS_LOGICGAMEOBJECTMANAGERCLIENT__FINDGAMEOBJECT 0xa11240ULL
#define GUESS_LOGICGAMEOBJECTMANAGERCLIENT__GETGAMEOBJECTS 0xa0e118ULL
#define GUESS_LOGICGAMEOBJECTMANAGERCLIENT__LOGICGAMEOBJECTMANAGERCLIENT 0xa0dcfcULL
#define GUESS_LOGICGAMEOBJECTSERVER__GETDATA 0xa19e0cULL
#define GUESS_LOGICJSONOBJECT__PUT 0xb27b2cULL
#define GUESS_LOGICLONGTOCODECONVERTERUTIL__CONVERT 0xbb73a0ULL
#define GUESS_LOGICLONGTOCODECONVERTERUTIL__LOGICLONGTOCODECONVERTERUTIL 0xbd000cULL
#define GUESS_LOGICLONGTOCODECONVERTERUTIL__TOCODE 0x7887d8ULL
#define GUESS_LOGICPLAYERMAPUTIL__TILEDATATOTILECODE 0xa6fdd0ULL
#define GUESS_LOGICPLAYERMAP__SAVE 0xa6c264ULL
#define GUESS_LOGICPROJECTILECLIENT_CTOR 0xa1e5c4ULL
#define GUESS_LOGICPROJECTILECLIENT_DESTRUCT 0xa1e5c4ULL
#define GUESS_LOGICPROJECTILECLIENT_GETDATA 0xa1eb04ULL
#define GUESS_LOGICPROJECTILECLIENT_GETTARGETX 0xa1ecd8ULL
#define GUESS_LOGICPROJECTILECLIENT_GETTARGETY 0xa1ecd8ULL
#define GUESS_LOGICPROJECTILEDATA_GETRENDERING 0x9aa800ULL
#define GUESS_LOGICPROJECTILEDATA_GETSPEED 0x9aa660ULL
#define GUESS_LOGICPROJECTILEDATA__GETNUMEARLYTICKS 0x9aab4cULL
#define GUESS_LOGICPROJECTILEDATA__GETSPAWNAREAEFFECT 0x9aa800ULL
#define GUESS_LOGICPROJECTILEDATA__ISBEAM 0x9aa800ULL
#define GUESS_LOGICPROJECTILEDATA__ISOWNTEAMPROJECTILE 0x4aa1b0ULL
#define GUESS_LOGICPROJECTILESERVER__RUNEARLYTICKS 0xa28fc8ULL
#define GUESS_LOGICPROJECTILESERVER__SHOOTPROJECTILE 0xa27ffcULL
#define GUESS_LOGICRANDOM__SETITERATEDRANDOMSEED 0xba1c94ULL
#define GUESS_LOGICSKILLCLIENT__CANACTIVATE 0xa2a43cULL
#define GUESS_LOGICSKILLCLIENT__GETDATA 0xa2a2bcULL
#define GUESS_LOGICSKILLDATA__GETACTIVETIME 0x9bda44ULL
#define GUESS_LOGICSKILLDATA__GETBEHAVIOUR 0x9bdf5cULL
#define GUESS_LOGICSKILLDATA__GETCASTINGRANGE 0x9bda44ULL
#define GUESS_LOGICSKILLDATA__GETLINKEDSKILL 0x9bdf5cULL
#define GUESS_LOGICSKILLDATA__GETMAXCHARGE 0x9bdcacULL
#define GUESS_LOGICSKILLDATA__GETMSBETWEENATTACKS 0x9bdcacULL
#define GUESS_LOGICSKILLDATA__GETPROJECTILEDATA 0x9bda44ULL
#define GUESS_LOGICSKILLDATA__GETRECHARGETIME 0x9bdcacULL
#define GUESS_LOGICTILEDATA__BLOCKSMOVEMENT 0x9d0c30ULL
#define GUESS_LOGICTILEDATA__BLOCKSPROJECTILES 0x9d0c30ULL
#define GUESS_LOGICTILEMAP__ISPLAYERLINEOFSIGHTCLEAR 0x906390ULL
#define GUESS_LOGICTILEMAP__ISPLAYERLINEOFSIGHTCLEAR1 0x906390ULL
#define GUESS_LOGICTILEMAP__LOGICTILEMAP 0x4ab2c8ULL
#define GUESS_MAPEDITORMODIFIERITEM__MAPEDITORMODIFIERITEM 0x684bfcULL
#define GUESS_MAPEDITORMODIFIERPOPUP__ADDMODIFIERITEM 0x68610cULL
#define GUESS_MESSAGEMANAGER_INSTANCE 0ULL
#define GUESS_MOVIECLIP_GOTOANDSTOP 0xb55394ULL
#define GUESS_MOVIECLIP__GETCHILDCLIPBYNAME 0xb55f04ULL
#define GUESS_MOVIECLIP__GETTEXTFIELDBYNAME 0xb56494ULL
#define GUESS_MOVIECLIP__GOTOANDSTOPFRAMEINDEX 0xb55394ULL
#define GUESS_MOVIECLIP__SETCHILDVISIBLE 0xb56494ULL
#define GUESS_NAME_APPLYDECORATION 0x5398b8ULL
#define GUESS_NAME_SETUPDECORATED 0x539850ULL
#define GUESS_NATIVECOPYTOCLIPBOARD 0xd413c0ULL
#define GUESS_OPERATOR_NEW 0x1045b6cULL
#define GUESS_PIRANHAMESSAGE_CTOR 0xba1f38ULL
#define GUESS_PROJECTILE_CTOR 0x4b141cULL
#define GUESS_RENDERSYSTEM__RENDERSYSTEM 0x4b4774ULL
#define GUESS_RESOURCELISTENER__ADDFILE 0xbd4cd0ULL
#define GUESS_RESOURCEMANAGER__GETCSV 0xb2801cULL
#define GUESS_RESOURCEMANAGER__ISRESOURCELOADED 0xb26378ULL
#define GUESS_SCREEN_HEIGHTGLOBAL 0x11a3590ULL
#define GUESS_SCREEN_WIDTHGLOBAL 0x11a358cULL
#define GUESS_SCREEN__GETDPICLASS 0xd47bccULL
#define GUESS_SCREEN__GETHEIGHT 0xd47818ULL
#define GUESS_SCREEN__GETWIDTH 0xd47818ULL
#define GUESS_SCROLLAREA__ADDCONTENT 0x64e44cULL
#define GUESS_SCROLLAREA__REMOVEALLCONTENT 0xb89ec8ULL
#define GUESS_SKILLCOMMANDTYPETABLE 0ULL
#define GUESS_SPRITE_SPRITE 0xb66c00ULL
#define GUESS_SPRITE__ADDCHILD 0xb66ee0ULL
#define GUESS_SPRITE__ADDCHILDAT 0xb66ee0ULL
#define GUESS_SPRITE__REMOVECHILD 0xb6710cULL
#define GUESS_STAGEINSTANCEGLOBALPTR 0ULL
#define GUESS_STAGE_ADDCHILD 0xb6cb44ULL
#define GUESS_STARTSPECTATEMESSAGE__CTOR 0xaa7ef8ULL
#define GUESS_STRINGCTOR 0xd37ae8ULL
#define GUESS_STRINGTABLE_GETMOVIECLIP 0xb265fcULL
#define GUESS_STRINGTABLE__GETMOVIECLIP 0xa21174ULL
#define GUESS_STRING__FORMAT 0xd3a788ULL
#define GUESS_TEAMCHATMESSAGE__CTOR 0xa82954ULL
#define GUESS_TEAMSETMEMBERREADYMESSAGE__CTOR 0xa860c0ULL
#define GUESS_TEXTFIELD_SETTEXT 0xb84c6cULL
#define GUESS_TEXTFIELD_SETTEXT_UI 0x54332cULL
#define GUESS_VTABLE_CHARACTER_DATA 0ULL
#define GUESS_VTABLE_DECORATED_TEXT_FIELD 0ULL
#define GUESS_VTABLE_GRADIENT_DATA 0ULL
#define GUESS_VTABLE_PROJECTILE_DATA 0ULL
#define GUESS_VTABLE_TEXT_FIELD 0ULL

#define RCL_SLOT_RVA_0 0x00ad4ed0ULL
#define RCL_SLOT_RVA_1 0x00ad521cULL
#define RCL_SLOT_RVA_2 0ULL
#define RCL_SLOT_RVA_3 0ULL
#define RCL_SLOT_RVA_4 0ULL
#define RCL_SLOT_RVA_5 0x00c33690ULL
#define RCL_SLOT_RVA_6 0x00b9dc24ULL
#define RCL_SLOT_RVA_7 0ULL
#define RCL_SLOT_RVA_8 0ULL
#define RCL_SLOT_RVA_9 0ULL
#define RCL_SLOT_RVA_10 0ULL
#define RCL_SLOT_RVA_11 0x008c7fbcULL
#define RCL_SLOT_RVA_12 0x00000000ULL
#define RCL_SLOT_RVA_13 0x00bcfbe8ULL
#define RCL_SLOT_RVA_14 0x00bcfc28ULL
#define RCL_SLOT_RVA_15 0ULL
#define RCL_SLOT_RVA_16 0x008c6150ULL
#define RCL_SLOT_RVA_17 0x00ac3f20ULL
#define RCL_SLOT_RVA_18 0x00746898ULL
#define RCL_SLOT_RVA_19 0x00b8ae88ULL
#define RCL_SLOT_RVA_20 0x00b8ac7cULL
#define RCL_SLOT_RVA_21 0ULL
#define RCL_SLOT_RVA_22 0ULL
#define RCL_SLOT_RVA_23 0x00b85fe0ULL
#define RCL_SLOT_RVA_24 0x00b867d8ULL
#define RCL_SLOT_RVA_25 0x00b9e188ULL
#define RCL_SLOT_RVA_26 0x00b9dc8cULL
#define RCL_SLOT_RVA_27 0ULL
#define RCL_SLOT_RVA_28 0x008c7f9cULL
#define RCL_SLOT_RVA_29 0x008c7facULL
#define RCL_SLOT_RVA_30 0x00b898e8ULL
#define RCL_SLOT_RVA_31 0x00b89c10ULL

#define RCL_TYPE_SLOT_RVA_0 0x0014c81cULL
#define RCL_TYPE_SLOT_RVA_1 0x00a31768ULL
#define RCL_TYPE_SLOT_RVA_2 0x009f4ec8ULL
#define RCL_TYPE_SLOT_RVA_3 0x00314ca0ULL
#define RCL_TYPE_SLOT_RVA_4 0x00490b54ULL
#define RCL_TYPE_SLOT_RVA_5 0x0086f494ULL
#define RCL_TYPE_SLOT_RVA_6 0x00370688ULL
#define RCL_TYPE_SLOT_RVA_8 0x00490d94ULL

#endif
