#ifndef TITANOX_DIAG_DIAG_H
#define TITANOX_DIAG_DIAG_H

#include "core/types.h"

extern int t_active;
extern uintptr_t t_ag_manager;
extern int t_ag_objectCount;
extern uintptr_t t_base;
extern int64_t t_elem_moves;
extern uint64_t t_engage_writes;
extern int t_enq_x;
extern int t_enq_y;
extern uint64_t t_gate_writes;
extern uint64_t t_human_live;
extern int64_t t_moves;
extern int32_t t_own_team_5;
extern int t_own_x;
extern int t_own_y;
extern uint64_t t_pred_calls;
extern uint64_t t_pred_fails;
extern int t_readback;
extern uintptr_t t_scene_object;
extern uint64_t t_slot_hits[TNX_SLOT_COUNT];
extern int t_test_state_2;
extern int t_tested_2;
extern uint64_t t_tick_2;
extern tnx_vtcensus_t t_vtcensus[TNX_VTCENSUS_MAX];
extern int t_vtcensus_used;
extern uintptr_t t_wit_elem;
extern int32_t t_wit_x0;
extern int32_t t_wit_x1;
extern int32_t t_wit_y0;
extern int32_t t_wit_y1;
void tnx_audit_all(void);
const char *tnx_cand_name(int slot);
void tnx_candidates(uintptr_t ownElem, int *out);
void tnx_class_dump(const tnx_obj_t *objects, int usable);
void tnx_core(void);
void tnx_diag_report(const char *why);
void tnx_drift(void);
void tnx_dump(void);
void tnx_engage_report(const char *why);
int tnx_fields(void);
int tnx_fields_pair(uintptr_t *srcOut, int32_t *xOut, int32_t *yOut);
void tnx_gate_report(int slotHit);
uint64_t tnx_hook_dispatches(void);
void tnx_hop_dump(uintptr_t client, uintptr_t inner);
void tnx_map_dump(uintptr_t bounds);
int tnx_object_detail(uintptr_t manager, int limit);
uint64_t tnx_object_dispatches(void);
void tnx_players_dump(uintptr_t players, uintptr_t array, int32_t count, int32_t capacity);
void tnx_pos_trace(const tnx_obj_t *objects, int usable);
void tnx_queue_line(void);
void tnx_readback(int plus);
void tnx_report_manager(const char *tag, uintptr_t manager);
void tnx_report_mode_hit(const char *tag, uintptr_t slot, uintptr_t object);
void tnx_slot_diag(const char *why);
int tnx_slot_probe(void);
void tnx_slot_table_dump(void);
void tnx_statics(void);
void tnx_team_dump(const tnx_obj_t *objects, int usable);
void tnx_test(const tnx_obj_t *objects, int usable, int ownIndex);
void tnx_trail_dump(void);
int tnx_trail_verdict(const tnx_trail_t *entry, char *buf, size_t size);
int tnx_vtcensus_top(int byShaped);
void tnx_window(int plus);
int tnx_witness(int32_t *x, int32_t *y);
void tnx_witness_line(int plus);
void tnx_write_test(const tnx_obj_t *objects, int usable, int ownIndex);

extern uint64_t t_engage_last;
extern uint64_t t_engage_start;
extern int t_gate2_seen;
extern int t_gate3_seen;
extern uint64_t t_move_tick;
extern int32_t t_own_x_2;
extern int32_t t_own_y_2;
extern int32_t t_pick_x;
extern int32_t t_pick_y;
void tnx_census(void);
void tnx_crit_probe(float px, float py);
void tnx_drive_note(int32_t ownX, int32_t ownY, int32_t tx, int32_t ty, int32_t appX, int32_t appY, int32_t pairX, int32_t pairY);
void tnx_frame(void);
void tnx_hop2(void);
int tnx_interp(int32_t *x, int32_t *y);
void tnx_interp_line(void);
int tnx_pred_probe(uintptr_t pred, int *alignOut, int *readOut, int *writeOut, int *vtOut);
void tnx_probe(void);
uint64_t tnx_rend_delta(void);
void tnx_snapshot_3(void);
const char *tnx_state_name(void);
uint64_t tnx_upd_delta(void);

#endif
