
#ifndef OFFSETS_H
#define OFFSETS_H

#include <stddef.h>
#include <stdint.h>
#include <mach-o/loader.h>

#define RVA_ANALYTICEVENT__SETSTRING 0xb47828ULL
#define RVA_BATTLESCREEN__UPDATEAUTOSHOOT 0x807668ULL
#define RVA_COMBATHUD__SETMOVESTICKSTATE 0x5857ecULL
#define RVA_LOGICCHARACTERCLIENTOWN__CLIENTPREDICTIONPAUSEMOVEMENTFORSKILLCASTING 0xab7094ULL
#define RVA_LOGICGAMEPLAYUTIL__GETCLOSESTANYCOLLISION 0xbd55c4ULL
#define RVA_LOGICSKILLDATA__GETRECHARGETIME 0xa943bcULL
#define RVA_MAPEDITORSCREEN__INITITEMS 0x82c500ULL
#define RVA_MESSAGEMANAGER__RECEIVEMESSAGE 0x7bace8ULL
#define RVA_SPRITE_SPRITE 0xc2d680ULL
#define RVA_STAGE_ADDCHILD 0xc33690ULL
#define RVA_LOGICSKILLDATA__GETMAXCHARGE 0xa943bcULL
#define RVA_LOGICSKILLDATA__GETMSBETWEENATTACKS 0xa943bcULL

#define RVA_LOGICBATTLEMODECLIENT_SETCLIENTPREDICTIONMOVETO 0xac3f20ULL
#define RVA_SETCLIENTPREDICTION 0xac3f20ULL

#define RVA_CLIENTINPUTMANAGER_ADDINPUT 0x74675cULL

#define RVA_BATTLEMODE_GETINSTANCE 0ULL
#define RVA_BATTLESCREEN__BATTLESCREEN 0ULL
#define RVA_BATTLESCREEN__TRYTOACTIVATESKILL 0ULL
#define RVA_BATTLESCREEN__UPDATEMOVEMENT 0ULL
#define RVA_BATTLESCREEN_ACTIVATESKILL 0ULL
#define RVA_BATTLESCREEN_FIREWRAPPERFN 0ULL
#define RVA_BATTLESCREEN_GETCLOSESTTARGETFORAUTOSHOOT 0ULL
#define RVA_CLIENTINPUTMESSAGE_SENDMOVEMENT 0ULL
#define RVA_COMBATHUD__SETSHOOTSTICKSTATE 0ULL
#define RVA_DISPLAYOBJECT__SETXY 0ULL
#define RVA_LOGICBATTLEMODECLIENT_GETOWNCHARACTER 0ULL
#define RVA_LOGICBATTLEMODECLIENT_GETOWNPLAYERTEAM 0ULL
#define RVA_LOGICBATTLEMODECLIENT_UPDATE 0ULL
#define RVA_LOGICCHARACTERDATA_GETCOLLISIONRADIUS 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETDATA 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETGLOBALID 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETX 0ULL
#define RVA_LOGICGAMEOBJECTCLIENT_GETY 0ULL
#define RVA_LOGICGAMEOBJECTMANAGERCLIENT__GETGAMEOBJECTS 0ULL
#define RVA_LOGICPROJECTILEDATA_GETRADIUS 0ULL
#define RVA_LOGICPROJECTILEDATA_GETSPEED 0ULL
#define RVA_LOGICTILEMAP__ISPLAYERLINEOFSIGHTCLEAR 0ULL
#define RVA_MOVIECLIP__GETTEXTFIELDBYNAME 0ULL
#define RVA_STRINGTABLE_GETMOVIECLIP 0ULL
#define RVA_TEXTFIELD_SETTEXT 0ULL

#define OFF_APPLICATION__COPYSTRING 0xe4a7b4ULL
#define OFF_BATTLEMODE_CLIENTINPUTMANAGER 0x58ULL
#define OFF_BATTLEMODE_OBJECTMANAGERPTR 0x28ULL
#define OFF_BATTLESCREEN_AUTOFIREX 0xe6cULL
#define OFF_BATTLESCREEN_AUTOFIREY 0xe70ULL
#define OFF_BATTLESCREEN_AUTOSHOOTPREDOFF 0x66cULL
#define OFF_BATTLESCREEN_MANUALFIREX 0xf04ULL
#define OFF_BATTLESCREEN_MANUALFIREY 0xf08ULL
#define OFF_BATTLESCREEN_SCREENHEIGHT 0x888ULL
#define OFF_BATTLESCREEN_SCREENWIDTH 0x884ULL
#define OFF_BATTLESCREEN_VIEWMATRIX 0x7e8ULL
#define OFF_CHARDATA_BRAWLERID 0x18ULL
#define OFF_CHARDATA_SPEED 0x1c4ULL
#define OFF_CLIENTINPUT_X 0xcULL
#define OFF_CLIENTINPUT_Y 0x10ULL
#define OFF_FRAMERATEMANAGER__SETSEGMENT 0xddbde0ULL
#define OFF_GAMEOBJ_DEADFLAG 0xd0ULL
#define OFF_GAMEOBJ_TEAM 0x40ULL
#define OFF_HERODATA_NAMEPTR 0x48ULL
#define OFF_JOY_CENTERX 0x9cULL
#define OFF_JOY_CENTERY 0xa0ULL
#define OFF_JOY_CURRENTX 0x94ULL
#define OFF_JOY_CURRENTY 0x98ULL
#define OFF_JOY_ISDRAGGING 0x10ULL
#define OFF_MESSAGE_IPPTR 0x98ULL
#define OFF_MESSAGE_PORT 0x90ULL
#define OFF_OBJECTMANAGER_COUNT 0xcULL
#define OFF_OBJECTMANAGER_OBJECTSARRAY 0x0ULL
#define OFF_OBJECTMANAGER_PTRSTRIDE 0x8ULL
#define OFF_PROJECTILE_SPAWNANGLE 0xb8ULL
#define OFF_SCSTRING_DATA 0x8ULL
#define OFF_SCSTRING_LENGTH 0x4ULL
#define OFF_SCREEN__GETDPICLASS 0xde2200ULL
#define OFF_SCREEN__GETHEIGHT 0xde21f4ULL
#define OFF_SOCKADDR_ADDR0 0x4ULL
#define OFF_SOCKADDR_ADDR1 0x5ULL
#define OFF_SOCKADDR_ADDR2 0x6ULL
#define OFF_SOCKADDR_ADDR3 0x7ULL
#define OFF_SOCKADDR_PORTHI 0x2ULL
#define OFF_SOCKADDR_PORTLO 0x3ULL
#define OFF_STAGEINSTANCEGLOBALPTR 0x12393e0ULL
#define OFF_STRINGCTOR 0xdcf8f0ULL
#define OFF_STRING__FORMAT 0xdd244cULL
#define OFF_TILEMAP_HEIGHT 0xc8ULL
#define OFF_TILEMAP_TILESARRAY 0x20ULL
#define OFF_TILEMAP_WIDTH 0xc4ULL
#define OFF_TILETYPEDATA_BLOCKSMOVEMENT 0x56ULL
#define OFF_TILETYPEDATA_BLOCKSPROJECTILES 0x57ULL
#define OFF_VTABLE_CHARACTER_DATA 0x44bf6f8ULL
#define OFF_VTABLE_PROJECTILE_DATA 0x11501b0ULL
#define OFF_NATIVECOPYTOCLIPBOARD 0xdd91f8ULL

#define OFF_GAMEOBJ_GID 0x8
#define OFF_GAMEOBJ_X 0x30
#define OFF_GAMEOBJ_Y 0x34
#define OFF_GAMEOBJ_OWNERINDEX 0x3c
#define OFF_GAMEOBJ_ACTIVEFLAG 0x1e8
#define OFF_CTRL_STICK_X 0xfa4
#define OFF_CTRL_STICK_Y 0xfa8
#define OFF_CTRL_APPLIED_X 0xfcc
#define OFF_CTRL_APPLIED_Y 0xfd0
#define OFF_CTRL_TOUCH_GATE 0xf7f
#define OFF_CTRL_TOUCH_STATE 0xf80
#define OFF_CTRL_TOUCH_ID 0xf84
#define OFF_MODE_PREDICT_X 0x1d4
#define OFF_MODE_PREDICT_Y 0x1d8
#define OFF_CTRL_APPLIED_IDLE -300

typedef struct {
    uintptr_t base;
    const struct mach_header_64 *hdr;
} image_ref_t;

#ifdef __cplusplus
extern "C" {
#endif

uintptr_t rt_resolve_method(image_ref_t img, const char *cls, const char *meth, uintptr_t *func_starts, size_t starts_n, uintptr_t *xref_pc_out);
void rt_dump_image(image_ref_t img);
void rt_dump_target(const char *name, uintptr_t target);
int rt_is_code(image_ref_t img, uintptr_t target);

#ifdef __cplusplus
}
#endif

#endif

