#ifndef TITANOX_INPUT_MOVE_H
#define TITANOX_INPUT_MOVE_H

#include "core/types.h"

extern uint64_t t_diag_us;
extern uint64_t t_diag_max_us;
extern int t_dead_probe_done;
extern uint64_t t_clamped;
extern uint64_t t_ctrl_dead;
extern uint64_t t_stuck_3;
extern uint64_t t_mask_before;
extern int t_body_blocks;
extern int t_body_mine;
extern int t_body_enemy;
extern int t_body_logs;
extern uint64_t t_human_live;
extern int t_input_skips;
extern int t_wrote_input;
extern int t_engaged_frame;
extern int t_neutral_logs;
extern int t_test_state_2;
extern uint64_t t_test_tick;
extern int t_test_before_x;
extern int t_test_before_y;
extern int t_test_after_x_2;
extern int t_test_after_y_2;
extern int t_moved_2;
extern int t_moved2_2;
extern int t_kept_2;
extern int t_tested_2;
extern uint64_t t_enqueues;
extern int t_enq_x;
extern int t_enq_y;
extern int t_q_before;
extern int t_q_after;
extern int t_readback;
extern int t_readback_tick;
extern int t_hop2_logs;
extern int t_hop2_filled;
extern uintptr_t t_hop2;
extern int t_queue_logs;
extern int t_window_logs;
extern uint64_t t_push_frame;
extern uint64_t t_test_tickbase;
extern int t_enq_ok;
extern const char *t_alloc_how;
extern void *t_msg;
extern int t_seq_before;
extern int t_seq_after;
extern int t_q_before_2;
extern int t_q_after_2;
extern void *t_q_last;
extern int32_t t_scene_before_x;
extern int32_t t_scene_before_y;
extern uint64_t t_watch_from;
extern int t_watch_logs;
extern uintptr_t t_pred_last;
extern int t_predict_logs;
extern uint64_t t_pred_calls;
extern uint64_t t_pred_fails;
extern uintptr_t t_wit_elem;
extern int32_t t_wit_x0;
extern int32_t t_wit_y0;
extern int32_t t_wit_x1;
extern int32_t t_wit_y1;
extern int32_t t_own_held_x;
extern int32_t t_own_held_y;
extern int32_t t_own_flag;
extern int t_have_wit;
extern int t_active;
extern int t_calls;
extern int t_act_logs;
extern int t_wit_logs;
extern int t_own_logs_3;
extern int t_probe_done;
extern int64_t t_moves;
extern int64_t t_elem_moves;
extern uintptr_t t_joystick;
extern uint64_t t_joystick_writes;
extern uint64_t t_joystick_took;
extern int32_t t_stick_x;
extern int32_t t_stick_y;
extern int t_stick_hold;
extern uint64_t t_stick_tick;
extern int t_engaged_ticks;
extern long long t_sum_x;
extern long long t_sum_y;
extern int t_route_seeded;
extern int32_t t_last_own_x;
extern int32_t t_last_own_y;
extern int t_precond;
extern int t_gate;
extern int t_accepted;
extern int t_proofs;
extern int t_drove;
extern uint64_t t_drive_tick;
extern float t_mark;
extern float t_dot;
extern float t_last_dx;
extern float t_last_dy;
extern int32_t t_raw_x;
extern int32_t t_raw_y;
extern int32_t t_app_x;
extern int32_t t_app_y;

int tnx_mode_2(void);
float tnx_look_ms(void);
int tnx_ctrl_ok(uintptr_t ctrl);
void *tnx_msg_alloc(void);
void *tnx_q_last(void);
uintptr_t tnx_entry_2(uintptr_t rva);
void *tnx_manager(void);
int tnx_queue_count(uintptr_t *mgrOut);
int tnx_predict(int32_t x, int32_t y);
int tnx_pending(int want, uint64_t *mask);
int tnx_enqueue(int x, int y);

int tnx_enqueue_type(int x, int y, int type);
int tnx_move_to_2(int32_t x, int32_t y, float ox, float oy);
uintptr_t tnx_move_carrier_2(void);
void tnx_move_locate(float ox, float oy);
int tnx_move_pair_ok(uintptr_t obj, int32_t *outX, int32_t *outY);
int tnx_move_near_own(uintptr_t obj, float ox, float oy, int32_t *outX, int32_t *outY);
uintptr_t tnx_move_vt_rva(uintptr_t obj);
int tnx_move_arm_byte(uintptr_t obj);
extern int t_move_probe;
extern int t_move_rej;
extern int t_move_n;
extern int t_move_ok;
extern uintptr_t t_move_own;
extern int32_t t_move_x;
extern int32_t t_move_y;
int tnx_witness(int32_t *x, int32_t *y);
void tnx_probe(void);
int tnx_resolve_own(const tnx_obj_t *objects, int usable, int *indexOut, const char **fromOut);
void tnx_actuate(void);
void tnx_witness_line(int plus);
int tnx_fields_pair(uintptr_t *srcOut, int32_t *xOut, int32_t *yOut);
int tnx_fields(void);
void tnx_window(int plus);
void tnx_test(const tnx_obj_t *objects, int usable, int ownIndex);
void tnx_queue_line(void);
void tnx_hop2(void);
float tnx_seg_dist(float ax, float ay, float bx, float by, float px, float py);
int tnx_proj_vel(const tnx_proj_t *p, float *vxOut, float *vyOut);
uintptr_t tnx_input_mgr(void);
void tnx_input_release(void);
void tnx_snapshot_3(void);
void tnx_drag(int engaged, int haveOwn, int32_t ownX, int32_t ownY, float dirX, float dirY);
void tnx_stick(int engaged, float dirX, float dirY);
void tnx_route(int engaged);
void tnx_threats(void);
int tnx_body_blocked(float x, float y, float ownX, float ownY);
uintptr_t tnx_client(void);

extern int t_enq_stop_1;
extern int t_enq_stop_2;
extern int t_enq_stop_3;
extern int t_enq_stop_5;

#endif
